#!/bin/bash
NC='\033[0m'            # No Color
RED='\033[0;31m'            # Red
LIGHTRED='\033[1;31m'       # Light Red
GREEN='\033[0;32'           # Green
LIGHTGREEN='\033[1;32'      # Light Green
BLUE='\033[0;34m'           # Blue
LIGHTBLUE='\033[1;34m'      # Light Blue
CYAN='\033[0;36m'           # Cyan
LIGHTCYAN='\033[1;36m'      # Light Cyan
YELLOW='\033[0;33m'         # Yellow
LIGHTYELLOW='\033[1;33m'    # Light Yellow
PURPLE='\033[0;35m'         # Purple
LIGHTPURPLE='\033[1;35m'    # Light Purple

# Installation script for macrice
echo
# Begin installation process
echo -e "Now installing ${BLUE}macrice${NC}..." && echo
#   Install EVERYTHING to usr/local/share/macrice/*
mkdir /usr/local/share/macrice && echo "..."
cp -r scripts /usr/local/share/macrice/scripts && echo "......"
cp -r assets /usr/local/share/macrice/assets && echo "........."
cp -r dotfiles /usr/local/share/macrice/dotfiles && echo "............"

# Installs macrice.sh to /usr/local/bin/macrice as executable
cp scripts/macrice.sh scripts/macrice && echo "..............."
chmod a+x scripts/macrice && echo ".................."
sudo cp scripts/macrice /usr/local/bin/macrice && echo ".....................   !" && echo
# End installation process
echo -e "${BLUE}macrice${NC} is now installed!"
echo -e "Use '${BLUE}macrice${NC} ${YELLOW}help${NC}' for instructions"