#!/bin/bash
NC='\033[0m'            # No Color
RED='\033[0;31m'            # Red
LIGHTRED='\033[1;31m'       # Light Red
GREEN='\033[0;32'           # Green
LIGHTGREEN='\033[1;32'      # Light Green
BLUE='\033[0;34m'           # Blue
LIGHTBLUE='\033[1;34m'      # Light Blue
CYAN='\033[0;36m'           # Cyan
LIGHTCYAN='\033[1;36m'      # Light Cyan
YELLOW='\033[0;33m'         # Yellow
LIGHTYELLOW='\033[1;33m'    # Light Yellow
PURPLE='\033[0;35m'         # Purple
LIGHTPURPLE='\033[1;35m'    # Light Purple

# Installation script for torpdots
echo
# Begin installation process
echo -e "Now installing ${BLUE}torpdots${NC}..." && echo
#   Install EVERYTHING to usr/local/share/torpdots/*
mkdir /usr/local/share/torpdots && echo "..."
cp -r scripts /usr/local/share/torpdots/scripts && echo "......"
cp -r assets /usr/local/share/torpdots/assets && echo "........."
cp -r dotfiles /usr/local/share/torpdots/dotfiles && echo "............"

# Installs torpdots.sh to /usr/local/bin/torpdots as executable
cp scripts/torpdots.sh scripts/torpdots && echo "..............."
chmod a+x scripts/torpdots && echo ".................."
sudo cp scripts/torpdots /usr/local/bin/torpdots && echo ".....................   !" && echo
# End installation process
echo -e "${BLUE}torpdots${NC} is now installed!"
echo -e "Use '${BLUE}torpdots${NC} ${YELLOW}help${NC}' for instructions"