#!/bin/bash

# macdot — glryan@uw.edu	|	https://griffinryan.com/

# TO-DO: Create a `macdot restore` function
#        that restores the backup /~/.macdot/ to /~/.

# macdot main     set at: /usr/local/bin/macdot
# functions: help, list, formula, cask, apple, dot
# path: /opt/homebrew/Cellar/macdot

# all macdot() functions are set here

function showInfo() {
    # run script for info.sh
    bash /opt/homebrew/Cellar/macdot/**/lib/help
}

function displayList() {
    # run script for list.sh
    bash /opt/homebrew/Cellar/macdot/**/lib/list
}

function brewFormula() {
    # run script for formula.sh
    bash /opt/homebrew/Cellar/macdot/**/lib/formula
}

function brewCask() {
    # run script for cask.sh
    bash /opt/homebrew/Cellar/macdot/**/lib/cask
}

function appleConfig() {
    # run Applescript for apple executable
    bash /opt/homebrew/Cellar/macdot/**/lib/apple
}

function dotConfig() {
    # run script for dot.sh
    bash /opt/homebrew/Cellar/macdot/**/lib/dot
}

function saveConfig() {
    bash /opt/homebrew/Cellar/macdot/**/lib/save
}

function restoreConfig() {
    bash /opt/homebrew/Cellar/macdot/**/lib/restore
}

function backupConfig() {
    bash /opt/homebrew/Cellar/macdot/**/lib/backup
}

function uninstallTorpdots() {
    # run script for uninstall.sh
    bash /opt/homebrew/Cellar/macdot/**/lib/uninstall
}

function itermConfig() {
    bash /opt/homebrew/Cellar/macdot/**/lib/itermconfig
}

function showHelp() {
    bash /opt/homebrew/Cellar/macdot/**/lib/morehelp
}

case $1 in
  help | -h) showHelp;;
  list | -l) displayList;;
  kegs | keg) brewFormula;;
  save | Save) saveConfig;;
  restore | revert) restoreConfig;;
  iterm | iterm2) itermConfig;;
  casks | cask) brewCask;;
  apple | -a) appleConfig;;
  dot | -d) dotConfig;;
  help | -h) showHelp;;
  *) showInfo;;
esac

unset showInfo;
unset displayList;
unset brewFormula;
unset brewCask;
unset appleConfig;
unset dotConfig;
