#!/bin/bash

# macrice — glryan@uw.edu	|	https://griffinryan.com/

# TO-DO: Create a `macrice restore` function
#        that restores the backup /~/.macrice/ to /~/.

# macrice main     set at: /usr/local/bin/macrice
# functions: help, list, formula, cask, apple, dot
# path: /opt/homebrew/Cellar/macrice

# all macrice() functions are set here

function showInfo() {
    # run script for info.sh
    bash /opt/homebrew/Cellar/macrice/**/lib/help
}

function displayList() {
    # run script for list.sh
    bash /opt/homebrew/Cellar/macrice/**/lib/list
}

function brewFormula() {
    # run script for formula.sh
    bash /opt/homebrew/Cellar/macrice/**/lib/formula
}

function brewCask() {
    # run script for cask.sh
    bash /opt/homebrew/Cellar/macrice/**/lib/cask
}

function appleConfig() {
    # run Applescript for apple executable
    bash /opt/homebrew/Cellar/macrice/**/lib/apple
}

function dotConfig() {
    # run script for dot.sh
    bash /opt/homebrew/Cellar/macrice/**/lib/dot
}

function saveConfig() {
    bash /opt/homebrew/Cellar/macrice/**/lib/save
}

function restoreConfig() {
    bash /opt/homebrew/Cellar/macrice/**/lib/restore
}

function backupConfig() {
    bash /opt/homebrew/Cellar/macrice/**/lib/backup
}

function uninstallTorpdots() {
    # run script for uninstall.sh
    bash /opt/homebrew/Cellar/macrice/**/lib/uninstall
}

function itermConfig() {
    bash /opt/homebrew/Cellar/macrice/**/lib/itermconfig
}

# main loop set here
if [[ -z "$1" ]]; then
    # uses info.sh
    showInfo;
elif [[ "$1" == "help" || "$1" == "-h" ]]; then
    showInfo;
elif [[ "$1" == " " || "$1" == "  " ]]; then
    showInfo;
elif [[ "$2" == "help" || "$2" == "-h" ]]; then
    showInfo;
fi;

if [[ "$1" == "list" || "$1" == "-l" ]]; then
    # uses list.sh
    displayList;
elif [[ "$1" == "kegs" || "$1" == "keg" ]]; then
    # uses formula.sh
    brewFormula;
elif [[ "$1" == "save" || "$1" == "Save" ]]; then
    # uses save.sh
    saveConfig;
elif [[ "$1" == "restore" || "$1" == "revert" ]]; then
    # uses restore.sh
    restoreConfig;
elif [[ "$1" == "backup" || "$1" == "backup" ]]; then
    # uses restore.sh
    backupConfig;
elif [[ "$1" == "iterm" || "$1" == "iterm2"  ]]; then
    # uses itermconfig.sh
    itermConfig;
elif [[ "$1" == "cask" || "$1" == "casks" || "$1" == "-c" ]]; then
    # uses cask.sh
    brewCask;
elif [[ "$1" == "apple" || "$1" == "-a" ]]; then
    # uses apple (executable Applescript)
    appleConfig;
elif [[ "$1" == "dot" || "$1" == "-d" ]]; then
    dotConfig;
fi;

unset showInfo;
unset displayList;
unset brewFormula;
unset brewCask;
unset appleConfig;
unset dotConfig;