# acountry
# Autogenerated from man page /opt/homebrew/share/man/man1/acountry.1
complete -c acountry -s d -d 'Print some extra debugging output'
complete -c acountry -s h -l help -d 'Display this help and exit'
complete -c acountry -s v -d 'Be more verbose.  Print extra information'

