# addftinfo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/addftinfo.1
complete -c addftinfo -s v -d 'prints the version number'

