# adig
# Autogenerated from man page /opt/homebrew/share/man/man1/adig.1
complete -c adig -s c -d 'Set the query class'
complete -c adig -s d -d 'Print some extra debugging output'
complete -c adig -s f -d 'Add a flag'
complete -c adig -s h -l help -d 'Display this help and exit'
complete -c adig -s T -d 'Use specified TCP port to connect to DNS server'
complete -c adig -s s -d 'Connect to specified DNS server, instead of the system\'s default one(s)'
complete -c adig -s t -d 'Query records of specified type'
complete -c adig -s U -d 'Use specified UDP port to connect to DNS server'
complete -c adig -s x -d 'For an IPv4 -t PTR a. b. c. d lookup, query for . br d. c. b. a. in-addr'
complete -c adig -o xx -d 'As for -x and an IPv6 address, compact a. b. c. z'

