# afconvert
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/afconvert.1
complete -c afconvert -s h -d 'print help text El'

