# afmtodit
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/afmtodit.1
complete -c afmtodit -s a -d 'Use  n as the slant parameter in the font file; this is used by groff in the …'
complete -c afmtodit -s d -d 'The device description file is  desc_file rather than the default  DESC '
complete -c afmtodit -s e -d 'The PostScript font should be reencoded to use the encoding described in enc_…'
complete -c afmtodit -s i -d 'Generate an italic correction for each character so that  the character\'s wid…'
complete -c afmtodit -s m -d 'Prevent negative left italic correction values'
complete -c afmtodit -s n -d 'Don\'t output a  ligatures command for this font'
complete -c afmtodit -s s -d 'The font is special'
complete -c afmtodit -s v -d 'Print version'
complete -c afmtodit -o i50 -d 'for italic fonts'
complete -c afmtodit -o i0 -d 'to improve spacing with eqn (1)'
complete -c afmtodit -s x -d 'Don\'t use the built-in Adobe Glyph List.  FILES'

