# apfs_unlockfv
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/apfs_unlockfv.8
complete -c apfs_unlockfv -s h -d 'Print a usage message.  El -hang -offset indent'
complete -c apfs_unlockfv -s W -d 'Unlock with empty password'

