# apfs_systemsnapshot
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/apfs_systemsnapshot.8
complete -c apfs_systemsnapshot -s r -d 'Tag snapshot_name as the root snapshot to boot from upon next boot'
complete -c apfs_systemsnapshot -s s -d 'Create a new system snapshot named snapshot_name'
complete -c apfs_systemsnapshot -s h -d 'Print a usage message'

