# apfs_hfs_convert
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/apfs_hfs_convert.8
complete -c apfs_hfs_convert -s e -d 'Estimate the APFS metadata size after conversion'
complete -c apfs_hfs_convert -s v -d 'Increase verbosity of the output'
complete -c apfs_hfs_convert -s s -d 'Force the converted volume to be case-sensitive'
complete -c apfs_hfs_convert -s S -d 'Print statistics about the conversion to the supplied path'
complete -c apfs_hfs_convert -s n -d 'Do not finalize the conversion to APFS.  Volume remains HFS'
complete -c apfs_hfs_convert -s f -d 'Force conversion if volume is dirty (journal is non-empty, volume had inconsi…'
complete -c apfs_hfs_convert -s F -d 'Volume number index (0-based) should be formatted as fixed-size'
complete -c apfs_hfs_convert -s M -d 'When converting LwVM systems, which require a special "conversion mount" of t…'
complete -c apfs_hfs_convert -s o -d 'NX or APFS format options'
complete -c apfs_hfs_convert -s g -d 'If conversion succeeds, modify the GPT UUID'
complete -c apfs_hfs_convert -s D -d 'Convert all former and current directory hardlinks to files/aliases'
complete -c apfs_hfs_convert -l feature-format -d 'Allow for one-off specific formatting features to be toggled on or off during…'

