# app-sso
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/app-sso.1
complete -c app-sso -s a -d 'Display the login dialog for the specified realm, or if the user has already …'
complete -c app-sso -s u -d 'The username for authentication'
complete -c app-sso -s f -d 'Display the login screen even if the user is already authenticated'
complete -c app-sso -s q -d 'Suppress the information that is normally printed after authentication.  El'
complete -c app-sso -s d -d 'Logs out any user logged into the specified realm'
complete -c app-sso -s c -d 'Displays the "Change Password" dialog for the specified realm'
complete -c app-sso -s l -d 'Prints the list of configured realms'
complete -c app-sso -s i -d 'Print information about the currently configured realm'
complete -c app-sso -s v -d 'Print the complete site code cache in the results.  El'
complete -c app-sso -s s -d 'Perform a site lookup for the specified realm.  -tag -width -indent'
complete -c app-sso -s r -d 'Reset the cache for the specified realm'
complete -c app-sso -s k -d 'Resets the "login automatically" option for the specified realm'
complete -c app-sso -s p -d 'Allow user setup to proceed if you are using "delayUserSetup" in your configu…'
complete -c app-sso -s t -d 'Prints the kerberos settings that are shared with other processes for the spe…'
complete -c app-sso -s j -d 'Format the output of this command as JSON instead of property list format'
complete -c app-sso -s h -d 'Print a synopsis of the above document'

