# applesingle
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/applesingle.1
complete -c applesingle -s f -d 'perform the operation even if the output file already exists'
complete -c applesingle -s h -d 'display version and usage, then quit'
complete -c applesingle -s v -d 'be verbose'
complete -c applesingle -s V -d 'display version, then quit'
complete -c applesingle -s c -d 'For decode, read encoded data from the standand input'
complete -c applesingle -s C -d 'create output files in dir'
complete -c applesingle -s o -d 'Use name for output, overriding any stored or default name'
complete -c applesingle -s s -d 'override the default suffix for the given encoding'
complete -c applesingle -s R -d 'don\'t use BinHex runlength compression when encoding'
complete -c applesingle -s t -d 'Specify MacBinary encoding type'

