# arch
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/arch.1
complete -c arch -o 32 -d 'Add the native 32-bit architecture to the list of architectures'
complete -c arch -o 64 -d 'Add the native 64-bit architecture to the list of architectures'
complete -c arch -s c -d 'Clears the environment that will be passed to the command to be run'
complete -c arch -s d -d 'Deletes the named environment variable from the environment that will be pass…'
complete -c arch -s e -d 'Assigns the given value to the named environment variable in the environment …'
complete -c arch -s h -d 'Prints a usage message and exits'

