# arp
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/arp.8
complete -c arp -s a -d 'The program displays or deletes all of the current ARP entries'
complete -c arp -s d -d 'A super-user may delete an entry for the host called hostname with the d flag'
complete -c arp -s i -d 'Limit the operation scope to the ARP entries on interface'
complete -c arp -s l -d 'Show link-layer reachability information'
complete -c arp -s n -d 'Show network addresses as numbers (normally arp attempts to display addresses…'
complete -c arp -s s -d 'Create an ARP entry for the host called hostname with the Ethernet address et…'
complete -c arp -s S -d 'Is just like s except any existing ARP entry for this host will be deleted fi…'
complete -c arp -s f -d 'Cause the file filename to be read and multiple entries to be set in the ARP …'
complete -c arp -s x -d 'Show extended link-layer reachability information in addition to that shown b…'

