# assetutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/assetutil.1
complete -c assetutil -s V -d 'version information for assetutil'
complete -c assetutil -s I -d 'Produce a JSON description of the asset catalog object with the given name to…'
complete -c assetutil -s i -d 'Keep all assets that have idiom that is given on the command line'
complete -c assetutil -s s -d 'Keep all assets that have scale factor that is given on the command line, pre…'
complete -c assetutil -s p -d 'Keep all assets that have the display gamut that is given on the command line…'
complete -c assetutil -s M -d 'Keep all assets that have memory class that is given on the command line, pre…'
complete -c assetutil -s g -d 'Keep all assets that have graphics class that is given on the command line'
complete -c assetutil -s h -d 'process the hosted idioms list, this is a list of the idioms that must always…'
complete -c assetutil -s t -d 'Subtype to keep (integer)'
complete -c assetutil -s c -d 'Main Assets'
complete -c assetutil -s o -d 'Output file name, if no output file is given then input file is overwritten'
complete -c assetutil -s T -d 'compare thinning attributes \'scale=2:idiom=phone:memory=2:graphicsclass=MTL1,…'
complete -c assetutil -s n -d 'given a comma separated list of names, any assets in the car file that match …'
complete -c assetutil -s Z -d 'do an integrity check of the input file.  \\" Ends the list Pp'

