# auditd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/auditd.8
complete -c auditd -s d -d 'Starts the daemon in debug mode \\[em] it will not daemonize'
complete -c auditd -s l -d 'This option is for when auditd is configured to start on-demand using launchd…'

