# auditreduce
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/auditreduce.1
complete -c auditreduce -s A -d 'Select all records'
complete -c auditreduce -s a -d 'Select records that occurred after or on the given datetime'
complete -c auditreduce -s b -d 'Select records that occurred before the given datetime'
complete -c auditreduce -s c -d 'Select records matching the given audit classes specified as a comma separate…'
complete -c auditreduce -s d -d 'Select records that occurred on a given date'
complete -c auditreduce -s e -d 'Select records with the given effective user ID or name'
complete -c auditreduce -s f -d 'Select records with the given effective group ID or name'
complete -c auditreduce -s g -d 'Select records with the given real group ID or name'
complete -c auditreduce -s j -d 'Select records having a subject token with matching ID'
complete -c auditreduce -s m -d 'Select records with the given event name or number'
complete -c auditreduce -s o -d '-tag -width "'
complete -c auditreduce -s r -d 'Select records with the given real user ID or name'
complete -c auditreduce -s U -d 'Use unbuffered output'
complete -c auditreduce -s u -d 'Select records with the given audit ID'
complete -c auditreduce -s v -d 'Invert sense of matching, to select records that do not match'

