# authopen
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/authopen.1
complete -c authopen -o stdoutpipe -d 'specifies that STDOUT_FILENO has been dup2()\'d onto a pipe to a parent proces…'
complete -c authopen -o extauth -d 'specifies that authopen should read one AuthorizationExternalForm structure f…'
complete -c authopen -s w -d 'instructs authopen to open filename read/write and truncate it'
complete -c authopen -s a -d 'append to filename rather than truncating it (truncating is the default)'
complete -c authopen -s c -d 'create the file if it doesn\'t exist.  m requires c Ns'
complete -c authopen -s m -d 'specify the mode bits if a file is created'
complete -c authopen -s o -d 'numerically specify the flags that should be passed to "open" "2"'
complete -c authopen -s x -d 'require that the file being created not exist'

