# automountd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/automountd.8
complete -c automountd -s v -d 'Log to syslogd 8 more detailed information about actions taken by automountd'
complete -c automountd -s n -d 'Disable browsing of all maps'
complete -c automountd -s T -d 'Increase by 1 the logging level for messages printed to the standard output i…'
complete -c automountd -s o -d 'Apply the options specified by opts to all mounts by default'
complete -c automountd -s D -d 'Set the environment value specified by name to the specified value'

