# automount
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/automount.8
complete -c automount -s v -d 'Print more detailed information about actions taken by automount'
complete -c automount -s c -d 'Tell automountd 8 to flush any cached information it has'
complete -c automount -s u -d 'Unmount all non-busy automounted mounts.  Top-level triggers are preserved'
complete -c automount -s t -d 'Set to timeout seconds the time after which an automounted file system will b…'

