# automator
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/automator.1
complete -c automator -s D -d 'Set variable name to value for this run of workflow'
complete -c automator -s i -d 'Set input as the input to workflow'
complete -c automator -s v -d 'Run in verbose mode.  El Pp'

