# auvaltool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/auvaltool.1
complete -c auvaltool -s h -d 'print help text'
complete -c auvaltool -s a -d 'lists all available AudioUnits of any type'
complete -c auvaltool -s s -d 'lists all available AudioUnits of type \'TYPE\''
complete -c auvaltool -s v -d 'opens the AudioUnit specified by the TYPE SUBT MANU component ID\'s and tests …'
complete -c auvaltool -o vt -d 'iterates through all of the AU\'s of specified TYPE and MANU'
complete -c auvaltool -o de -d 'execution is terminated when first error is encountered'
complete -c auvaltool -o dw -d 'execution is terminated when first warning is encountered'
complete -c auvaltool -s c -d 'continue validating when an error occurs in batch mode'
complete -c auvaltool -s q -d 'quiet - does no printing except for errors or warnings'
complete -c auvaltool -o qp -d 'doesn\'t print parameter or Factory Presets information'
complete -c auvaltool -s o -d 'only runs a basic open and initialize test'
complete -c auvaltool -s r -d 'repeat the whole process of validation N times'
complete -c auvaltool -s w -d 'wait after finished - good for profiling memory usage see \'man leaks\''
complete -c auvaltool -o vers -d 'The version is printed to stdout'
complete -c auvaltool -o versh -d 'The version is printed to stdout in hexadecimal'
complete -c auvaltool -s f -d 'Each line in the file should contain one complete command.  El'

