# avconvert
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/avconvert.1
complete -c avconvert -o '\\-source' -d 'The source media file to be converted'
complete -c avconvert -o '\\-output' -d 'The output movie file to be created'
complete -c avconvert -o '\\-preset' -d 'Use the specified preset for file conversion'
complete -c avconvert -o '\\-disableFastStart' -d 'Disable fast-start movie creation'
complete -c avconvert -o '\\-disableMetadataFilter' -d 'Disable the metadata filter.   Use with caution'
complete -c avconvert -o '\\-duration' -d 'Trim the output movie to num seconds (decimal allowed)'
complete -c avconvert -o '\\-help' -d 'Print command usage and list available preset names'
complete -c avconvert -o '\\-multiPass' -d 'Perform a higher quality multi-pass encode in the conversion'
complete -c avconvert -o '\\-progress' -d 'Display progress during the conversion (default with -v)'
complete -c avconvert -o '\\-replace' -d 'Overwrite the output file, if it already exists'
complete -c avconvert -o '\\-start' -d 'Skip the first num seconds (decimal allowed) of the source movie'
complete -c avconvert -o '\\-verbose' -d 'Print additional information about the conversion'

