# avmediainfo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/avmediainfo.1
complete -c avmediainfo -o '\\-formatextensions' -d 'Displays format description extensions for each track'
complete -c avmediainfo -o '\\-samples' -d 'Lists high level sample information for each track (Decode Time(stamp), Prese…'
complete -c avmediainfo -o '\\-chunks' -d 'Lists high level chunk information (Index, Offset, Size, Sample Count, Sample…'
complete -c avmediainfo -o '\\-interleave' -d 'Shows the interleave by listing the chunks in offset order'
complete -c avmediainfo -o '\\-integeroffsets' -d 'Displays all offsets as integers, instead of hex'
complete -c avmediainfo -o '\\-brief' -d 'Displays a brief description of the movie'
complete -c avmediainfo -o '\\-help' -d 'Show help.  Ed'
complete -c avmediainfo -o '\\-metadata' -d 'Displays metadata information based on options provided'
complete -c avmediainfo -o '\\-mediatype' -d 'Restricts which tracks have chunk and/or sample information displayed based o…'

