# banner
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man6/banner.6
complete -c banner -s d -d 'Enable debug'
complete -c banner -s t -d 'Enable trace'
complete -c banner -s w -d 'Change the output from a width of 132 to width, suitable for a narrow terminal'

