# base64
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/base64.1
complete -c base64 -s b -d '--break= Ns Ar count Insert line breaks every count characters'
complete -c base64 -s d
complete -c base64 -s D -d '--decode Decode incoming Base64 stream into binary data.  Pp'
complete -c base64 -s h -d '--help Print usage summary and exit.  Pp'
complete -c base64 -s i -d '--input= Ns Ar input_file Read input from input_file'
complete -c base64 -s o -d '--output= Ns Ar output_file Write output to output_file'

