# bash
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/bash.1
complete -c bash -s c -d 'If the  -c option is present, then commands are read from R string '
complete -c bash -s i -d 'If the  -i option is present, the shell is R interactive '
complete -c bash -s l -d 'Make  bash act as if it had been invoked as a login shell (see '
complete -c bash -s r -d 'If the  -r option is present, the shell becomes  restricted (see '
complete -c bash -s s -d 'If the  -s option is present, or if no arguments remain after option processi…'
complete -c bash -s D -d 'A list of all double-quoted strings preceded by $ is printed on the standard …'
complete -c bash -l debugger -d 'Arrange for the debugger profile to be executed before the shell starts'
complete -c bash -l dump-po-strings -d 'Equivalent to -D, but the output is in the GNU gettext po (portable object) f…'
complete -c bash -l dump-strings -d 'Equivalent to -D'
complete -c bash -l help -d 'Display a usage message on standard output and exit successfully'
complete -c bash -l rcfile -d 'PD Execute commands from  file instead of the standard personal initializatio…'
complete -c bash -l login -d 'Equivalent to -l'
complete -c bash -l noediting -d 'Do not use the GNU  readline library to read command lines when the shell is …'
complete -c bash -l noprofile -d 'Do not read either the system-wide startup file '
complete -c bash -l norc -d 'Do not read and execute the personal initialization file  ~/'
complete -c bash -l posix -d 'Change the behavior of bash where the default operation differs from the POSI…'
complete -c bash -l restricted -d 'The shell becomes restricted (see . SM  "RESTRICTED SHELL" below)'
complete -c bash -l verbose -d 'Equivalent to  -v'
complete -c bash -s o -d 'set builtin below)'
complete -c bash -l init-file
complete -c bash -l version -d 'Show version information for this instance of bash on the standard output and…'
complete -c bash -s a -d 'option to specify an array.   The read builtin accepts a'
complete -c bash -s f -d 'option has been set, bash scans each word for the characters * , ? , and [ '
complete -c bash -s F -d 'option to declare or typeset will list the function names only (and optionall…'
complete -c bash -s b -d 'True if file exists and is a block special file'
complete -c bash -s d -d 'True if file exists and is a directory'
complete -c bash -s e -d 'True if file exists'
complete -c bash -s g -d 'True if file exists and is set-group-id'
complete -c bash -s h -d 'True if file exists and is a symbolic link'
complete -c bash -s k -d 'True if file exists and its ``sticky\'\' bit is set'
complete -c bash -s p -d 'True if file exists and is a named pipe (FIFO)'
complete -c bash -s t -d 'True if file descriptor fd is open and refers to a terminal'
complete -c bash -s u -d 'True if file exists and its set-user-id bit is set'
complete -c bash -s w -d 'True if file exists and is writable'
complete -c bash -s x -d 'True if file exists and is executable'
complete -c bash -s O -d 'True if file exists and is owned by the effective user id'
complete -c bash -s G -d 'True if file exists and is owned by the effective group id'
complete -c bash -s L -d 'True if file exists and is a symbolic link'
complete -c bash -s S -d 'True if file exists and is a socket'
complete -c bash -s N -d 'True if file exists and has been modified since it was last read'
complete -c bash -s z -d 'True if the length of string is zero'
complete -c bash -s n
complete -c bash -o eq
complete -c bash -o ne
complete -c bash -o lt
complete -c bash -o le
complete -c bash -o gt -d or
complete -c bash -o ge -d 'These arithmetic binary operators return true if arg1 is equal to, not equal …'
complete -c bash -s m -d 'Use keymap as the keymap to be affected by the subsequent bindings'
complete -c bash -s P -d 'List current readline function names and bindings'
complete -c bash -s v -d 'Display readline variable names and values in such a way that they can be re-…'
complete -c bash -s V -d 'List current readline variable names and values'
complete -c bash -s q -d 'Query about which keys invoke the named function'
complete -c bash -s A -d 'The action may be one of the following to generate a list of possible complet…'
complete -c bash -s W -d 'The wordlist is split using the characters in the'
complete -c bash -s C -d 'command is executed in a subshell environment, and its output is used as the …'
complete -c bash -s X -d 'filterpat is a pattern as used for filename expansion'
complete -c bash -s E -d 'option disables the interpretation of these escape characters, even on system…'
complete -c bash -s B
complete -c bash -s T
complete -c bash -s H

