# bc
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/bc.1
complete -c bc -s h -l help -d 'Print the usage and exit'
complete -c bc -s i -l interactive -d 'Force interactive mode'
complete -c bc -s l -l mathlib -d 'Define the standard math library'
complete -c bc -s w -l warn -d 'Give warnings for extensions to POSIX bc'
complete -c bc -s s -l standard -d 'Process exactly the POSIX bc language'
complete -c bc -s q -l quiet -d 'Do not print the normal GNU bc welcome'
complete -c bc -s v -l version -d 'Print the version number and copyright and quit'

