# bioutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/bioutil.1
complete -c bioutil -s r -d 'Read Touch ID configuration'
complete -c bioutil -s w -d 'Write Touch ID configuration'
complete -c bioutil -s s -d 'Indicates that system-wide configuration is to be read/written (user-specific…'
complete -c bioutil -s f -d 'Enables (1) or disables (0) overall Touch ID functionality (system-wide confi…'
complete -c bioutil -s u -d 'Enables (1) or disables (0) Touch ID for unlock'
complete -c bioutil -s a -d 'Enables (1) or disables (0) Touch ID for ApplePay (user-specific configuratio…'
complete -c bioutil -s o -d 'Sets Touch ID timeout (in seconds, system-wide configuration only)'
complete -c bioutil -s c -d 'Provides number of enrolled fingerprints of the current user or of all users …'
complete -c bioutil -s p -d 'Deletes all enrolled fingerprints of the current user or of all users (when r…'
complete -c bioutil -s d -d 'Deletes all enrolled fingerprints of the user with given user ID (must be run…'

