# bitcode_strip
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/bitcode_strip.1
complete -c bitcode_strip -s r -d 'Remove the __LLVM bitcode segment entirely'
complete -c bitcode_strip -s m -d 'Remove the bitcode from the __LLVM segment, leaving behind a marker'
complete -c bitcode_strip -s l -d 'Remove all of the native executable code, leaving the LLVM bitcode behind'
complete -c bitcode_strip -s v -d 'Print the arguments passed to other tools run by  bitcode_strip when processi…'
complete -c bitcode_strip -o keep_cs -d 'Preserve the codesign load commands in the output binary, even though the cod…'
complete -c bitcode_strip -s o -d 'specifies the output file as  output'
complete -c bitcode_strip -o preserve-metadata -d 'to resign the binary'

