# bootpd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/bootpd.8
complete -c bootpd -s B -d 'Disable BOOTP service'
complete -c bootpd -s b -d 'Only respond if the client\'s bootfile exists: for BOOTP clients only'
complete -c bootpd -s D -d 'Enable DHCP service.   By default, DHCP service is disabled'
complete -c bootpd -s d -d 'Remain in the foreground and produce extra debugging output to stderr'
complete -c bootpd -s I -d 'Disable re-initialization on IP address changes'
complete -c bootpd -s i -d 'Enable service on the specified interface'
complete -c bootpd -s m -d 'Enable NetBoot 1. 0 (BOOTP-based) service'
complete -c bootpd -s N -d 'Enable NetBoot 2. 0 (BSDP/DHCP-based) service'
complete -c bootpd -s o -d 'For relay agent operation, the maximum hop count, default is 4 hops'
complete -c bootpd -s q -d 'Be quiet as possible.   Only report serious errors to'
complete -c bootpd -s r -d 'Relay packets to the specified server_ip, not exceeding the hop count'
complete -c bootpd -s S -d 'Enable BOOTP service'
complete -c bootpd -s v -d 'Be more verbose in messages logged to \\fI/var/log/system. log\\fR'

