# bputil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/bputil.1
complete -c bputil -s u -d 'Pp Used to specify the username for a user with access to the signing key to …'
complete -c bputil -s p -d 'Pp Used to specify the password for a user with access to the signing key to …'
complete -c bputil -s v -d 'Pp Specify the APFS Volume Group UUID of the OS intended to have its policy c…'
complete -c bputil -s l -d 'Pp Enables verbose logging to assist in debugging any issues associated with …'
complete -c bputil -s d -d 'Pp Display the detailed contents of the LocalPolicy'
complete -c bputil -s e -d 'Pp Display the detailed contents of the LocalPolicy for every bootable OS ins…'
complete -c bputil -s f -d 'Pp Changes security mode to Full Security'
complete -c bputil -s g -d 'Pp Selecting this option will make your system easier to compromise! Pp This …'
complete -c bputil -s n -d 'Pp Selecting this option will make your system easier to compromise! Pp This …'
complete -c bputil -s k -d 'Pp Because this option automatically downgrades to Reduced Security mode if n…'
complete -c bputil -s c -d 'Pp Because this option automatically downgrades to Permissive Security mode i…'
complete -c bputil -s a -d 'Pp Because this option automatically downgrades to Permissive Security mode i…'
complete -c bputil -s s -d 'Pp Because this option automatically downgrades to Permissive Security mode i…'
complete -c bputil -s m -d 'Pp Because this option automatically downgrades to Reduced Security mode if n…'

