# bundle-lock
# Autogenerated from man page /usr/share/man/man1/bundle-lock.1
complete -c bundle-lock -l conservative -d 'If updating, use bundle install conservative update behavior and do not allow…'

