# bundle-outdated
# Autogenerated from man page /usr/share/man/man1/bundle-outdated.1
complete -c bundle-outdated -l only-explicit -d 'Only list gems specified in your Gemfile, not their dependencies'

