# bundle-binstubs
# Autogenerated from man page /usr/share/man/man1/bundle-binstubs.1
complete -c bundle-binstubs -l shebang -d 'Specify a different shebang executable name than the default (default \'ruby\')'

