# bundle-platform
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/bundle-platform.1
complete -c bundle-platform -l ruby -d 'It will display the ruby directive information, so you don\'t have to parse it…'

