# bundle-info
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/bundle-info.1
complete -c bundle-info -l path -d 'Print the path of the given gem'

