# bundle-init
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/bundle-init.1
complete -c bundle-init -l gemspec -d 'Use the specified . gemspec to create the [Gemfile(5)][Gemfile(5)]'

