# bundle-exec
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/bundle-exec.1
complete -c bundle-exec -l keep-file-descriptors -d 'Exec in Ruby 2. 0 began discarding non-standard file descriptors'

