# c89
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/c89.1
complete -c c89 -s c -d 'Suppress the link-edit phase of the compilation, and do not remove any object…'
complete -c c89 -s D -d 'Define name as if by a C-language #define directive'
complete -c c89 -s E -d 'Copy C-language source files to the standard output, expanding all preprocess…'
complete -c c89 -s g -d 'Produce symbolic information in the object or executable files'
complete -c c89 -s I -d 'Change the algorithm for searching for headers whose names are not absolute p…'
complete -c c89 -s L -d 'Change the algorithm of searching for the libraries named in the l objects to…'
complete -c c89 -s o -d 'Use the pathname outfile, instead of the default a'
complete -c c89 -s O -d 'If optlevel is zero, disable all optimizations'
complete -c c89 -s s -d 'Produce object and/or executable files from which symbolic and other informat…'
complete -c c89 -s U -d 'Remove any initial definition of name'
complete -c c89 -s W -d 'Set the pointer size for the compiled code to either 32 or 64 bits'
complete -c c89 -s l -d 'Search the library named lib Ns Ar library Ns Pa . a'

