# caffeinate
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/caffeinate.8
complete -c caffeinate -s d -d 'Create an assertion to prevent the display from sleeping'
complete -c caffeinate -s i -d 'Create an assertion to prevent the system from idle sleeping'
complete -c caffeinate -s m -d 'Create an assertion to prevent the disk from idle sleeping'
complete -c caffeinate -s s -d 'Create an assertion to prevent the system from sleeping'
complete -c caffeinate -s u -d 'Create an assertion to declare that user is active'
complete -c caffeinate -s t -d 'Specifies the timeout value in seconds for which this assertion has to be val…'
complete -c caffeinate -s w -d 'Waits for the process with the specified pid to exit'

