# cap_mkdb
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/cap_mkdb.1
complete -c cap_mkdb -s f -d 'Specify a different database basename'
complete -c cap_mkdb -s v -d 'Print out the number of capability records in the database'

