# cfilutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/cfilutil.1
complete -c cfilutil -s a -d 'Auto start filtering with given offset'
complete -c cfilutil -s h -d 'Display this help'
complete -c cfilutil -s i -d 'Interactive mode'
complete -c cfilutil -s k -d 'Peek mode with increment'
complete -c cfilutil -s l -d 'Pass loopback traffic'
complete -c cfilutil -s m -d 'Maximum dump length'
complete -c cfilutil -s p -d 'Pass mode (all or after given offset if it is > 0)'
complete -c cfilutil -s q -d 'Decrease verbosity'
complete -c cfilutil -s r -d 'Random drop rate'
complete -c cfilutil -s s -d 'display content filter statistics (all, sock, filt, cfil)'
complete -c cfilutil -s t -d 'Pass delay in microseconds'
complete -c cfilutil -s u -d 'NECP filter control unit'
complete -c cfilutil -s v -d 'Increase verbosity.  El Pp SEE ALSO neutil 1              \\" rdar://16115914'

