# chat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/chat.8
complete -c chat -s f -d 'Read the chat script from the chat file'
complete -c chat -s t -d 'Set the timeout for the expected string to be received'
complete -c chat -s r -d 'Set the file for output of the report strings'
complete -c chat -s e -d 'Start with the echo option turned on'
complete -c chat -s E -d 'Enables environment variable substituion within chat scripts using the standa…'
complete -c chat -s v -d 'Request that the chat script be executed in a verbose mode'
complete -c chat -s V -d 'Request that the chat script be executed in a stderr verbose mode'
complete -c chat -s s -d 'Use stderr'
complete -c chat -s S -d 'Do not use the SYSLOG.   By default, error messages are sent to the SYSLOG'
complete -c chat -s T -d 'Pass in an arbitary string, usually a phone number, that will be substituted …'
complete -c chat -s U -d 'Pass in a second string, usually a phone number, that will be substituted for…'

