# checknr
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/checknr.1
complete -c checknr -s a -d 'Add additional pairs of macros to the list of known macros'
complete -c checknr -s c -d 'Define commands which would otherwise be complained about as undefined'
complete -c checknr -s f -d 'Request checknr to ignore \\ef font changes'
complete -c checknr -s s -d 'Ignore \\es size changes'

