# chkpasswd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/chkpasswd.8
complete -c chkpasswd -s c -d 'The supplied password is compared verbatim without first being encrypted'
complete -c chkpasswd -s i -d 'Specify the system against which to check the password (default is PAM)'
complete -c chkpasswd -s l -d 'Specify a location; varies based on infosystem type: -tag -width "for opendir…'

