# chmod
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/chmod.1
complete -c chmod -s f -d 'Do not display a diagnostic message if chmod could not modify the mode for fi…'
complete -c chmod -s H -d 'If the R option is specified, symbolic links on the command line are followed…'
complete -c chmod -s h -d 'If the file is a symbolic link, change the mode of the link itself rather tha…'
complete -c chmod -s L -d 'If the R option is specified, all symbolic links are followed'
complete -c chmod -s P -d 'If the R option is specified, no symbolic links are followed'
complete -c chmod -s R -d 'Change the modes of the file hierarchies rooted in the files, instead of just…'
complete -c chmod -s v -d 'Cause chmod to be verbose, showing filenames as the mode is modified'
complete -c chmod -s a -d 'The -a mode is used to delete ACL entries'
complete -c chmod -s E -d 'Reads the ACL information from stdin, as a sequential list of ACEs, separated…'
complete -c chmod -s C -d 'Returns false if any of the named files have ACLs in non-canonical order'
complete -c chmod -s i -d 'Removes the \'inherited\' bit from all entries in the named file(s) ACLs'
complete -c chmod -s I -d 'Removes all inherited entries from the named file(s) ACL(s)'
complete -c chmod -s N -d 'Removes the ACL from the named file(s)'

