# chown
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/chown.8
complete -c chown -s H -d 'If the R option is specified, symbolic links on the command line are followed…'
complete -c chown -s L -d 'If the R option is specified, all symbolic links are followed'
complete -c chown -s P -d 'If the R option is specified, no symbolic links are followed'
complete -c chown -s R -d 'Change the user ID and/or the group ID of the file hierarchies rooted in the …'
complete -c chown -s f -d 'Do not report any failure to change file owner or group, nor modify the exit …'
complete -c chown -s h -d 'If the file is a symbolic link, change the user ID and/or the group ID of the…'
complete -c chown -s n -d 'Interpret user ID and group ID as numeric, avoiding name lookups'
complete -c chown -s v -d 'Cause chown to be verbose, showing files as the owner is modified'
complete -c chown -s x -d 'File system mount points are not traversed'

