# chpass
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/chpass.1
complete -c chpass -s l -d 'If not specified, chpass will perform a search for the user record on all ava…'
complete -c chpass -s u -d 'The user name to use when authenticating to the directory node containing the…'
complete -c chpass -s s -d 'Attempt to change the user\'s shell to newshell'

