# chroot
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/chroot.8
complete -c chroot -s G -d 'Run the command with the permissions of the specified groups'
complete -c chroot -s g -d 'Run the command with the permissions of the specified group'
complete -c chroot -s u -d 'Run the command as the user'

