# cksum
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/cksum.1
complete -c cksum -s o -d 'Use historic algorithms instead of the (superior) default one'

