# classkit-tool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/classkit-tool.8
complete -c classkit-tool -s h -d 'Show this message and exit'
complete -c classkit-tool -s s -d 'Return the current development mode'
complete -c classkit-tool -s d -d 'Set the development mode to off, teacher, or student'
complete -c classkit-tool -s r -d 'Reset the development mode data'

