# cmp
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/cmp.1
complete -c cmp -s b -l print-bytes -d 'Print differing bytes'
complete -c cmp -s i -l ignore-initial -d 'Skip the first SKIP bytes of input'
complete -c cmp -s l -l verbose -d 'Output byte numbers and values of all differing bytes'
complete -c cmp -s n -l bytes -d 'Compare at most LIMIT bytes'
complete -c cmp -s s -l quiet -l silent -d 'Output nothing; yield exit status only'
complete -c cmp -s v -l version -d 'Output version info'
complete -c cmp -l help -d 'Output this help'

