# col
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/col.1
complete -c col -s b -d 'Do not output any backspaces, printing only the last character written to eac…'
complete -c col -s f -d 'Forward half line feeds are permitted (``fine\'\' mode)'
complete -c col -s h -d 'Do not output multiple spaces instead of tabs (default)'
complete -c col -s l -d 'Buffer at least num lines in memory.  By default, 128 lines are buffered'
complete -c col -s p -d 'Force unknown control sequences to be passed through unchanged'
complete -c col -s x -d 'Output multiple spaces instead of tabs'

