# colcrt
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/colcrt.1
complete -c colcrt -s 2 -d 'Cause all half-lines to be printed, effectively double spacing the output'

