# comm
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/comm.1
complete -c comm -s 1 -d 'Suppress printing of column 1, lines only in file1'
complete -c comm -s 2 -d 'Suppress printing of column 2, lines only in file2'
complete -c comm -s 3 -d 'Suppress printing of column 3, lines common to both'
complete -c comm -s i -d 'Case insensitive comparison of lines'

