# compress
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/compress.1
complete -c compress -s b -d 'The code size (see below) is limited to bits, which must be in the range 9'
complete -c compress -s c -d 'Compressed or uncompressed output is written to the standard output'
complete -c compress -s f -d 'Files are overwritten without prompting for confirmation'
complete -c compress -s v -d 'Print the percentage reduction of each file'

