# compression_tool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/compression_tool.1
complete -c compression_tool -o encode -d 'Encode (compress) the input'
complete -c compression_tool -o decode -d 'Decode (uncompress) the input'
complete -c compression_tool -o aalgorithm -d 'Set the compression algorithm, valid options are zlib, lzma, lzfse, lz4, lz4_…'
complete -c compression_tool -o Aalgorithm -d 'Enable block compression, and set compression algorithm, valid options are zl…'
complete -c compression_tool -o bblock_size -d 'Set block size for block compression'
complete -c compression_tool -o tthread_count -d 'Set the number of worker threads to use for block compression/decompression'
complete -c compression_tool -o iinput_file -d 'Input file.  If omitted, read from standard input'
complete -c compression_tool -o ooutput_file -d 'Output file.  If omitted, write to standard output'
complete -c compression_tool -s v -d 'Increase verbosity.  Default is silent operation'
complete -c compression_tool -s a -d 'Set the compression algorithm, valid options are zlib, lzma, lzfse, lz4, lz4_…'
complete -c compression_tool -s A -d 'Enable block compression, and set compression algorithm, valid options are zl…'
complete -c compression_tool -s b -d 'Set block size for block compression'
complete -c compression_tool -s t -d 'Set the number of worker threads to use for block compression/decompression'
complete -c compression_tool -s i -d 'Input file.  If omitted, read from standard input'
complete -c compression_tool -s o -d 'Output file.  If omitted, write to standard output'
complete -c compression_tool -s h -d 'Print usage and exit'

