# configd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/configd.8
complete -c configd -s b -d 'Don\'t actually load any bundles'
complete -c configd -s B -d 'Prevents the loading of the bundle with the specified bundleID'
complete -c configd -s d -d 'Run configd in the foreground without forking.   This is useful for debugging'
complete -c configd -s v -d 'Puts configd into verbose mode'
complete -c configd -s V -d 'Turns verbose mode on for the bundle with the specified bundleID'
complete -c configd -s t -d 'Loads only the bundle specified by bundle-path'

