# containermanagerd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/containermanagerd.8
complete -c containermanagerd -l runmode -d 'Defines the running mode of the daemon where runmode is one of the following:…'
complete -c containermanagerd -l default-user -d 'Sets the default user where user data will be stored'
complete -c containermanagerd -l bundle-container-mode -d 'Controls how bundle containers are managed where mode is one of the following…'
complete -c containermanagerd -l bundle-container-owner -d 'Sets the username that bundle containers will be chown 2 to'
complete -c containermanagerd -l system-container-mode -d 'Controls how system containers are managed where mode is one of the following…'
complete -c containermanagerd -l system-container-owner -d 'Sets the username that system containers will be chown 2 to'

