# corelist5
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/corelist5.30.1
complete -c corelist5 -l utils -d 'lists the first version of perl each named utility program was released with '

