# createhomedir
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/createhomedir.1
complete -c createhomedir -s s -d 'creates home directories for server home paths only (default)'
complete -c createhomedir -s c -d 'creates home directories for local home paths only'
complete -c createhomedir -s b -d 'creates home directories for both server and local home paths'
complete -c createhomedir -s a -d 'creates home directories for users defined in all directory domains of the se…'
complete -c createhomedir -s l -d 'creates home directories for users defined in the local directory domain'
complete -c createhomedir -s L -d 'causes the created home directory to be localized'
complete -c createhomedir -s n -d 'creates home directories for users defined in a specific directory domain in …'
complete -c createhomedir -s u -d 'creates a home directory for a specific user defined in the domain(s) identif…'
complete -c createhomedir -s i -d 'reads username list from standard input and creates specified home directories'
complete -c createhomedir -s h -d 'usage help'

