# cron
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/cron.8
complete -c cron -s s -d 'Enable special handling of situations when the GMT offset of the local timezo…'
complete -c cron -s o -d 'Disable the special handling of situations when the GMT offset of the local t…'
complete -c cron -s x -d 'Enable writing of debugging information to standard output'

