# csnameddata
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/csnameddata.8
complete -c csnameddata -s f -d 'when displaying an item, don\'t truncate the data display'
complete -c csnameddata -o full -d 'when displaying an item, don\'t truncate the data display'
complete -c csnameddata -s v -d 'display more verbose status'
complete -c csnameddata -l verbose -d 'display more verbose status El COMMANDS Each command and any arguments are ha…'

