# csplit
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/csplit.1
complete -c csplit -s f -d 'Create file names beginning with prefix, instead of xx'
complete -c csplit -s k -d 'Do not remove previously created files if an error occurs or a HUP, INT, or T…'
complete -c csplit -s n -d 'Create file names beginning with number of decimal digits after the prefix, i…'
complete -c csplit -s s -d 'Do not write the size of each output file to standard output as it is created'

