# csreq
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/csreq.1
complete -c csreq -s b -d 'Requests that the requirement read be written in binary form to the path given'
complete -c csreq -s r -d 'Specifies the input requirement.  See "specifying requirements" below'
complete -c csreq -s t -d 'Requests that the requirement read be written as text to standard output'
complete -c csreq -s v -d 'Increases the verbosity of output'

