# csunique
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/csunique.8
complete -c csunique -s v -d 'Output verbose progress information of each step and the UUID re-mappings'
complete -c csunique -s n -d 'Operates in "dry run" mode; no changes are made to the on-disk data'
complete -c csunique -s I -d 'Specifies an additional class of UUID objects that should be modified'
complete -c csunique -s X -d 'Specifies a class of UUID objects that should not be modified'

