# ctags
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/ctags.1
complete -c ctags -s a -d 'append to tags file'
complete -c ctags -s B -d 'use backward searching patterns ?. ?'
complete -c ctags -s d -d 'create tags for #defines that don\'t take arguments; #defines that take argume…'
complete -c ctags -s F -d 'use forward searching patterns /. / (the default)'
complete -c ctags -s f -d 'Places the tag descriptions in a file called tags_file'
complete -c ctags -s t -d 'create tags for typedefs, structs, unions, and enums'
complete -c ctags -s u -d 'update the specified files in the tags file, that is, all references to them …'
complete -c ctags -s v -d 'An index of the form expected by vgrind 1 is produced on the standard output'
complete -c ctags -s w -d 'suppress warning diagnostics'
complete -c ctags -s x -d 'ctags produces a list of object names, the line number and file name on which…'

