# cupsaccept
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/cupsaccept.8
complete -c cupsaccept -s E -d 'Forces encryption when connecting to the server'
complete -c cupsaccept -s U -d 'Sets the username that is sent when connecting to the server'
complete -c cupsaccept -s h -d 'Chooses an alternate server'
complete -c cupsaccept -s r -d 'Sets the reason string that is shown for a printer that is rejecting jobs'

