# cupsreject
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/cupsreject.8
complete -c cupsreject -s E -d 'Forces encryption when connecting to the server'
complete -c cupsreject -s U -d 'Sets the username that is sent when connecting to the server'
complete -c cupsreject -s h -d 'Chooses an alternate server'
complete -c cupsreject -s r -d 'Sets the reason string that is shown for a printer that is rejecting jobs'

