# cups-lpd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/cups-lpd.8
complete -c cups-lpd -s h -d 'Sets the CUPS server (and port) to use'
complete -c cups-lpd -s n -d 'Disables reverse address lookups; normally  cups-lpd will try to discover the…'
complete -c cups-lpd -s o -d 'Inserts options for all print queues'

