# date
# Autogenerated from man page /usr/share/man/man1/date.1
complete -c date -s d -d 'Set the kernel\'s value for daylight saving time'
complete -c date -s t -d 'Set the system\'s value for minutes west of GMT'

