# db_archive
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/db_archive.1
complete -c db_archive -s a -d 'Write all pathnames as absolute pathnames, instead of relative to the databas…'
complete -c db_archive -s d -d 'Remove log files that are no longer needed; no filenames are written'
complete -c db_archive -s h -d 'Specify a home directory for the database environment; by default, the curren…'
complete -c db_archive -s l -d 'Write out the pathnames of all the database log files, whether or not they ar…'
complete -c db_archive -s P -d 'Specify an environment password'
complete -c db_archive -s s -d 'Write the pathnames of all the database files that need to be archived in ord…'
complete -c db_archive -s V -d 'Write the library version number to the standard output, and exit'
complete -c db_archive -s v -d 'Run in verbose mode, listing the checkpoints in the log files as they are rev…'

