# db_checkpoint
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/db_checkpoint.1
complete -c db_checkpoint -s 1 -d 'Checkpoint the log once, regardless of whether or not there has been activity…'
complete -c db_checkpoint -s h -d 'Specify a home directory for the database environment; by default, the curren…'
complete -c db_checkpoint -s k -d 'Checkpoint the database at least as often as every kbytes of log file are wri…'
complete -c db_checkpoint -s L -d 'Log the execution of the db_checkpoint utility to the specified file in the f…'
complete -c db_checkpoint -s P -d 'Specify an environment password'
complete -c db_checkpoint -s p -d 'Checkpoint the database at least every min minutes if there has been any acti…'
complete -c db_checkpoint -s V -d 'Write the library version number to the standard output, and exit'
complete -c db_checkpoint -s v -d 'Write the time of each checkpoint attempt to the standard output'

