# db_dump
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/db_dump.1
complete -c db_dump -s d -d 'Dump the specified database in a format helpful for debugging the Berkeley DB…'
complete -c db_dump -s f -d 'Write to the specified file instead of to the standard output'
complete -c db_dump -s h -d 'Specify a home directory for the database environment; by default, the curren…'
complete -c db_dump -s k -d 'Dump record numbers from Queue and Recno databases as keys'
complete -c db_dump -s l -d 'List the databases stored in the file'
complete -c db_dump -s N -d 'Do not acquire shared region mutexes while running'
complete -c db_dump -s P -d 'Specify an environment password'
complete -c db_dump -s p -d 'If characters in either the key or data items are printing characters (as def…'
complete -c db_dump -s R -d 'Aggressively salvage data from a possibly corrupt file'
complete -c db_dump -s r -d 'Salvage data from a possibly corrupt file'
complete -c db_dump -s s -d 'Specify a single database to dump'
complete -c db_dump -s V -d 'Write the library version number to the standard output, and exit'

