# db_deadlock
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/db_deadlock.1
complete -c db_deadlock -s a -d 'When a deadlock is detected, abort the locker: -tag -width m with the greates…'
complete -c db_deadlock -s h -d 'Specify a home directory for the database environment; by default, the curren…'
complete -c db_deadlock -s L -d 'Log the execution of the db_deadlock utility to the specified file in the fol…'
complete -c db_deadlock -s t -d 'Check the database environment every sec seconds plus usec microseconds to se…'
complete -c db_deadlock -s V -d 'Write the library version number to the standard output, and exit'
complete -c db_deadlock -s v -d 'Run in verbose mode, generating messages each time the detector runs'

