# db_load
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/db_load.1
complete -c db_load -s c -d 'Specify configuration options ignoring any value they may have based on the i…'
complete -c db_load -s f -d 'Read from the specified input file instead of from the standard input'
complete -c db_load -s h -d 'Specify a home directory for the database environment'
complete -c db_load -s n -d 'Do not overwrite existing keys in the database when loading into an already e…'
complete -c db_load -s P -d 'Specify an environment password'
complete -c db_load -s T -d 'The -T option allows non-Berkeley DB applications to easily load text files i…'
complete -c db_load -s t -d 'Specify the underlying access method'
complete -c db_load -s V -d 'Write the library version number to the standard output, and exit'

