# db_printlog
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/db_printlog.1
complete -c db_printlog -s h -d 'Specify a home directory for the database environment; by default, the curren…'
complete -c db_printlog -s N -d 'Do not acquire shared region mutexes while running'
complete -c db_printlog -s P -d 'Specify an environment password'
complete -c db_printlog -s r -d 'Read the log files in reverse order'
complete -c db_printlog -s V -d 'Write the library version number to the standard output, and exit'

