# db_recover
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/db_recover.1
complete -c db_recover -s c -d 'Perform catastrophic recovery instead of normal recovery'
complete -c db_recover -s e -d 'Retain the environment after running recovery'
complete -c db_recover -s h -d 'Specify a home directory for the database environment; by default, the curren…'
complete -c db_recover -s P -d 'Specify an environment password'
complete -c db_recover -s t -d 'Recover to the time specified rather than to the most current possible date'
complete -c db_recover -s V -d 'Write the library version number to the standard output, and exit'
complete -c db_recover -s v -d 'Run in verbose mode'

