# db_stat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/db_stat.1
complete -c db_stat -s C -d 'Display internal information about the lock region'
complete -c db_stat -s c -d 'Display lock region statistics, as described in DB_ENV->lock_stat'
complete -c db_stat -s d -d 'Display database statistics for the specified file, as described in DB->stat'
complete -c db_stat -s e -d 'Display current environment statistics'
complete -c db_stat -s f -d 'Display only those database statistics that can be acquired without traversin…'
complete -c db_stat -s h -d 'Specify a home directory for the database environment; by default, the curren…'
complete -c db_stat -s l -d 'Display log region statistics, as described in DB_ENV->log_stat'
complete -c db_stat -s M -d 'Display internal information about the shared memory buffer pool'
complete -c db_stat -s m -d 'Display shared memory buffer pool statistics, as described in DB_ENV->memp_st…'
complete -c db_stat -s N -d 'Do not acquire shared region mutexes while running'
complete -c db_stat -s P -d 'Specify an environment password'
complete -c db_stat -s r -d 'Display replication statistics, as described in DB_ENV->rep_stat'
complete -c db_stat -s s -d 'Display statistics for the specified database contained in the file specified…'
complete -c db_stat -s t -d 'Display transaction region statistics, as described in DB_ENV->txn_stat'
complete -c db_stat -s V -d 'Write the library version number to the standard output, and exit'
complete -c db_stat -s Z -d 'Reset the statistics after reporting them; valid only with the -c, -e, -l, -m…'

