# db_upgrade
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/db_upgrade.1
complete -c db_upgrade -s h -d 'Specify a home directory for the database environment; by default, the curren…'
complete -c db_upgrade -s N -d 'Do not acquire shared region mutexes while running'
complete -c db_upgrade -s P -d 'Specify an environment password'
complete -c db_upgrade -s s -d 'This flag is only meaningful when upgrading databases from releases before th…'
complete -c db_upgrade -s V -d 'Write the library version number to the standard output, and exit'

