# db_verify
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/db_verify.1
complete -c db_verify -s h -d 'Specify a home directory for the database environment; by default, the curren…'
complete -c db_verify -s o -d 'Skip the database checks for btree and duplicate sort order and for hashing'
complete -c db_verify -s N -d 'Do not acquire shared region mutexes while running'
complete -c db_verify -s P -d 'Specify an environment password'
complete -c db_verify -s q -d 'Suppress the printing of any error descriptions, simply exit success or failu…'
complete -c db_verify -s V -d 'Write the library version number to the standard output, and exit'

