# dbiprof
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/dbiprof.1
complete -c dbiprof -l number -d 'Produce this many items in the report.   Defaults to 10'
complete -c dbiprof -l sort -d 'Sort results by the given field'
complete -c dbiprof -l reverse -d 'Reverses the selected sort'
complete -c dbiprof -l match -d 'Consider only items where the specified key matches the given value'
complete -c dbiprof -l exclude -d 'Remove items for where the specified key matches the given value'
complete -c dbiprof -l case-sensitive -d 'Using this option causes --match and --exclude to work case-sensitively'
complete -c dbiprof -l delete -d 'Sets the \\f(CW\\*(C`DeleteFiles\\*(C\' option to DBI::ProfileData which causes t…'
complete -c dbiprof -l dumpnodes -d 'Print the list of nodes in the form of a perl data structure'

