# defaults
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/defaults.1
complete -c defaults -o app -d 'The name of an application may be provided instead of a domain using the \\fB-…'
complete -c defaults -s g -d 'Specify the global domain'
complete -c defaults -o string -d 'Allows the user to specify a string as the value for the given preference key'
complete -c defaults -o data -d 'Allows the user to specify a bunch of raw data bytes as the value for the giv…'
complete -c defaults -o int -d 'Allows the user to specify an integer as the value for the given preference k…'
complete -c defaults -o float -d 'Allows the user to specify a floating point number as the value for the given…'
complete -c defaults -o bool -d 'Allows the user to specify a boolean as the value for the given preference key'
complete -c defaults -o date -d 'Allows the user to specify a date as the value for the given preference key'
complete -c defaults -o array -d 'Allows the user to specify an array as the value for the given preference key…'
complete -c defaults -o array-add -d 'Allows the user to add new elements to the end of an array for a key which ha…'
complete -c defaults -o dict -d 'Allows the user to add a dictionary to the defaults database for a domain'
complete -c defaults -o dict-add -d 'Allows the user to add new key/value pairs to a dictionary for a key which ha…'
complete -c defaults -o currentHost -d 'Restricts preferences operations to the host the user is currently logged in …'
complete -c defaults -o host -d 'Restricts preferences operations to \\fIhostname\\fR'

