# delv
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/delv.1
complete -c delv -s a -d 'Specifies a file from which to read DNSSEC trust anchors'
complete -c delv -s b -d 'Sets the source IP address of the query to address'
complete -c delv -s c -d 'Sets the query class for the requested data'
complete -c delv -s d -d 'Set the systemwide debug level to level.  The allowed range is from 0 to 99'
complete -c delv -s h -d 'Display the delv help usage output and exit'
complete -c delv -s i -d 'Insecure mode.  This disables internal DNSSEC validation'
complete -c delv -s m -d 'Enables memory usage debugging'
complete -c delv -s p -d 'Specifies a destination port to use for queries instead of the standard DNS p…'
complete -c delv -s q -d 'Sets the query name to name'
complete -c delv -s t -d 'Sets the query type to type, which can be any valid query type supported in B…'
complete -c delv -s v -d 'Print the delv version and exit'
complete -c delv -s x -d 'Performs a reverse lookup, mapping an addresses to a name'
complete -c delv -s 4 -d 'Forces delv to only use IPv4'
complete -c delv -s 6 -d 'Forces delv to only use IPv6'

