# demandoc
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/demandoc.1
complete -c demandoc -s w -d 'Output a word list.  This outputs each word of text on its own line'

