# derq
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/derq.1
complete -c derq -l pretty -d 'When specified, derq will print the active context in a textual representatio…'
complete -c derq -l raw -d 'Signifies that the input might not be a DER encoded entitlements blob'
complete -c derq -l xml -d 'Instruct the macho or csops subcommands to query the embedded XML blob instea…'
complete -c derq -s i -d 'Allows you to specify which file should be used as the input'
complete -c derq -s o -d 'Allows you to specify which file should be used as the output'
complete -c derq -s p -d 'Specifies the pid of a running process from which derq should extract the DER…'
complete -c derq -s f -d 'Specifies what format the input is'

