# df
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/df.1
complete -c df -s a -d 'Show all mount points, including those that were mounted with the MNT_IGNORE …'
complete -c df -s b -d 'Use (the default) 512-byte blocks'
complete -c df -s g -d 'Use 1073741824-byte (1-Gbyte) blocks rather than the default'
complete -c df -s H -d '"Human-readable" output'
complete -c df -s h -d '"Human-readable" output'
complete -c df -s i -d 'Include statistics on the number of free inodes'
complete -c df -s k -d 'Use 1024-byte (1-Kbyte) blocks, rather than the default'
complete -c df -s l -d 'Only display information about locally-mounted filesystems'
complete -c df -s m -d 'Use 1048576-byte (1-Mbyte) blocks rather than the default'
complete -c df -s n -d 'Print out the previously obtained statistics from the filesystems'
complete -c df -s P -d 'Use (the default) 512-byte blocks'
complete -c df -s T -d 'Only print out statistics for filesystems of the specified types'
complete -c df -s t -d 'If used with no arguments, this option is a no-op (Mac OS X already prints th…'

