# diskarbitrationd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/diskarbitrationd.8
complete -c diskarbitrationd -s d -d 'Report detailed information in /var/log/diskarbitrationd. log'

