# dnctl
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/dnctl.8
complete -c dnctl -s a -d 'While listing, show counter values'
complete -c dnctl -s f -d 'Don\'t ask for confirmation for commands that can cause problems if misused, i'
complete -c dnctl -s h -d 'Displays a short help'
complete -c dnctl -s n -d 'Only check syntax of the command strings, without actually passing them to th…'
complete -c dnctl -s q -d 'While add Ns ing, zero Ns ing, resetlog Ns ging or flush Ns ing, be quiet abo…'
complete -c dnctl -s s -d 'While listing pipes, sort according to one of the four counters (total or cur…'
complete -c dnctl -s v -d 'Be verbose'

