# dot_clean
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/dot_clean.1
complete -c dot_clean -s f -d 'Tp Flat merge.   Do not recursively merge all directories in the given dir'
complete -c dot_clean -s h -d 'Help.  Prints verbose usage message'
complete -c dot_clean -s m -d 'Always delete dot underbar files'
complete -c dot_clean -s n -d 'Delete dot underbar file if there is no matching native file'
complete -c dot_clean -s s -d 'Follow symbolic links'
complete -c dot_clean -s v -d 'Print verbose output'
complete -c dot_clean -l keep -d 'The default option'

