# dscacheutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/dscacheutil.1
complete -c dscacheutil -s h -d 'Lists the options for calling dscacheutil'
complete -c dscacheutil -s q -d 'Initiate a query using standard calls'
complete -c dscacheutil -s a -d 'Optional flag to q for a specific key with a value'
complete -c dscacheutil -o cachedump -d 'Dumps an overview of the cache by default'
complete -c dscacheutil -o buckets -d 'Used in conjunction with cachedump to also print hash bucket usage of the cur…'
complete -c dscacheutil -o entries -d 'Used in conjunction with cachedump to dump detailed information about cache e…'
complete -c dscacheutil -o configuration -d 'Prints current configuration information, such as the search policy from Dire…'
complete -c dscacheutil -o flushcache -d 'Flushes the entire cache.   This should only be used in extreme cases'
complete -c dscacheutil -o statistics -d 'Prints statistics from the cache including an overview and detailed call stat…'

