# dsenableroot
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/dsenableroot.8
complete -c dsenableroot -s u -d 'Username of a user that has administrative privileges on this computer'
complete -c dsenableroot -s p -d 'Password to use in conjunction with the specified username'
complete -c dsenableroot -s r -d 'Password to be used for the root account'

