# dsexport
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/dsexport.1
complete -c dsexport -l N -d 'Export all attributes, including native attributes'
complete -c dsexport -s r -d 'Comma-separated list of records to export from the specified node'
complete -c dsexport -s e -d 'Comma-separated list of attributes that should not be exported'
complete -c dsexport -s a -d 'Address of the desired proxy machine'
complete -c dsexport -s u -d 'Username to use for the proxy connection'
complete -c dsexport -s p -d 'Password to use for the proxy connection'

