# dsimport
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/dsimport.1
complete -c dsimport -l crypt -d 'is used to signify that all user passwords are crypt-based'
complete -c dsimport -l force -d 'forces a specific value for the named attribute for all records during the im…'
complete -c dsimport -l groupid -d 'is the GID used for any records that do not specify a primary GID'
complete -c dsimport -l grouppreset -d 'designate a preset record to be applied to imported group records'
complete -c dsimport -l loglevel -d 'changes the amount of logging detail output to the log file'
complete -c dsimport -l outputfile -d 'Outputs a plist to the specified file with a list of changed users or groups …'
complete -c dsimport -l password -d 'is the admin\'s password for import operations'
complete -c dsimport -l recordformat -d 'passes in the delimiters and attributes and record type to specify the order …'
complete -c dsimport -l recordtype -d 'Override the record type defined in the import file'
complete -c dsimport -l remotehost -d 'connects to a remote host at the network address specified'
complete -c dsimport -l remoteusername -d 'specifies user name to use for the remote connection'
complete -c dsimport -l remotepassword -d 'specifies password to use for the remote connection'
complete -c dsimport -l startid -d 'indicates the ID number to start with when the import tool generates user or …'
complete -c dsimport -l template -d 'is used for delimited import of files that lack field descriptions'
complete -c dsimport -l username -d 'is the admin username to use when importing records'
complete -c dsimport -l userpreset -d 'designate a preset record to be applied to imported user records'

