# dsmemberutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/dsmemberutil.1
complete -c dsmemberutil -s h -d 'Lists the options for calling dsmemberutil'
complete -c dsmemberutil -s v -d 'Causes dsmemberutil to operate in verbose mode'
complete -c dsmemberutil -s u -d 'Using user with UID'
complete -c dsmemberutil -s U -d 'Using user with name'
complete -c dsmemberutil -s s -d 'Using user with SID'
complete -c dsmemberutil -s x -d 'Using user with UUID'
complete -c dsmemberutil -s g -d 'Using group with GID'
complete -c dsmemberutil -s G -d 'Using group with name'
complete -c dsmemberutil -s S -d 'Using group with SID'
complete -c dsmemberutil -s X -d 'Using group with UUID El EXAMPLES Pp -tag -width -indent  \\" Differs from abo…'

