# dyld_info
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/dyld_info.1
complete -c dyld_info -o arch -d 'Only display the specified architecture'
complete -c dyld_info -o platform -d 'Display the platform (e. g.  macOS, iOS) that the binary was built for'
complete -c dyld_info -o segments -d 'Display all segments and sections with size info'
complete -c dyld_info -o dependents -d 'Display all dylibs that the binary is linked against'
complete -c dyld_info -o inits -d 'Display all static initializers and Objective-C +load methods'
complete -c dyld_info -o exports -d 'Display all exported symbols'
complete -c dyld_info -o imports -d 'Display all imported symbols'
complete -c dyld_info -o objc -d 'Display the Objective-C classes and categories defined'
complete -c dyld_info -o fixups -d 'Display a simple table of fixup locations and what dyld will set them to'
complete -c dyld_info -o fixup_chains -d 'If the binary uses chained fixups, displays the format of the chains and the …'
complete -c dyld_info -o fixup_chain_details -d 'Display a table of all the raw fixup chain bits and their meanings'
complete -c dyld_info -o symbolic_fixups -d 'Display all fixups, grouped by data symbol'
complete -c dyld_info -o validate_only -d 'Display nothing if binary is valid, or information about what parts are malfo…'

