# dyldinfo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/dyldinfo.1
complete -c dyldinfo -o arch -d 'Only display the specified architecture'
complete -c dyldinfo -o dylibs -d 'Display the table of dylibs on which this image depends'
complete -c dyldinfo -o rebase -d 'Display the table of rebasing information'
complete -c dyldinfo -o bind -d 'Display the table of binding information'
complete -c dyldinfo -o weak_bind -d 'Display the table of weak binding information'
complete -c dyldinfo -o lazy_bind -d 'Display the table of lazy binding information'
complete -c dyldinfo -o export -d 'Display the table symbols which this image exports'
complete -c dyldinfo -o opcodes -d 'Display the low level opcodes used to encode all rebase and binding informati…'
complete -c dyldinfo -o function_starts -d 'Decodes the list of function start addresses.  El SEE ALSO otool 1 nm 1'

