# dyld
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/dyld.1
complete -c dyld -s L -d 'option to  otool (1) to discover the frameworks and shared libraries that the…'

