# dynamic_pager
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/dynamic_pager.8
complete -c dynamic_pager -s F -d 'The base name of the filename to use for the swapfiles'

