# echo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/echo.1
complete -c echo -s n -d 'Do not print the trailing newline character'

