# emond
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/emond.8
complete -c emond -s r -d 'Tells emond to look for rules files in the specified path'
complete -c emond -s c -d 'Tells emond to look in specified path for its config file'

