# encode_keychange
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/encode_keychange.1
complete -c encode_keychange -s E -d '<engineID> is intepreted as a hex string when preceeded by 0x, otherwise it i…'
complete -c encode_keychange -s f -d 'Force passphrases to be read from standard input'
complete -c encode_keychange -s h -d 'Display the help message'
complete -c encode_keychange -s N -d 'Passphrase used to generate the new Ku'
complete -c encode_keychange -s O -d 'Passphrase used to generate the old Ku'
complete -c encode_keychange -s P -d 'Turn off the prompt for passphrases when getting data from standard input'
complete -c encode_keychange -s v -d 'Be verbose'
complete -c encode_keychange -s V -d 'Echo passphrases to terminal'

