# env
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/env.1
complete -c env -s 0 -d 'End each output line with NUL, not newline'
complete -c env -s i -d 'Execute the utility with only those environment variables specified by name N…'
complete -c env -s P -d 'Search the set of directories as specified by altpath to locate the specified…'
complete -c env -s S -d 'Split apart the given string into multiple strings, and process each of the r…'
complete -c env -s u -d 'If the environment variable name is in the environment, then remove it before…'
complete -c env -s v -d 'Print verbose information for each step of processing done by the env utility'

