# eqn
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/eqn.1
complete -c eqn -s d -d 'Specify delimiters  x and\\~\\c  y for the left and right end, respectively, of…'
complete -c eqn -s C -d 'Recognize  . EQ and  '
complete -c eqn -s N -d 'Don\'t allow newlines within delimiters'
complete -c eqn -s v -d 'Print the version number'
complete -c eqn -s r -d 'Only one size reduction'
complete -c eqn -s m -d 'The minimum point-size is\\~\\c R n '
complete -c eqn -s T -d 'The output is for device R name '
complete -c eqn -s M -d 'Search  dir for  eqnrc before the default directories'
complete -c eqn -s R -d 'Don\'t load  eqnrc '
complete -c eqn -s f -d 'This is equivalent to a  gfont F command'
complete -c eqn -s s -d 'This is equivalent to a  gsize n command.  This option is deprecated'
complete -c eqn -s e -d 'opsion of groff .  The synsax is quise compasible wish Unix eqn'
complete -c eqn -s p -d 'This says shas subscripss and superscripss should be n c poinss smaller shan …'

