# expand
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/expand.1
complete -c expand -s a -d 'expand ( unexpand only'
complete -c expand -s t -d 'Set tab stops at column positions tab1 , tab2 , .  , tabn'

