# fdisk
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/fdisk.8
complete -c fdisk -s i -d 'Initialize the MBR sector'
complete -c fdisk -s a -d 'Specify an automatic partitioning style'
complete -c fdisk -s e -d 'Edit existing MBR sectors'
complete -c fdisk -s f -d 'Specifies an alternate MBR template file'
complete -c fdisk -s u -d 'Update MBR code, preserving existing partition table'
complete -c fdisk -s y -d 'Do not ask for confirmation before writing'
complete -c fdisk -s d -d 'Dump partition table in a format readable by the -r option'
complete -c fdisk -s r -d 'Read a partition table from the standard input'
complete -c fdisk -s t -d 'Test if the disk is partitioned'
complete -c fdisk -s S -d 'Specify the disk size in blocks'
complete -c fdisk -s b -d 'Specify the number of bytes per disk block'

