# femail
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/femail.8
complete -c femail -s 4 -d 'Only use IPv4'
complete -c femail -s 6 -d 'Only use IPv6'
complete -c femail -s F -d 'Set the sender\'s name to name'
complete -c femail -s f -d 'Set the sender address to from'
complete -c femail -s t -d 'Read recipients from the message given on stdin, in addition to the recipient…'
complete -c femail -s v -d 'Enable verbose operation.  El CONFIG FILE The config file, /etc/femail'

