# filtercalltree
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/filtercalltree.1
complete -c filtercalltree -o invertCallTree -d 'Print the call tree from hottest to coldest stack frame'
complete -c filtercalltree -o pruneCount -d 'Remove branches of the call tree that have count less than count'
complete -c filtercalltree -o pruneMallocSize -d 'Remove branches of the call tree that have malloc size less than size, such a…'
complete -c filtercalltree -o chargeSystemLibraries -d 'Remove stack frames from all libraries in /System and /usr, while still charg…'
complete -c filtercalltree -o chargeLibrary -d 'Remove stack frames from library-name, while still charging their cost to the…'
complete -c filtercalltree -o keepBoundaries -d 'When charging libraries to callers, keep the top call into excluded libraries'

