# find
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/find.1
complete -c find -s E -d 'Interpret regular expressions followed by -regex and -iregex primaries as ext…'
complete -c find -s H -d 'Cause the file information and file type (see stat 2 ) returned for each symb…'
complete -c find -s L -d 'Cause the file information and file type (see stat 2 ) returned for each symb…'
complete -c find -s P -d 'Cause the file information and file type (see stat 2 ) returned for each symb…'
complete -c find -s X -d 'Permit find to be safely used in conjunction with xargs 1'
complete -c find -s d -d 'Cause find to perform a depth-first traversal'
complete -c find -s s -d 'Cause find to traverse the file hierarchies in lexicographical order, i. e'
complete -c find -s x -d 'Prevent find from descending into directories that have a device number diffe…'

