# finger
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/finger.1
complete -c finger -s 4 -d 'Forces finger to use IPv4 addresses only'
complete -c finger -s 6 -d 'Forces finger to use IPv6 addresses only'
complete -c finger -s g -d 'This option restricts the gecos output to only the users\' real name'
complete -c finger -s h -d 'When used in conjunction with the s option, the name of the remote host is di…'
complete -c finger -s k -d 'Disable all use of utmpx 5'
complete -c finger -s l -d 'Produce a multi-line format displaying all of the information described for t…'
complete -c finger -s m -d 'Prevent matching of user names'
complete -c finger -s o -d 'When used in conjunction with the s option, the office location and office ph…'
complete -c finger -s p -d 'Prevent the l option of finger from displaying the contents of the '
complete -c finger -s s -d 'Display the user\'s login name, real name, terminal name and write status (as …'

