# firmwarepasswd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/firmwarepasswd.8
complete -c firmwarepasswd -o setpasswd -d 'Prompts to add a new firmware password or change and existing password if one…'
complete -c firmwarepasswd -o setmode -d 'Set the mode to "command" or "full"'
complete -c firmwarepasswd -o mode -d 'Displays the current mode if one is set'
complete -c firmwarepasswd -o check -d 'Displays whether or not a firmware password is set.  Pp'
complete -c firmwarepasswd -o delete -d 'Prompts for password and clears both password and the mode if correct'
complete -c firmwarepasswd -o verify -d 'Prompts for password and displays success if correct'
complete -c firmwarepasswd -o unlockseed -d 'Generates a firmware password recovery key'
complete -c firmwarepasswd -o disable-reset-capability -d 'Disables firmware password reset using unlockseed'
complete -c firmwarepasswd -o enable-reset-capability -d 'Enables firmware password reset using unlockseed'
complete -c firmwarepasswd -s h -d 'Displays a list of all the commands available in the firmwarepasswd tool, wit…'

