# fs_usage
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/fs_usage.1
complete -c fs_usage -s e -d 'Specifying the e option generates output that excludes sampling of the runnin…'
complete -c fs_usage -s w -d 'Specifying the w option forces a wider, more detailed output, regardless of t…'
complete -c fs_usage -s f -d 'Specifying the f option turns on output filtering based on the mode provided'
complete -c fs_usage -s b -d 'Specifying the b option annotates disk I/O events with BootCache info (if ava…'
complete -c fs_usage -s t -d 'Specifies a run timeout in seconds'
complete -c fs_usage -s R -d 'Specifies a raw trace file to process'
complete -c fs_usage -s S -d 'If R is selected, specifies the start time in microseconds to begin processin…'
complete -c fs_usage -s E -d 'If R is selected, specifies the ending time in microseconds to stop processin…'

