# fsck_exfat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/fsck_exfat.8
complete -c fsck_exfat -s q -d 'Causes fsck_exfat to quickly check whether the volume was unmounted cleanly'
complete -c fsck_exfat -s f -d 'This option is ignored by fsck_exfat and is present only for compatibility wi…'
complete -c fsck_exfat -s p -d 'Preen the specified file systems'
complete -c fsck_exfat -s y -d 'Causes fsck_exfat to assume yes as the answer to all questions'
complete -c fsck_exfat -s n -d 'Causes fsck_exfat to assume no as the answer to all questions'
complete -c fsck_exfat -s g -d 'Causes fsck_exfat to produce its output in GUI-compatible form'
complete -c fsck_exfat -s x -d 'Causes fsck_exfat to produce its output in an XML-like form'
complete -c fsck_exfat -s d -d 'Causes fsck_exfat to produce extra debugging output'
complete -c fsck_exfat -s S -d 'Causes fsck_exfat to create a shadow file containing all metadata read from t…'

