# fsck_apfs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/fsck_apfs.8
complete -c fsck_apfs -s q -d 'Causes fsck_apfs to quickly check whether the device is `clean\''
complete -c fsck_apfs -s n -d 'Never attempt to repair any damage that is found'
complete -c fsck_apfs -s y -d 'Always attempt to repair any damage that is found'
complete -c fsck_apfs -s l -d 'Enable live verification mode'
complete -c fsck_apfs -s s -d 'Print space verification summary'
complete -c fsck_apfs -s S -d 'Skip iteration of snapshots (top-level snapshot structures will still be chec…'
complete -c fsck_apfs -s o -d 'Repair overallocations; please do not run an older fsck_apfs on newer systems…'

