# fsck_msdos
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/fsck_msdos.8
complete -c fsck_msdos -s q -d 'Causes fsck_msdos to quickly check whether the volume was unmounted cleanly'
complete -c fsck_msdos -s f -d 'This option is ignored by fsck_msdos and is present only for compatibility wi…'
complete -c fsck_msdos -s n -d 'Causes fsck_msdos to assume no as the answer to all operator questions, excep…'
complete -c fsck_msdos -s p -d 'Preen the specified file systems'
complete -c fsck_msdos -s y -d 'Causes fsck_msdos to assume yes as the answer to all operator questions'

