# fsck_cs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/fsck_cs.8
complete -c fsck_cs -s q -d 'Performs a "quick" check and indicates if any corruptions were found via the …'
complete -c fsck_cs -s p -d 'Operates in "preen" mode.   MLV mirror blocks are repaired where necessary'
complete -c fsck_cs -s y -d 'Causes fsck_cs to assume "yes" as the answer to all questions'
complete -c fsck_cs -s n -d 'Causes fsck_cs to assume "no" as the answer to all questions'
complete -c fsck_cs -s x -d 'Causes fsck_cs to produce its output in an XML-like (plist) format'
complete -c fsck_cs -s g -d 'Causes fsck_cs to produce its output in GUI-compatible form'
complete -c fsck_cs -s l -d 'Reproduce all console output, as well as additional status and error messages…'
complete -c fsck_cs -l pv -d 'the component CoreStorage physical volume(s) directly'
complete -c fsck_cs -l uuid -d 'the CoreStorage logical volume group (as a UUID)'
complete -c fsck_cs -l lv -d 'a CoreStorage logical volume (as a device name) El DIAGNOSTICS The fsck_cs ut…'

