# ftp-proxy
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/ftp-proxy.8
complete -c ftp-proxy -s A -d 'Permit only anonymous FTP connections'
complete -c ftp-proxy -s a -d 'Specify the local IP address to use in bind 2 as the source for connections m…'
complete -c ftp-proxy -s D -d 'Specify a debug level, where the proxy emits verbose debug output into syslog…'
complete -c ftp-proxy -s g -d 'Specify the named group to drop group privileges to, after doing pf 4 lookups…'
complete -c ftp-proxy -s i -d 'Set ftp-proxy ftp-proxy for use with IP-Filter'
complete -c ftp-proxy -s M -d 'Specify the upper end of the port range the proxy will use for the data conne…'
complete -c ftp-proxy -s m -d 'Specify the lower end of the port range the proxy will use for all data conne…'
complete -c ftp-proxy -s n -d 'Activate network address translation NAT mode'
complete -c ftp-proxy -s p -d 'Set ftp-proxy ftp-proxy for use with pf'
complete -c ftp-proxy -s R -d 'Reverse proxy mode for FTP servers running behind a NAT gateway'
complete -c ftp-proxy -s r -d 'Use reverse host reverse DNS lookups for logging and libwrap use'
complete -c ftp-proxy -s S -d 'Source address to use for data connections made by the proxy'
complete -c ftp-proxy -s t -d 'Specifies a timeout, in seconds'
complete -c ftp-proxy -s u -d 'Specify the named user to drop privilege to, after doing pf 4 lookups which r…'
complete -c ftp-proxy -s V -d 'Be verbose'
complete -c ftp-proxy -s w -d 'Use the tcp wrapper access control library hosts_access 3, allowing connectio…'

