# fwkdp
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/fwkdp.1
complete -c fwkdp -l setargs -d 'Sets the nvram boot-args on the current machine to boot-args Ns \\&'
complete -c fwkdp -l proxy -d 'Use proxy mode only'
complete -c fwkdp -l core -d 'Use core dump receive mode only'
complete -c fwkdp -l verbose -d 'Verbose mode'
complete -c fwkdp -l disable -d 'Sets the nvram boot-args on the current machine to "debug=0x146" which disabl…'
complete -c fwkdp -l erase -d 'Deletes the boot-args variable from nvram'
complete -c fwkdp -l ioff -d 'Turns off interactive mode'
complete -c fwkdp -l restart -d 'Automatically restarts the machine only after the nvram has been modified by …'
complete -c fwkdp -l help -d 'Displays usage info for fwkdp'

