# fwkpfv
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/fwkpfv.1
complete -c fwkpfv -l appendlog -d 'Append output logging to /tmp/fwkpf. log'
complete -c fwkpfv -l openlog -d 'Open log file with Console. app.  Only valid with a Ns \\&'
complete -c fwkpfv -l newlog -d 'Create a new log file, rather than append.  Only valid with a Ns \\&'
complete -c fwkpfv -l prefix -d 'Prefix logger machine\'s ID to each log'
complete -c fwkpfv -l publish -d 'Do not publish FireWire unit directory keys'
complete -c fwkpfv -l single -d 'Use a single window even if multiple loggers are present'
complete -c fwkpfv -l buffer -d 'Sets the host\'s psuedo address space queue buffer to size Ns in bytes'
complete -c fwkpfv -l file -d 'Sets the log file path, if in use, to path Ns given as a path to a file'
complete -c fwkpfv -l setargs -d 'Sets the nvram boot-args on the current machine to boot-args Ns \\&'
complete -c fwkpfv -l setpm -d 'Sets the nvram boot-args on the current machine to "debug=0x14e io=0x880"'
complete -c fwkpfv -l disable -d 'Sets the nvram boot-args on the current machine to "debug=0x146" which disabl…'
complete -c fwkpfv -l erase -d 'Deletes the boot-args variable from nvram'
complete -c fwkpfv -l ioff -d 'Turns off interactive mode'
complete -c fwkpfv -l restart -d 'Automatically restarts the machine only after the nvram has been modified by …'
complete -c fwkpfv -l help -d 'Displays usage info for fwkpfv'

