# gcore
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/gcore.1
complete -c gcore -s s -d 'Suspend the process while the core file is captured'
complete -c gcore -s v -d 'Report progress on the dump as it proceeds'
complete -c gcore -s b -d 'Limit the size of the core file to size MiBytes'
complete -c gcore -s o -d 'Write the core file to path'
complete -c gcore -s c -d 'Write the core file to pathformat'

