# gen_bridge_metadata
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/gen_bridge_metadata.1
complete -c gen_bridge_metadata -s f -d 'Generates metadata for the given framework'
complete -c gen_bridge_metadata -s p -d 'Generates metadata based on the private headers of the given frameworks'
complete -c gen_bridge_metadata -s F -d 'Selects the metadata format that will be generated'
complete -c gen_bridge_metadata -s e -d 'Considers the given exception file when generating the final metadata format'
complete -c gen_bridge_metadata -l arm64e -d 'Write arm64e annotations instead of x86_64 and compiles the dylib as arm64e'
complete -c gen_bridge_metadata -l 64-bit -d 'This option has no effect'
complete -c gen_bridge_metadata -l no-32-bit -d 'This option has no effect'
complete -c gen_bridge_metadata -l no-64-bit -d 'This option has no effect'
complete -c gen_bridge_metadata -s c -d 'Provides custom flags that will be passed to the C compiler'
complete -c gen_bridge_metadata -s C -d 'Provides custom flags that will be passed to the C compiler, when generating …'
complete -c gen_bridge_metadata -s o -d 'Writes the output to the given file'
complete -c gen_bridge_metadata -s h -d 'Prints a summary of the options.  Pp'
complete -c gen_bridge_metadata -s d -d 'Turns on debugging messages'
complete -c gen_bridge_metadata -s v -d 'Shows the version of the program'

