# genstrings
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/genstrings.1
complete -c genstrings -s a -d 'Allows the output to be appended to the old output files'
complete -c genstrings -o SwiftUI -d 'Enables support for recognizing the SwiftUI Text initializer, including its s…'
complete -c genstrings -s s -d 'Recognizes routine as equivalent to NSLocalizedString'
complete -c genstrings -o skipTable -d 'Causes genstrings to skip over the file for \\fITable\\fR'
complete -c genstrings -o noPositionalParameters -d 'Turns off generation of positional parameters'
complete -c genstrings -s u -d 'Allow unicode characters in the value of strings files'
complete -c genstrings -o encoding -d 'Read source files using the given IANA charset name'
complete -c genstrings -o macRoman -d 'For compatibility, read source files using Mac Roman encoding'
complete -c genstrings -s q -d 'Turns off multiple key/value pairs warning'
complete -c genstrings -o bigEndian -d 'Causes output files to be written with the specified endianness and be prefix…'
complete -c genstrings -s o -d 'Specifies the directory in which the output string tables should be created'

