# GetFileInfo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/GetFileInfo.1
complete -c GetFileInfo -s P -d 'Acts on a symlink file instead of the file the symlink resolves to'
complete -c GetFileInfo -s a -d 'Gets a file\'s attribute bits where <attribute-letter> is one of the following…'
complete -c GetFileInfo -s t -d 'Gets the file type, a string of exactly four characters'
complete -c GetFileInfo -s c -d 'Gets the file\'s creator, a string of four characters enclosed in quotation ma…'
complete -c GetFileInfo -s d -d 'Gets the creation date, a string of the form "mm/dd/yyyy hh:mm:ss" in 24-hour…'
complete -c GetFileInfo -s m -d 'Gets the modification date, a string of the form "mm/dd/yyyy hh:mm:ss" in 24-…'

