# git-show-index
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/git-show-index.1
complete -c git-show-index -l object-format -d 'Specify the given object format (hash algorithm) for the index file'

