# git-stripspace
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/git-stripspace.1
complete -c git-stripspace -s s -l strip-comments -d 'Skip and remove all lines starting with comment character (default #)'
complete -c git-stripspace -s c -l comment-lines -d 'Prepend comment character and blank to each line'

