# git-request-pull
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/git-request-pull.1
complete -c git-request-pull -s p -d 'Include patch text in the output'

