# git-credential-store
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/git-credential-store.1
complete -c git-credential-store -l file -d 'Use <path> to lookup and store credentials'

