# git-check-mailmap
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/git-check-mailmap.1
complete -c git-check-mailmap -l stdin -d 'Read contacts, one per line, from the standard input after exhausting contact…'

