# gitweb
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/gitweb.1
complete -c gitweb -l export-all -d 'option is used) allows pulling only for those repositories that have git-daem…'

