# groff
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/groff.1
complete -c groff -s p -d and
complete -c groff -s l -d 'See groff_font (5) and the man pages of the output devices for more details'
complete -c groff -s P -d 'to pass options to output devices; for example, the following selects A4 pape…'

