# grog
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/grog.1
complete -c grog -s e
complete -c grog -o man
complete -c grog -o me
complete -c grog -o mm
complete -c grog -o mom
complete -c grog -o ms
complete -c grog -o mdoc
complete -c grog -o mdoc-old
complete -c grog -s p
complete -c grog -s R
complete -c grog -s g
complete -c grog -s G
complete -c grog -s s -d and
complete -c grog -s t -d 'are required for printing files , and prints the groff command including thos…'
complete -c grog -s C -d '(which is also passed on) to enable compatibility mode, and'
complete -c grog -s v -d 'to print the version number'
complete -c grog -o Tdvi -d option

