# grolj4
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/grolj4.1
complete -c grolj4 -s c -d 'Print  n copies of each page'
complete -c grolj4 -s l -d 'Print the document with a landscape orientation'
complete -c grolj4 -s d -d 'Use duplex mode R n : 1is long-side binding; 2is short-side binding; default …'
complete -c grolj4 -s p -d 'Set the paper size to R size , which must be one of letter, legal, executive,…'
complete -c grolj4 -s v -d 'Print the version number'
complete -c grolj4 -s w -d 'Set the default line thickness to  n thousandths of an em'
complete -c grolj4 -s F -d 'Prepend directory B dir /dev name to the search path for font and device desc…'

