# grolbp
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/grolbp.1
complete -c grolbp -s c -d 'TQ  --copies= numcopies Print  numcopies copies of each page'
complete -c grolbp -s l -d 'TQ  --landscape Print the document with a landscape orientation'
complete -c grolbp -s p -d 'TQ  --papersize= paper_size Set the paper size to R paper_size , which must b…'
complete -c grolbp -s o -d 'TQ  --orientation= orientation Print the document with  orientation orientati…'
complete -c grolbp -s w -d 'TQ  --linewidth= width Set the default line thickness to  width thousandths o…'
complete -c grolbp -s v -d 'TQ  --version Print the version number'
complete -c grolbp -s F -d 'TQ  --fontdir= dir Prepend directory B dir /dev name to the search path for f…'
complete -c grolbp -l copies -d 'Print numcopies copies of each page'
complete -c grolbp -l landscape -d 'Print the document with a landscape orientation'
complete -c grolbp -l papersize -d 'Set the paper size to paper_size , which must be a valid paper size descripti…'
complete -c grolbp -l orientation -d 'Print the document with orientation orientation, which must be `portrait\' or …'
complete -c grolbp -l linewidth -d 'Set the default line thickness to width thousandths of an em'
complete -c grolbp -l version -d 'Print the version number'
complete -c grolbp -l fontdir -d 'Prepend directory dir /dev name to the search path for font and device descri…'
complete -c grolbp -s h
complete -c grolbp -l help -d 'Print a short help text'

