# grops
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/grops.1
complete -c grops -s b -d 'Provide workarounds for older printers, broken spoolers, and previewers'
complete -c grops -s c -d 'Print  n copies of each page'
complete -c grops -s F -d 'Prepend directory B dir /dev name to the search path for prologue, font, and …'
complete -c grops -s g -d 'Guess the page length'
complete -c grops -s I -d 'This option may be used to specify a directory to search for files on the com…'
complete -c grops -s l -d 'Print the document in landscape format'
complete -c grops -s m -d 'Turn manual feed on for the document'
complete -c grops -s p -d 'Set physical dimension of output medium'
complete -c grops -s P -d 'Use the file  prologue-file (in the font path) as the prologue instead of the…'
complete -c grops -s w -d 'Lines should be drawn using a thickness of R n \\~\\c thousandths of an em'
complete -c grops -o Tps -d 'option.  If no files are given, grops will read the standard input'
complete -c grops -s v -d 'Print the version number'

