# gzexe
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/gzexe.1
complete -c gzexe -s d -d 'Decompress executables previously compressed by gzexe'

