# h2ph5
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/h2ph5.30.1
complete -c h2ph5 -s e -d 'If an error is encountered during conversion, output file will be removed and…'

