# hdik
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/hdik.8
complete -c hdik -o shadow -d 'Use a shadow file in conjunction with the data in the image'
complete -c hdik -o nomount -d 'Suppress automatic mounting of filesystems contained within the image'
complete -c hdik -o drivekey -d 'Specify a key/value pair for the IOHDIXHDDrive object created (shows up in th…'

