# headerdoc2html
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/headerdoc2html.1
complete -c headerdoc2html -s H -d 'The H option turns on inclusion of the htmlHeader line, as specified in the c…'
complete -c headerdoc2html -s X -d 'The X option switches from HTML to XML output'
complete -c headerdoc2html -s d -d 'The d option turns on extra debugging output'
complete -c headerdoc2html -s h -d 'The h option causes headerdoc to output an XML file containing metadata about…'
complete -c headerdoc2html -s p -d 'The p option turns on the C preprocessor'
complete -c headerdoc2html -s q -d 'The q option causes headerdoc to be excessively quiet'
complete -c headerdoc2html -s u -d 'The u option causes headerdoc to produce unsorted output'
complete -c headerdoc2html -s v -d 'The v option causes headerdoc to print version information'

