# heap
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/heap.1
complete -c heap -s s -d 'Sort output by total size of class instances, rather than by count'
complete -c heap -s z -d 'Show the output separated out into the different malloc zones, instead of an …'
complete -c heap -o guessNonObjects -d 'Look through the memory contents of each Objective-C object to find pointers …'
complete -c heap -o sumObjectFields -d 'Do the same analysis as with the guessNonObjects option, but add the sizes of…'
complete -c heap -o showSizes -d 'Show the distribution of each malloc size for each object, instead of summing…'
complete -c heap -o diffFrom -d 'Show only the new objects since the specified memgraph'
complete -c heap -o addresses -d 'Print the addresses of all malloc blocks found on the heap in ascending addre…'
complete -c heap -o noContent -d 'Do not show object content in -addresses mode'

