# hfs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/hfs.util.8
complete -c hfs -s a -d 'Adopt permissions for the HFS file system at device'
complete -c hfs -s I -d 'Print out status information about the journal on the HFS file system at moun…'
complete -c hfs -s J -d 'Enable journaling on the HFS file system mounted on mountpoint'
complete -c hfs -s k -d 'Get the UUID key for the HFS file system at device'
complete -c hfs -s m -d 'Mount the HFS file system located on device onto mountpoint with the flags mo…'
complete -c hfs -s M -d 'Force mount the HFS file system located on device onto mountpoint with the fl…'
complete -c hfs -s N -d 'Disable journaling on a HFS+ file system located at device'
complete -c hfs -s p -d 'Probe the device for an HFS file system using the flags mountflag1 mountflag2…'
complete -c hfs -s s -d 'Set the UUID key (generates a new UUID value) for the HFS file system at devi…'
complete -c hfs -s u -d 'Unmount the HFS file system located at device'
complete -c hfs -s U -d 'Disable journaling on the HFS+ file system mounted on mountpoint El Pp The mo…'

