# host
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/host.1
complete -c host -s 4 -d 'Use IPv4 only for query transport.  See also the -6 option'
complete -c host -s 6 -d 'Use IPv6 only for query transport.  See also the -4 option'
complete -c host -s a -d '"All".  The -a option is normally equivalent to -v -t ANY'
complete -c host -s c -d 'Query class: This can be used to lookup HS (Hesiod) or CH (Chaosnet) class re…'
complete -c host -s C -d 'Check consistency: host will query the SOA records for zone name from all the…'
complete -c host -s d -d 'Print debugging traces.  Equivalent to the -v verbose option'
complete -c host -s i -d Obsolete
complete -c host -s l -d 'List zone: The host command performs a zone transfer of zone name and prints …'
complete -c host -s N -d 'The number of dots that have to be in name for it to be considered absolute'
complete -c host -s r -d 'Non-recursive query: Setting this option clears the RD (recursion desired) bi…'
complete -c host -s R -d 'Number of retries for UDP queries: If number is negative or zero, the number …'
complete -c host -s s -d 'Do not send the query to the next nameserver if any server responds with a SE…'
complete -c host -s t -d 'Query type: The type argument can be any recognized query type: CNAME, NS, SO…'
complete -c host -s T -d 'TCP: By default, host uses UDP when making queries'
complete -c host -s m -d 'Memory usage debugging: the flag can be record, usage, or trace'
complete -c host -s v -d 'Verbose output.  Equivalent to the -d debug option'
complete -c host -s V -d 'Print the version number and exit'
complete -c host -s w -d 'Wait forever: The query timeout is set to the maximum possible'
complete -c host -s W -d 'Timeout: Wait for up to wait seconds for a reply'

