# hpftodit
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/hpftodit.1
complete -c hpftodit -s a -d 'Include characters in the TFM file that are not included in the map file'
complete -c hpftodit -s d -d 'Dump information about the TFM file to the standard output; this option can b…'
complete -c hpftodit -s q -d 'Suppress warnings about characters in the map file that were not found in the…'
complete -c hpftodit -s v -d 'Print the  hpftodit version number'
complete -c hpftodit -s s -d 'The font is special'
complete -c hpftodit -s i -d 'Generate an italic correction for each character so that the character\'s widt…'

