# htdigest
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/htdigest.1
complete -c htdigest -s c -d 'Create the passwdfile.  If passwdfile already exists, it is deleted first'

