# ifconfig
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/ifconfig.8
complete -c ifconfig -o alias -d 'Remove the network address specified'
complete -c ifconfig -o arp -d 'Disable the use of the Address Resolution Protocol arp 4'
complete -c ifconfig -o debug -d 'Disable driver dependent debugging code'
complete -c ifconfig -o mediaopt -d 'If the driver supports the media selection system, disable the specified medi…'
complete -c ifconfig -o rxcsum -d 'If the driver supports user-configurable checksum offloading, disable receive…'
complete -c ifconfig -o tso -d 'If the driver supports tcp 4 segmentation offloading, disable TSO on the inte…'
complete -c ifconfig -o lro -d 'If the driver supports tcp 4 large receive offloading, disable LRO on the int…'
complete -c ifconfig -o av -d 'If supported by the driver, disable 802. 1 AVB on the interface'
complete -c ifconfig -o vlanmtu -d 'If the driver offers user-configurable VLAN support, disable reception of ext…'
complete -c ifconfig -o link -d 'on Disable special processing at the link level with the specified interface'
complete -c ifconfig -o bonddev -d 'If the interface is a bond pseudo device, disassociate the physical interface…'
complete -c ifconfig -o tunnel -d 'Unconfigure the physical source and destination address for IP tunnel interfa…'
complete -c ifconfig -o vlandev -d 'If the driver is a vlan 4 pseudo device, disassociate the parent interface fr…'

