# info
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/info.1
complete -c info -l apropos -d 'look up STRING in all indices of all manuals'
complete -c info -s d -l directory -d 'add DIR to INFOPATH'
complete -c info -l dribble -d 'remember user keystrokes in FILENAME'
complete -c info -s f -l file -d 'specify Info file to visit'
complete -c info -s h -l help -d 'display this help and exit'
complete -c info -l index-search -d 'go to node pointed by index entry STRING'
complete -c info -s n -l node -d 'specify nodes in first visited Info file'
complete -c info -s o -l output -d 'output selected nodes to FILENAME'
complete -c info -s R -l raw-escapes -d 'output "raw" ANSI escapes (default)'
complete -c info -l no-raw-escapes -d 'output escapes as literal text'
complete -c info -l restore -d 'read initial keystrokes from FILENAME'
complete -c info -s O -l show-options -l usage -d 'go to command-line options node'
complete -c info -l subnodes -d 'recursively output menu items'
complete -c info -s w -l where -l location -d 'print physical location of Info file'
complete -c info -l vi-keys -d 'use vi-like and less-like key bindings'
complete -c info -l version -d 'display version information and exit'

