# infokey
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/infokey.1
complete -c infokey -l output -d 'output to FILE instead of $HOME/. info'
complete -c infokey -l help -d 'display this help and exit'
complete -c infokey -l version -d 'display version information and exit'

