# install
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/install.1
complete -c install -s B -d 'Use suffix as the backup suffix if b is given'
complete -c install -s b -d 'Back up any existing files before overwriting them by renaming them to file N…'
complete -c install -s C -d 'Copy the file'
complete -c install -s c -d 'Copy the file.  This is actually the default'
complete -c install -s d -d 'Create directories.  Missing parent directories are created as required'
complete -c install -s f -d 'Specify the target\'s file flags; see chflags 1 for a list of possible flags a…'
complete -c install -s g -d 'Specify a group.  A numeric GID is allowed'
complete -c install -s M -d 'Disable all use of mmap 2'
complete -c install -s m -d 'Specify an alternate mode.  The default mode is set to rwxr-xr-x (0755)'
complete -c install -s o -d 'Specify an owner.  A numeric UID is allowed'
complete -c install -s p -d 'Preserve the modification time'
complete -c install -s S -d 'Safe copy'
complete -c install -s s -d 'install install exec\'s the command strip 1 to strip binaries so that install …'
complete -c install -s v -d 'Causes install install to show when C actually installs something'

