# install-info
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/install-info.1
complete -c install-info -l delete -d 'delete existing entries for INFO-FILE from DIR-FILE; don\'t insert any new ent…'
complete -c install-info -l dir-file -d 'specify file name of Info directory file'
complete -c install-info -l entry -d 'insert TEXT as an Info directory entry'
complete -c install-info -l help -d 'display this help and exit'
complete -c install-info -l info-file -d 'specify Info file to install in the directory'
complete -c install-info -l info-dir -d 'same as --dir-file=DIR/dir'
complete -c install-info -l item -d 'same as --entry TEXT.  An Info directory entry is actually a menu item'
complete -c install-info -l quiet -d 'suppress warnings'
complete -c install-info -l remove -d 'same as --delete'
complete -c install-info -l section -d 'put this file\'s entries in section SEC of the directory'
complete -c install-info -l version -d 'display version information and exit'

