# install_name_tool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/install_name_tool.1
complete -c install_name_tool -o change -d 'Changes the dependent shared library install name  old to  new in the specifi…'
complete -c install_name_tool -o id -d 'Changes the shared library identification name of a dynamic shared library to…'
complete -c install_name_tool -o rpath -d 'Changes the rpath path name  old to  new in the specified Mach-O binary'
complete -c install_name_tool -o add_rpath -d 'Adds the rpath path name  new in the specified Mach-O binary'
complete -c install_name_tool -o headerpad_max_install_names -d option
complete -c install_name_tool -o delete_rpath -d 'deletes the rpath path name old in the specified Mach-O binary'

