# ioreg
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/ioreg.8
complete -c ioreg -s a -d 'Archive the output in XML'
complete -c ioreg -s b -d 'Show the object name in bold'
complete -c ioreg -s c -d 'Show the object properties only if the object is an instance of, or derives f…'
complete -c ioreg -s d -d 'Limit tree traversal to the specified depth'
complete -c ioreg -s f -d 'Enable smart formatting'
complete -c ioreg -s i -d 'Show the object inheritance'
complete -c ioreg -s k -d 'Show the object properties only if the object has the specified key'
complete -c ioreg -s l -d 'Show properties for all displayed objects'
complete -c ioreg -s n -d 'Show the object properties only if the object has the specified name'
complete -c ioreg -s p -d 'Traverse the registry over the specified plane'
complete -c ioreg -s r -d 'Show subtrees rooted by objects that match the specified criteria'
complete -c ioreg -s t -d 'Show tree location of each subtree'
complete -c ioreg -s w -d 'Clip the output to the specified line width'
complete -c ioreg -s x -d 'Show data and numbers as hexadecimal.  El'

