# iostat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/iostat.8
complete -c iostat -o '?\\&' -d 'Display a usage statement and exit'
complete -c iostat -s c -d 'Repeat the display count times'
complete -c iostat -s C -d 'Display CPU statistics.  This is on by default, unless d is specified'
complete -c iostat -s d -d 'Display only device statistics'
complete -c iostat -s I -d 'Display total statistics for a given time period, rather than average statist…'
complete -c iostat -s K -d 'In the blocks transferred display (-o), display block count in kilobytes rath…'
complete -c iostat -s n -d 'Display up to devs number of devices'
complete -c iostat -s o -d 'Display old-style iostat device statistics'
complete -c iostat -s T -d 'Display TTY statistics.  This is on by default, unless d is specified'
complete -c iostat -s U -d 'Display system load averages.  This is on by default, unless d is specified'
complete -c iostat -s w -d 'Pause wait seconds between each display'

