# ipcrm
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ipcrm.1
complete -c ipcrm -s q -d 'Remove the message queue associated with the ID msqid from the system'
complete -c ipcrm -s m -d 'Mark the shared memory segment associated with ID shmid for removal'
complete -c ipcrm -s s -d 'Remove the semaphore set associated with ID semid from the system'
complete -c ipcrm -s Q -d 'Remove the message queue associated with key msgkey from the system'
complete -c ipcrm -s M -d 'Mark the shared memory segment associated with key shmkey for removal'
complete -c ipcrm -s S -d 'Remove the semaphore set associated with key semkey from the system'

