# ipcs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ipcs.1
complete -c ipcs -s a -d 'Show the maximum amount of information possible when displaying active semaph…'
complete -c ipcs -s b -d 'Show the maximum allowed sizes for active semaphores, message queues, and sha…'
complete -c ipcs -s c -d 'Show the creator\'s name and group for active semaphores, message queues, and …'
complete -c ipcs -s M -d 'Display system information about shared memory'
complete -c ipcs -s m -d 'Display information about active shared memory segments'
complete -c ipcs -s o -d 'Show outstanding usage for active message queues, and shared memory segments'
complete -c ipcs -s p -d 'Show the process ID information for active semaphores, message queues, and sh…'
complete -c ipcs -s Q -d 'Display system information about messages queues'
complete -c ipcs -s q -d 'Display information about active message queues'
complete -c ipcs -s S -d 'Display system information about semaphores'
complete -c ipcs -s s -d 'Display information about active semaphores'
complete -c ipcs -s T -d 'Display system information about shared memory, message queues and semaphores'
complete -c ipcs -s t -d 'Show access times for active semaphores, message queues, and shared memory se…'
complete -c ipcs -s u -d 'Display information about IPC mechanisms owned by user'

