# jar
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/jar.1
complete -c jar -l module-version -d '[bu] 2'
complete -c jar -l hash-modules -d '[bu] 2'
complete -c jar -l module-path
complete -c jar -s c -l create -d 'Creates the archive'
complete -c jar -s i -l generate-index -d 'Generates index information for the specified JAR file'
complete -c jar -s t -l list -d 'Lists the table of contents for the archive'
complete -c jar -s u -l update -d 'Updates an existing JAR file'
complete -c jar -s x -l extract -d 'Extracts the named (or all) files from the archive'
complete -c jar -s d -l describe-module -d 'Prints the module descriptor or automatic module name'
complete -c jar -s C -d 'Changes the specified directory and includes the files specified at the end o…'
complete -c jar -s f -l file -d 'Specifies the archive file name'
complete -c jar -l release -d 'Creates a multirelease JAR file'
complete -c jar -s v -l verbose -d 'Sends or prints verbose output to standard output'
complete -c jar -s e -l main-class -d 'Specifies the application entry point for standalone applications bundled int…'
complete -c jar -s m -l manifest -d 'Includes the manifest information from the given manifest file'
complete -c jar -s M -l no-manifest -d 'Doesn[aq]t create a manifest file for the entries'
complete -c jar -s p -d 'Specifies the location of module dependence for generating the hash'
complete -c jar -s 0 -l no-compress -d 'Stores without using ZIP compression.  OTHER OPTIONS'
complete -c jar -s h -l help -d 'Displays the command-line help for the jar command or optionally the compatib…'
complete -c jar -l help-extra -d 'Displays help on extra options'
complete -c jar -l version -d 'Prints the program version'

