# java_home
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/java_home.1
complete -c java_home -s v -l version -d 'Filters the returned JVMs by version (as if JAVA_VERSION had been set in the …'
complete -c java_home -s a -l arch -d 'Filters the returned JVMs by the architecture they support (as if JAVA_ARCH h…'
complete -c java_home -s F -l failfast -d 'Immediately fails when filters return no JVMs; does not print out the path to…'
complete -c java_home -l exec -d 'Executes the command at $JAVA_HOME/bin/<command> and passes the remaining arg…'
complete -c java_home -s X -l xml -d 'Prints a list of all matching JVMs and associated properties as an XML plist …'
complete -c java_home -s V -l verbose -d 'Prints a list of all matching JVMs and architectures to stderr'
complete -c java_home -s h -l help -d 'Brief usage information'

