# jcmd
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/jcmd.1
complete -c jcmd -o all -d 'Compiler. codecache Prints code cache layout and bounds.  Impact: Low'
complete -c jcmd -s l -d '(BOOLEAN, false) VM'
complete -c jcmd -s i -d '(BOOLEAN, false) [bu] 2'
complete -c jcmd -s s -d subclasses
complete -c jcmd -o verbose -d 'table (BOOLEAN, false) VM. symboltable [options] Dumps the symbol table'
complete -c jcmd -o date -d '(BOOLEAN, false) VM. version Prints JVM version information.  Impact: Low'

