# jconsole
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/jconsole.1
complete -c jconsole -o interval -d 'Sets the update interval to n seconds (default is 4 seconds)'
complete -c jconsole -o notile -d 'Doesn[aq]t tile the windows for two or more connections'
complete -c jconsole -o pluginpath -d 'Specifies the path that jconsole uses to look up plug-ins'
complete -c jconsole -o version -d 'Prints the program version'
complete -c jconsole -o Jinput_arguments -d 'Passes input_arguments to the JVM on which the jconsole command is run'
complete -c jconsole -o help -l help -d 'Displays the help message for the command.  DESCRIPTION'

