# jdb
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/jdb.1
complete -c jdb -o help -d 'Displays a help message'
complete -c jdb -o sourcepath -d 'Uses the specified path to search for source files in the specified path'
complete -c jdb -o attach -d 'Attaches the debugger to a running JVM with the default connection mechanism'
complete -c jdb -o listen -d 'Waits for a running JVM to connect to the specified address with a standard c…'
complete -c jdb -o listenany -d 'Waits for a running JVM to connect at any available address using a standard …'
complete -c jdb -o launch -d 'Starts the debugged application immediately upon startup of the jdb command'
complete -c jdb -o listconnectors -d 'Lists the connectors available in this JVM'
complete -c jdb -o connect -d 'Connects to the target JVM with the named connector and listed argument values'
complete -c jdb -o dbgtrace -d 'Prints information for debugging the jdb command'
complete -c jdb -o tclient -d 'Runs the application in the Java HotSpot VM client'
complete -c jdb -o tserver -d 'Runs the application in the Java HotSpot VM server'
complete -c jdb -o Joption -d 'Passes option to the JVM, where option is one of the options described on the…'
complete -c jdb -s v -o 'verbose[:class' -d 'Turns on the verbose mode'
complete -c jdb -o Dname -d 'Sets a system property'
complete -c jdb -o classpath -d 'Lists directories separated by colons in which to look for classes'
complete -c jdb -s X -d 'A nonstandard target JVM option'

