# jdeprscan
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/jdeprscan.1
complete -c jdeprscan -l class-path -d 'Provides a search path for resolution of dependent classes'
complete -c jdeprscan -l for-removal -d 'Limits scanning or listing to APIs that are deprecated for removal'
complete -c jdeprscan -l full-version -d 'Prints out the full version string of the tool'
complete -c jdeprscan -l help -s h -d 'Prints out a full help message'
complete -c jdeprscan -l list -s l -d 'Prints the set of deprecated APIs'
complete -c jdeprscan -l release -d 'Specifies the Java SE release that provides the set of deprecated APIs for sc…'
complete -c jdeprscan -l verbose -s v -d 'Enables additional message output during processing'
complete -c jdeprscan -l version -d 'Prints out the abbreviated version string of the tool'

