# jfr
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/jfr.1
complete -c jfr -l xml -d 'Print the recording in XML format'
complete -c jfr -l json -d 'Print the recording in JSON format'
complete -c jfr -l categories -d 'Select events matching a category name'
complete -c jfr -l events -d 'Select events matching an event name'
complete -c jfr -l stack-depth -d 'Number of frames in stack traces, by default 5 <file> Location of the recordi…'
complete -c jfr -l output -d 'The location to write the disassembled file, by default the current directory'
complete -c jfr -l max-chunks -d 'Maximum number of chunks per file, by default 5'
complete -c jfr -l max-size -d 'Maximum number of bytes per file'

