# jhsdb
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/jhsdb.1
complete -c jhsdb -l serverid -d 'An optional unique ID for this debug server'
complete -c jhsdb -l rmiport -d 'Sets the port number to which the RMI connector is bound'
complete -c jhsdb -l registryport -d 'Sets the RMI registry port'
complete -c jhsdb -l hostname -d 'Sets the hostname the RMI connector is bound'
complete -c jhsdb -l flags -d 'Prints the VM flags'
complete -c jhsdb -l sysprops -d 'Prints the Java system properties'
complete -c jhsdb -l heap -d 'Prints the java heap summary'
complete -c jhsdb -l binaryheap -d 'Dumps the java heap in hprof binary format'
complete -c jhsdb -l dumpfile -d 'The name of the dumpfile'
complete -c jhsdb -l histo -d 'Prints the histogram of java object heap'
complete -c jhsdb -l clstats -d 'Prints the class loader statistics'
complete -c jhsdb -l finalizerinfo -d 'Prints the information on objects awaiting finalization'
complete -c jhsdb -l locks -d 'Prints the java. util. concurrent locks information'
complete -c jhsdb -l mixed -d 'Attempts to print both java and native frames if the platform allows it'
complete -c jhsdb -l all -d 'Prints all performance counters'

