# jinfo
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/jinfo.1
complete -c jinfo -o flag -d 'Prints the name and value of the specified command-line flag'
complete -c jinfo -o ']name' -d 'Enables or disables the specified Boolean command-line flag'
complete -c jinfo -o flags -d 'Prints command-line flags passed to the JVM'
complete -c jinfo -o sysprops -d 'Prints Java system properties as name-value pairs'
complete -c jinfo -s h -o help -d 'Prints a help message'

