# jmap
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/jmap.1
complete -c jmap -o clstats -d 'Connects to a running process and prints class loader statistics of Java heap'
complete -c jmap -o finalizerinfo -d 'Connects to a running process and prints information on objects awaiting fina…'
complete -c jmap -o histo -d 'Connects to a running process and prints a histogram of the Java object heap'
complete -c jmap -o dump:dump_options -d 'Connects to a running process and dumps the Java heap'

