# jps
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/jps.1
complete -c jps -s q -d 'Suppresses the output of the class name, JAR file name, and arguments passed …'
complete -c jps -o mlvV -d 'You can specify any combination of these options'
complete -c jps -s m -d 'The output may be null for embedded JVMs.  [bu] 2'
complete -c jps -s l -d 'main class or the full path name to the application[aq]s JAR file.  [bu] 2'
complete -c jps -s v -d '[bu] 2'
complete -c jps -s V -d 'arguments passed to the main method, producing a list of only local JVM ident…'
complete -c jps -o help -d 'Displays the help message for the jps command.  DESCRIPTION'

