# jstatd
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/jstatd.1
complete -c jstatd -o nr -d 'OPTIONS FOR THE JSTATD COMMAND'
complete -c jstatd -s p -d 'This option sets the port number where the RMI registry is expected to be fou…'
complete -c jstatd -s r -d 'This option sets the port number to which the RMI connector is bound'
complete -c jstatd -s n -d 'This option sets the name to which the remote RMI object is bound in the RMI …'
complete -c jstatd -o Joption -d 'This option passes a Java option to the JVM, where the option is one of those…'

