# jstack
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/jstack.1
complete -c jstack -s l -d 'The long listing option prints additional information about locks'
complete -c jstack -s h -o help -d 'Prints a help message'

