# jstat
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/jstat.1
complete -c jstat -o help -d 'Displays a help message'
complete -c jstat -o options -d 'Displays a list of static options.  See Output Options for the jstat Command'
complete -c jstat -s J -d 'The statOption must come first'
complete -c jstat -o statOption -d 'Determines the statistics information that the jstat command displays'
complete -c jstat -o JjavaOption -d 'Passes javaOption to the Java application launcher'
complete -c jstat -o class -d 'Class loader statistics.  Loaded: Number of classes loaded'
complete -c jstat -o compiler -d 'Java HotSpot VM Just-in-Time compiler statistics'
complete -c jstat -o gc -d 'Garbage collected heap statistics'
complete -c jstat -o gccapacity -d 'Memory pool generation and space capacities'
complete -c jstat -o gccause -d 'This option displays the same summary of garbage collection statistics as the…'
complete -c jstat -o gcnew -d 'New generation statistics.  S0C: Current survivor space 0 capacity (KB)'
complete -c jstat -o gcnewcapacity -d 'New generation space size statistics'
complete -c jstat -o gcold -d 'Old generation size statistics.  MC: Metaspace Committed Size (KB)'
complete -c jstat -o gcoldcapacity -d 'Old generation statistics.  OGCMN: Minimum old generation capacity (KB)'
complete -c jstat -o gcmetacapacity -d 'Metaspace size statistics.  MCMN: Minimum metaspace capacity (KB)'
complete -c jstat -o gcutil -d 'Summary of garbage collection statistics'
complete -c jstat -o printcompilation -d 'Java HotSpot VM compiler method statistics'
complete -c jstat -o XX:+PrintCompilation

