# kadmind
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/kadmind.8
complete -c kadmind -s c -d 'location of config file'
complete -c kadmind -s k -d 'location of master key file'
complete -c kadmind -l keytab -d 'what keytab to use'
complete -c kadmind -s r -d 'realm to use'
complete -c kadmind -s d -d 'enable debugging'
complete -c kadmind -s p -d 'ports to listen to'

