# kdestroy
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/kdestroy.1
complete -c kdestroy -o credential -d 'remove principal from the credential cache if it exists'
complete -c kdestroy -s p
complete -c kdestroy -o principal -d 'The cache with client principal to remove'
complete -c kdestroy -s c
complete -c kdestroy -o cache -d 'The cache to remove'
complete -c kdestroy -s A
complete -c kdestroy -s a
complete -c kdestroy -l all -d 'remove all credential caches'
complete -c kdestroy -l no-unlog -d 'Do not remove AFS tokens'
complete -c kdestroy -l no-delete-v4 -d 'Do not remove v4 tickets.  El SEE ALSO kinit 1, klist 1'

