# KernelEventAgent
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/KernelEventAgent.8
complete -c KernelEventAgent -s d -d 'Debug mode'
complete -c KernelEventAgent -s v -d 'Verbose mode'
complete -c KernelEventAgent -s f -d 'The file system identified by fsname is also passed the timeout value via the…'
complete -c KernelEventAgent -s t -d 'The timeout value, specified in seconds, is the amount of time to wait before…'

