# kextunload
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/kextunload.8
complete -c kextunload -s b -d 'Unload executable and IOKitPersonalities (as described immediately above) for…'
complete -c kextunload -s c -d 'Terminate all instances of class classname that are in the IOService plane of…'
complete -c kextunload -s h -d 'Print a help message describing each option flag and exit with a success resu…'
complete -c kextunload -s m -d 'Same as b (remains for backward compatibility)'
complete -c kextunload -s p -d 'Terminate services and remove personalities only; do not unload kexts'
complete -c kextunload -s q -d 'Quiet mode; print no informational or error messages'
complete -c kextunload -s v -d 'Verbose mode; print information about program operation'

