# kextlibs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/kextlibs.8
complete -c kextlibs -s h -d 'Print a help message describing each option flag and exit with a success resu…'
complete -c kextlibs -o all-symbols -d 'Print reports on all symbols that remain undefined, all symbols that have bee…'
complete -c kextlibs -s c -d 'Print the compatible version rather than the current version'
complete -c kextlibs -o multdef-symbols -d 'Print all undefined symbols from kext found in more than one library kext, fo…'
complete -c kextlibs -o non-kpi -d 'Search the compatibility kext, com. apple. kernel. 6'
complete -c kextlibs -o onedef-symbols -d 'Print all undefined symbols from kext found in exactly one library kext, foll…'
complete -c kextlibs -s r -d 'Search directory for dependencies'
complete -c kextlibs -s e -d 'Add /System/Library/Extensions and /Library/Extensions to the list of directo…'
complete -c kextlibs -o undef-symbols -d 'Print all undefined symbols from kext that can\'t be found in any library kexts'
complete -c kextlibs -o unsupported -d 'Search unsupported library kexts for symbols (by default they are not searche…'
complete -c kextlibs -s v -d 'Verbose mode; print information about program operation'
complete -c kextlibs -o xml -d 'Print an XML fragment to stdout suitable for copying and pasting directly int…'

