# kextfind
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/kextfind.8
complete -c kextfind -s h -d 'Print a help message describing each option flag and exit with a success resu…'
complete -c kextfind -o set-arch -d 'Set the architecture used for such things as architecture-specific properties…'
complete -c kextfind -s i -d 'Perform case-insensitive comparisons for all property, match property, and bu…'
complete -c kextfind -s s -d 'Perform substring searches for all property, match property, and bundle ident…'
complete -c kextfind -o no-paths -d 'Print no paths for kexts, just their bundle names, and for info dictionary an…'
complete -c kextfind -o relative-paths -d 'Print pathnames relative to kexts\' repositories (which can be ambiguous if mu…'
complete -c kextfind -s 0 -d 'Make the echo and all print Ns \\&. \\|. \\|'
complete -c kextfind -s f -d 'Specifies a kext or directory of kexts to search'
complete -c kextfind -s e -d 'Adds /System/Library/Extensions and /Library/Extensions to the list of direct…'
complete -c kextfind -s b
complete -c kextfind -o bundle-id -d 'True if the kext\'s bundle identifier matches identifier'
complete -c kextfind -o dup
complete -c kextfind -o duplicate-id -d 'True if any other kext has the same bundle identifier as the current kext'
complete -c kextfind -s B
complete -c kextfind -o bundle-name -d 'True if the kext\'s bundle name matches name'
complete -c kextfind -s m
complete -c kextfind -o match-property -d 'True if the kext has at least one personality that contains value as a string…'
complete -c kextfind -o me
complete -c kextfind -o match-property-exists -d 'True if the kext has at least one personality containing any value for the na…'
complete -c kextfind -s p
complete -c kextfind -o property -d 'True if the kext\'s info dictionary contains value as a string, number, or boo…'
complete -c kextfind -o pe
complete -c kextfind -o property-exists -d 'True if the kext\'s info dictionary contains any value for the named property'
complete -c kextfind -s a -d 'True if the kext is owned by root:wheel and has proper permissions'
complete -c kextfind -s d -d 'True if the kext has all its dependencies met'
complete -c kextfind -o nd -d 'True if the kext is missing dependencies (or can\'t have its dependencies reso…'
complete -c kextfind -o na -d 'True if the kext is not owned by root:wheel or has improper permissions (or c…'
complete -c kextfind -o nv -d 'True if the kext is not valid'
complete -c kextfind -s l -d 'True if the kext appears to be loadable'
complete -c kextfind -o loaded -d 'True if the kext is currently loaded (if its bundle identifier, version, and …'
complete -c kextfind -o nl -d 'True if the kext can\'t be loaded because it is invalid, inauthentic, or missi…'
complete -c kextfind -s v -d 'True if the kext is valid'
complete -c kextfind -s w -d 'True if any warnings are noted while validating the kext'
complete -c kextfind -o arch -d 'True if the kext contains all of the named CPU architectures (separated by co…'
complete -c kextfind -o ax -d 'True if the kext contains all of the named CPU architectures (separated by co…'
complete -c kextfind -o dsym -d 'True if the kext defines the named symbol in any of its architectures'
complete -c kextfind -s x -d 'True if the kext declares an executable via the CFBundleExecutable property (…'
complete -c kextfind -o nx -d 'True if the kext does not declare an executable via the CFBundleExecutable pr…'
complete -c kextfind -o rsym -d 'True if the kext has an undefined reference to the named symbol in any of its…'
complete -c kextfind -o debug -d 'True if the kext has a top-level OSBundleEnableKextLogging property set to tr…'
complete -c kextfind -o has-plugins -d 'True if the kext contains plugins'
complete -c kextfind -o integrity -d 'OBSOLETE.  As of Mac OS X 10'
complete -c kextfind -o kernel-resource -d 'True if the kext represents a resource built into the kernel'
complete -c kextfind -o lib -d 'True if the kext is a library that other kexts can link against'
complete -c kextfind -o plugin -d 'True if the kext is a plugin of another kext'
complete -c kextfind -s C -d 'True if the kext is potentially required for console-mode startup (same as p …'
complete -c kextfind -s L -d 'True if the kext is potentially required for local-root startup (same as p Cm…'
complete -c kextfind -s N -d 'True if the kext is potentially required for network-root startup (same as p …'
complete -c kextfind -s R -d 'True if the kext is potentially required for root startup (same as p Cm OSBun…'
complete -c kextfind -s S -d 'True if the kext is potentially allowed to load during safe boot (same as p C…'
complete -c kextfind -o compatible-with-version -d 'True if the kext is a library kext compatible with the given version'
complete -c kextfind -s V -d 'ne Ns | Ns Cm gt Ns | Ns Cm ge Ns | Ns Cm lt Ns | Ns Cm le Oc Ns Ar version N…'
complete -c kextfind -o version -d 'ne Ns | Ns Cm gt Ns | Ns Cm ge Ns | Ns Cm lt Ns | Ns Cm le Oc Ns Ar version N…'
complete -c kextfind -o echo -d 'Prints string followed by a newline'
complete -c kextfind -o print -d 'Prints the pathname of the kext'
complete -c kextfind -o print0 -d 'Equivalent to print nul, for all you find 1 users out there'
complete -c kextfind -o pa
complete -c kextfind -o print-arches -d 'Prints the names of all the architectures in the kext executable (if it has o…'
complete -c kextfind -o print-dependencies -d 'Prints the pathnames of all direct and indirect dependencies of the kext'
complete -c kextfind -o print-dependents -d 'Prints the pathnames of all direct and indirect dependents of the kext'
complete -c kextfind -o pdiag
complete -c kextfind -o print-diagnostics -d 'Prints validation and authentication failures, missing dependencies, and warn…'
complete -c kextfind -o px
complete -c kextfind -o print-executable -d 'Prints the pathname to the kext\'s executable file'
complete -c kextfind -o pid
complete -c kextfind -o print-info-dictionary -d 'Prints the pathname to the kext\'s info dictionary file'
complete -c kextfind -o print-integrity -d 'OBSOLETE.  As of Mac OS X 10'
complete -c kextfind -o print-plugins -d 'Prints the pathnames of all plugins of the kext'
complete -c kextfind -o pm
complete -c kextfind -o print-match-property -d 'For each matching personality in the kext, if the named property exists, prin…'
complete -c kextfind -o pp
complete -c kextfind -o print-property -d 'If the top-level property exists, prints name followed by an equals sign and …'
complete -c kextfind -o not -d 'This is the unary NOT operator'
complete -c kextfind -o sym -d 'Prints references or defines if the kext references or defines symbol'

