# kextload
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/kextload.8
complete -c kextload -s b -d 'Look up the kext whose CFBundleIdentifier is identifier within the set of kno…'
complete -c kextload -s d -d 'Add kext and its plugins to the set of known kexts for resolving dependencies'
complete -c kextload -s h -d 'Print a help message describing each option flag and exit with a success resu…'
complete -c kextload -s q -d 'Quiet mode; print no informational or error messages'
complete -c kextload -s r -d 'Use directory as a repository of kexts'
complete -c kextload -s v -d 'Verbose mode; print information about program operation'

