# kextstat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/kextstat.8
complete -c kextstat -s a -d 'Print the architecture of the kext'
complete -c kextstat -s b -d 'Display the status of only the kext with the given bundle identifier'
complete -c kextstat -s h -d 'Print a help message describing each option flag and exit with a success resu…'
complete -c kextstat -s k -d 'Don\'t show information for built-in components of the kernel'
complete -c kextstat -s l -d 'Print the list of loaded kexts only and omit the header (useful for running o…'
complete -c kextstat -s s -d 'Sort the list by load address'

