# krbservicesetup
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/krbservicesetup.8
complete -c krbservicesetup -s x -d 'Use kadmin. local instead of kadmin'
complete -c krbservicesetup -s r -d 'The Kerberos realm of the server'
complete -c krbservicesetup -s a -d 'Name of an administrator with priveleges to add principals to the KDC'
complete -c krbservicesetup -s p -d 'Password for the above user'
complete -c krbservicesetup -s t -d 'The path of the keytab file to write'
complete -c krbservicesetup -s f -d 'The path of the plist file containing the list of services to be configured s…'

