# last
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/last.1
complete -c last -s n -d 'Limits the report to n lines'
complete -c last -s h -d 'Host names may be names or internet numbers'
complete -c last -s t -d 'Specify the tty'

