# latency
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/latency.1
complete -c latency -s c -d 'When the c option is specified, it takes a path to a code file that contains …'
complete -c latency -s h -d 'Display high resolution interrupt latencies and write them to latencies'
complete -c latency -s m -d 'Display per-CPU interrupt latency statistics'
complete -c latency -o it -d 'Set the interrupt latency threshold, expressed in microseconds'
complete -c latency -s l -d 'Specifies a log file that is written to when either the interrupt or scheduli…'
complete -c latency -s n -d 'By default, latency latency acts on the default /System/Library/Kernels/kernel'
complete -c latency -s p -d 'Specifies the priority level to observe scheduler latencies for'
complete -c latency -o st -d 'Set the scheduler latency threshold in microseconds'
complete -c latency -s R -d 'Specifies a raw trace file to use as input'

