# layerutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/layerutil.1
complete -c layerutil -s c -d 'Convert to lcr format'
complete -c layerutil -s f -d 'Saves the flattened image as a jpeg to the output path given by the -o flag'
complete -c layerutil -s g -d 'Sets program to use gpu optimized compression'
complete -c layerutil -s l -d 'Set the lossy compression factor used for image content to a value between 0 …'
complete -c layerutil -s s -d 'Used to specify the scale factor used in the generated lcr file'
complete -c layerutil -s p -d 'v can be one of srgb/p3'
complete -c layerutil -s o -d 'Output file name'
complete -c layerutil -s h -d 'Prints out usage information'
complete -c layerutil -s V -d 'Prints out version information.  \\" Ends the list Pp'

