# ldapurl
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ldapurl.1
complete -c ldapurl -s a -d 'Set a comma-separated list of attribute selectors'
complete -c ldapurl -s b -d 'Set the searchbase'
complete -c ldapurl -s E -d 'Specify general extensions with -e and search extensions with -E'
complete -c ldapurl -s f -d 'Set the URL filter'
complete -c ldapurl -s H -d 'Specify URI to be exploded'
complete -c ldapurl -s h -d 'Set the host'
complete -c ldapurl -s p -d 'Set the TCP port'
complete -c ldapurl -s S -d 'Set the URL scheme'
complete -c ldapurl -s s -d OPTIONS
complete -c ldapurl -s e

