# ldapwhoami
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ldapwhoami.1
complete -c ldapwhoami -s n -d 'Show what would be done, but don\'t actually perform the whoami operation'
complete -c ldapwhoami -s v -d 'Run in verbose mode, with many diagnostics written to standard output'
complete -c ldapwhoami -s d -d 'Set the LDAP debugging level to debuglevel'
complete -c ldapwhoami -s x -d 'Use simple authentication instead of SASL'
complete -c ldapwhoami -s D -d 'Use the Distinguished Name binddn to bind to the LDAP directory'
complete -c ldapwhoami -s W -d 'Prompt for simple authentication'
complete -c ldapwhoami -s w -d 'Use passwd as the password for simple authentication'
complete -c ldapwhoami -s y -d 'Use complete contents of passwdfile as the password for simple authentication'
complete -c ldapwhoami -s H -d 'Specify URI(s) referring to the ldap server(s); only the protocol/host/port f…'
complete -c ldapwhoami -s h -d 'Specify an alternate host on which the ldap server is running'
complete -c ldapwhoami -s p -d 'Specify an alternate TCP port where the ldap server is listening'
complete -c ldapwhoami -s O -d 'Specify SASL security properties'
complete -c ldapwhoami -s E -d 'Specify general extensions with -e and search extensions with -E'
complete -c ldapwhoami -s I -d 'Enable SASL Interactive mode.   Always prompt'
complete -c ldapwhoami -s Q -d 'Enable SASL Quiet mode.   Never prompt'
complete -c ldapwhoami -s U -d 'Specify the authentication ID for SASL bind'
complete -c ldapwhoami -s R -d 'Specify the realm of authentication ID for SASL bind'
complete -c ldapwhoami -s X -d 'Specify the requested authorization ID for SASL bind'
complete -c ldapwhoami -s Y -d 'Specify the SASL mechanism to be used for authentication'
complete -c ldapwhoami -s e
complete -c ldapwhoami -s Z -d 'Issue StartTLS (Transport Layer Security) extended operation.  If you use'
complete -c ldapwhoami -o ZZ -d EXAMPLE

