# ldapcompare
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ldapcompare.1
complete -c ldapcompare -s n -d 'Show what would be done, but don\'t actually perform the compare'
complete -c ldapcompare -s v -d 'Run in verbose mode, with many diagnostics written to standard output'
complete -c ldapcompare -s z -d 'Run in quiet mode, no output is written.   You must check the return status'
complete -c ldapcompare -s M -d 'Enable manage DSA IT control.   -MM makes control critical'
complete -c ldapcompare -s d -d 'Set the LDAP debugging level to debuglevel'
complete -c ldapcompare -s x -d 'Use simple authentication instead of SASL'
complete -c ldapcompare -s D -d 'Use the Distinguished Name binddn to bind to the LDAP directory'
complete -c ldapcompare -s W -d 'Prompt for simple authentication'
complete -c ldapcompare -s w -d 'Use passwd as the password for simple authentication'
complete -c ldapcompare -s y -d 'Use complete contents of passwdfile as the password for simple authentication'
complete -c ldapcompare -s H -d 'Specify URI(s) referring to the ldap server(s); only the protocol/host/port f…'
complete -c ldapcompare -s h -d 'Specify an alternate host on which the ldap server is running'
complete -c ldapcompare -s p -d 'Specify an alternate TCP port where the ldap server is listening'
complete -c ldapcompare -s P -d 'Specify the LDAP protocol version to use'
complete -c ldapcompare -s E -d 'Specify general extensions with -e and search extensions with -E'
complete -c ldapcompare -s O -d 'Specify SASL security properties'
complete -c ldapcompare -s I -d 'Enable SASL Interactive mode.   Always prompt'
complete -c ldapcompare -s Q -d 'Enable SASL Quiet mode.   Never prompt'
complete -c ldapcompare -s U -d 'Specify the authentication ID for SASL bind'
complete -c ldapcompare -s R -d 'Specify the realm of authentication ID for SASL bind'
complete -c ldapcompare -s X -d 'Specify the requested authorization ID for SASL bind'
complete -c ldapcompare -s Y -d 'Specify the SASL mechanism to be used for authentication'
complete -c ldapcompare -o MM -d 'makes control critical'
complete -c ldapcompare -s e
complete -c ldapcompare -s Z -d 'Issue StartTLS (Transport Layer Security) extended operation.  If you use'
complete -c ldapcompare -o ZZ -d EXAMPLES

