# leaks
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/leaks.1
complete -c leaks -o list -d 'Print the leaks as a list ("classic"-style) rather than as a tree'
complete -c leaks -o groupByType -d 'When printing a tree of leaked objects, group the children of a node in the t…'
complete -c leaks -o nostacks -d 'Do not print backtraces of leaked blocks even if the target process has the M…'
complete -c leaks -o nosources -d 'Do not print sourceFile:lineNumber in backtraces'
complete -c leaks -o quiet -d 'Do not print process description header or binary image list'
complete -c leaks -o exclude -d 'Exclude leaked blocks whose backtraces include the specified symbol'
complete -c leaks -o outputGraph -d 'Generate a memory graph file containing information about all VM and malloc n…'
complete -c leaks -o fullContent -d 'When generating a memory graph file, include descriptions of the content of v…'
complete -c leaks -o readonlyContent -d 'When running leaks against a live target process, print descriptions of the c…'
complete -c leaks -o noContent -d 'Do not print the descriptions of the content of leaked memory, or save descri…'
complete -c leaks -o diffFrom -d 'Show only the new leaks since the specified memgraph'
complete -c leaks -o traceTree -d 'Print a reverse tree of references, from the given block up to the process \'r…'
complete -c leaks -o referenceTree -d 'Print a top-down tree of all malloc allocations and dynamically-allocated VM …'
complete -c leaks -o autoreleasePools -d 'Print the contents of all autorelease pools of all threads of the process, an…'
complete -c leaks -o debug -d 'This flag offers several additional more detailed modes of output, intended f…'
complete -c leaks -o atExit -d 'Launches the specified command and runs leaks leaks when that process exits'

