# libtool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/libtool.1
complete -c libtool -o static -d 'Produce a statically linked (archive) library from the input files'
complete -c libtool -o dynamic -d 'Produce a dynamically linked shared library from the input files'
complete -c libtool -o install_name -d 'For a dynamic shared library, this specifies the file  name the library will …'
complete -c libtool -o compatibility_version -d 'For a dynamic shared library, this specifies the compatibility version number…'
complete -c libtool -o current_version -d 'For dynamic shared library files this specifies the current version number of…'
complete -c libtool -o noall_load -d 'For dynamic shared library files this specifies the the default behavior of l…'
complete -c libtool -s v -d 'Verbose mode, which prints the R ld (1) commands and R lipo (1) commands exec…'
complete -c libtool -s V -d 'Print the version of libtool'
complete -c libtool -o filelist -d 'The  listfile contains a list of file names and is an alternative way of spec…'
complete -c libtool -o arch_only -d 'This option causes libtool to build a library only for the specified  arch_ty…'
complete -c libtool -s s -d 'Produce the preferred type of table of contents, which results in faster link…'
complete -c libtool -s a -d 'Produce the original type of table of contents, whose order is based on the o…'
complete -c libtool -s c -d 'Include common symbols as definitions with respect to the table of contents'
complete -c libtool -s L -d 'Use the 4'
complete -c libtool -s T -d 'Truncate archive member names to 16 characters and don\'t use the 4'
complete -c libtool -s f -d 'Warns when the output archive is universal and R ar (1) will no longer be abl…'
complete -c libtool -s q -d 'Do nothing if a universal file would be created'
complete -c libtool -s D -d 'When building a static library, set archive contents\' user ids, group ids, da…'
complete -c libtool -s t -d 'This option used to request that  ranlib only ``touch\'\' the archives instead …'
complete -c libtool -o no_warning_for_no_symbols -d 'Don\'t warn about file that have no symbols'
complete -c libtool -s o -d 'flag)'
complete -c libtool -o dylib -d 'once for each architecture present in the input objects and then lipo (1) to …'
complete -c libtool -o dynamiclib -d option
complete -c libtool -s l
complete -c libtool -o weak-l
complete -c libtool -o search_paths_first
complete -c libtool -o weak_library
complete -c libtool -s y
complete -c libtool -s u
complete -c libtool -o init
complete -c libtool -s i
complete -c libtool -o seg1addr
complete -c libtool -o segs_read_only_addr
complete -c libtool -o segs_read_write_addr
complete -c libtool -o seg_addr_table
complete -c libtool -o seg_addr_table_filename
complete -c libtool -o segprot
complete -c libtool -o segalign
complete -c libtool -o sectcreate
complete -c libtool -o sectorder
complete -c libtool -o sectorder_detail
complete -c libtool -o sectalign
complete -c libtool -o undefined
complete -c libtool -o read_only_relocs
complete -c libtool -o prebind
complete -c libtool -o prebind_all_twolevel_modules
complete -c libtool -o prebind_allow_overlap
complete -c libtool -o noprebind
complete -c libtool -o framework
complete -c libtool -o weak_framework
complete -c libtool -o umbrella
complete -c libtool -o allowable_client
complete -c libtool -o sub_umbrella
complete -c libtool -o sub_library
complete -c libtool -s F
complete -c libtool -s U
complete -c libtool -s Y
complete -c libtool -o Sn
complete -c libtool -o Si
complete -c libtool -o Sp
complete -c libtool -s S
complete -c libtool -s X
complete -c libtool -s x
complete -c libtool -o whyload
complete -c libtool -o all_load
complete -c libtool -o arch_errors_fatal
complete -c libtool -o dylib_file
complete -c libtool -o run_init_lazily
complete -c libtool -o final_output
complete -c libtool -o macosx_version_min
complete -c libtool -o multiply_defined
complete -c libtool -o multiply_defined_unused
complete -c libtool -o twolevel_namespace
complete -c libtool -o twolevel_namespace_hints
complete -c libtool -o flat_namespace
complete -c libtool -o nomultidefs
complete -c libtool -o headerpad
complete -c libtool -o headerpad_max_install_names
complete -c libtool -o weak_reference_mismatches
complete -c libtool -s M
complete -c libtool -o no_arch_warnings
complete -c libtool -o single_module
complete -c libtool -o multi_module
complete -c libtool -o exported_symbols_list
complete -c libtool -o unexported_symbols_list
complete -c libtool -s m
complete -c libtool -o dead_strip
complete -c libtool -o no_dead_strip_inits_and_terms
complete -c libtool -o executable_path
complete -c libtool -o syslibroot
complete -c libtool -o no_uuid -d 'See the ld (1) man page for details on these flags.  The flag'
complete -c libtool -o image_base -d 'is a synonym for'
complete -c libtool -o force_cpusubtype_ALL -d 'flag and passes the'
complete -c libtool -o arch -d 'flag so that the output is tagged with that cpusubtype'
complete -c libtool -o dependency_info -d 'Write an Xcode dependency info file describing a successful build operation'

