# lipo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/lipo.1
complete -c lipo -o arch -d 'Tells  lipo that  input_file contains the specified architecture type'
complete -c lipo -o hideARM64 -d 'When creating a universal binary including both 32-bit and 64-bit ARM files, …'
complete -c lipo -o output -d 'Commands that create new files write to the output file specified by the  -ou…'
complete -c lipo -o archs -d 'Display only the architecture names present in a single input file'
complete -c lipo -o create -d 'Create one universal output file from one or more input files'
complete -c lipo -o detailed_info -d 'Display a detailed list of the architecture types in the input universal file…'
complete -c lipo -o extract -o extract -d 'Take one universal input file and copy the arch_type from that universal file…'
complete -c lipo -o extract_family -o extract_family -d 'Take one universal input file and copy all of the arch_type s for the family …'
complete -c lipo -o info -d 'Display a brief description of each input file along with the names of each a…'
complete -c lipo -o remove -o remove -d 'Take one universal input file and remove the arch_type from that universal fi…'
complete -c lipo -o replace -o replace -d 'Take one universal input file; in the output file, replace the arch_type cont…'
complete -c lipo -o thin -d 'Take one input file and create a thin output file with the specified arch_type'
complete -c lipo -o verify_arch -d 'Take one input file and verify the specified arch_type s are present in the f…'
complete -c lipo -o segalign -d 'Set the segment alignment of the specified arch_type when creating a universa…'

