# lkbib
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/lkbib.1
complete -c lkbib -s v -d 'Print the version number'
complete -c lkbib -s p -d 'Search R filename .  Multiple  -p options can be used'
complete -c lkbib -s i -d 'When searching files for which no index exists, ignore the contents of fields…'
complete -c lkbib -s t -d 'Only require the first n characters of keys to be given.  Initially n is 6'

