# locale
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/locale.1
complete -c locale -s a -d 'Lists all public locales'
complete -c locale -s c -d 'Lists the category name before each keyword, unless it is the same category a…'
complete -c locale -s k -d 'Displays the name of each keyword prior to its value'
complete -c locale -s m -d 'Lists all available public charmaps'

