# localedef
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/localedef.1
complete -c localedef -s c -d 'Create permanent output even if warning messages have been issued'
complete -c localedef -s f -d 'Specify the pathname of a file containing a mapping of character symbols and …'
complete -c localedef -s i -d 'The pathname of a file containing the source definitions'

