# localemanager
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/localemanager.8
complete -c localemanager -s l -d 'Locale name'
complete -c localemanager -o subnet -d 'Subnet specified in CIDR notation'
complete -c localemanager -o server -d 'Server fully-qualified domain name'
complete -c localemanager -s i -d 'Use this IP address for the server'

