# logger
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/logger.1
complete -c logger -s i -d 'Log the process id of the logger process with each line'
complete -c logger -s s -d 'Log the message to standard error, as well as the system log'
complete -c logger -s f -d 'Log the specified file'
complete -c logger -s p -d 'Enter the message with the specified priority'
complete -c logger -s t -d 'Mark every line in the log with the specified tag '

