# login
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/login.1
complete -c login -s f -d 'When a user name is specified, this option indicates that proper authenticati…'
complete -c login -s h -d 'Specify the host from which the connection was received'
complete -c login -s l -d 'Tells the program executed by login that this is not a login session (by conv…'
complete -c login -s p -d 'By default, login discards any previous environment'
complete -c login -s q -d 'This forces quiet logins, as if a . hushlogin is present'

