# look
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/look.1
complete -c look -s d -d 'Dictionary character set and order, i. e'
complete -c look -s f -d 'Ignore the case of alphabetic characters'
complete -c look -s t -d 'Specify a string termination character, i. e'

