# lookbib
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/lookbib.1
complete -c lookbib -s v -d 'Print the version number'
complete -c lookbib -s i -d 'When searching files for which no index exists, ignore the contents of fields…'
complete -c lookbib -s t -d 'Only require the first n characters of keys to be given.  Initially n is 6'

