# lpq
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/lpq.1
complete -c lpq -s E -d 'Forces encryption when connecting to the server'
complete -c lpq -s P -d 'Specifies an alternate printer or class name'
complete -c lpq -s U -d 'Specifies an alternate username'
complete -c lpq -s a -d 'Reports jobs on all printers'
complete -c lpq -s h -d 'Specifies an alternate server'
complete -c lpq -s l -d 'Requests a more verbose (long) reporting format'

