# lprm
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/lprm.1
complete -c lprm -s E -d 'Forces encryption when connecting to the server'
complete -c lprm -s P -d 'Specifies the destination printer or class'
complete -c lprm -s U -d 'Specifies an alternate username'
complete -c lprm -s h -d 'Specifies an alternate server'

