# lsappinfo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/lsappinfo.8
complete -c lsappinfo -s v -l verbose
complete -c lsappinfo -s q -l quiet
complete -c lsappinfo -o defaultSession
complete -c lsappinfo -o currentSession
complete -c lsappinfo -o debug -o info -o notice -o warning -o err -o critical -o alert -o emergency

