# lsbom
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/lsbom.8
complete -c lsbom -s h -d 'print full usage'
complete -c lsbom -s b -d 'list block devices'
complete -c lsbom -s c -d 'list character devices'
complete -c lsbom -s d -d 'list directories'
complete -c lsbom -s f -d 'list files'
complete -c lsbom -s l -d 'list symbolic links'
complete -c lsbom -s m -d 'print modified times (for plain files only)'
complete -c lsbom -s s -d 'print only the path of each file'
complete -c lsbom -s x -d 'suppress modes for directories and symlinks'
complete -c lsbom -l arch -d 'when displaying plain files that represent Universal Mach-O binaries, print t…'
complete -c lsbom -s p -d 'print only some of the results lsbom Note: each option can only be used once:…'

