# lskq
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/lskq.1
complete -c lskq -s p -d 'Show kqueues of process <pid>'
complete -c lskq -s a -d 'Show kqueues for all running processes.  Requires root'
complete -c lskq -s v -d 'Verbose: show opaque user data and filter-specific extension fields'
complete -c lskq -s e -d 'Ignore empty kqueues'
complete -c lskq -s r -d 'Print fields in raw hex'
complete -c lskq -s h -d 'Show help and exit'

