# malloc_history
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/malloc_history.1
complete -c malloc_history -o showContent -d 'Show the content of malloc blocks of various types, including C strings, Pasc…'
complete -c malloc_history -o invert -d 'Invert the call tree, so that malloc (and the allocated content, if the showC…'
complete -c malloc_history -o ignoreThreads -d 'Combine the call trees for all threads into a single call tree'
complete -c malloc_history -o collapseRecursion -d 'Collapse recursion within the call trees'
complete -c malloc_history -o chargeSystemLibraries -d 'Remove stack frames from all libraries in /System and /usr, while still charg…'
complete -c malloc_history -o virtual -d 'Display the size of VM regions as the virtual size, rather than the default d…'

