# mandoc_soelim
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/mandoc_soelim.1
complete -c mandoc_soelim -s C -d 'Recognise . so when not followed by a space character'
complete -c mandoc_soelim -s r -d 'Compatibility with GNU groff\'s mandoc_soelim soelim (does nothing)'
complete -c mandoc_soelim -s t -d 'Compatibility with GNU groff\'s mandoc_soelim soelim (does nothing)'
complete -c mandoc_soelim -s v -d 'Compatibility with GNU groff\'s mandoc_soelim soelim (does nothing)'
complete -c mandoc_soelim -s I -d 'This option specify directories where mandoc_soelim searches for files (both …'

