# master
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/master.8
complete -c master -s c -d 'Read the main. cf and master'
complete -c master -s D -d 'After initialization, run a debugger on the master process'
complete -c master -s d -d 'Do not redirect stdin, stdout or stderr to /dev/null, and do not discard the …'
complete -c master -s e -d 'Terminate the master process after exit_time seconds'
complete -c master -s t -d 'Test mode.  Return a zero exit status when the master'
complete -c master -s v -d 'Enable verbose logging for debugging purposes'
complete -c master -s w -d 'Wait in a dummy foreground process, while the real master daemon initializes …'

