# mcxrefresh
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/mcxrefresh.1
complete -c mcxrefresh -s u -d 'Specify the numeric user id of the user to be refreshed'
complete -c mcxrefresh -s n -d 'Specify the short name of the user to be refreshed'
complete -c mcxrefresh -s a -d 'Ask for authentication and pass it to ManagedClient.  El Pp'

