# md5
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/md5.1
complete -c md5 -s s -d 'Print a checksum of the given string'
complete -c md5 -s p -d 'Echo stdin to stdout and append the checksum to stdout'
complete -c md5 -s q -d 'Quiet mode - only the checksum is printed out.  Overrides the r option'
complete -c md5 -s r -d 'Reverses the format of the output.  This helps with visual diffs'
complete -c md5 -s t -d 'Run a built-in time trial'
complete -c md5 -s x -d 'Run a built-in test script'

