# mdfind
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/mdfind.1
complete -c mdfind -s 0 -d 'Prints an ASCII NUL character after each result path'
complete -c mdfind -o live -d 'Causes the mdfind command to provide live-updates to the number of files matc…'
complete -c mdfind -o count -d 'Causes the mdfind command to output the total number of matches, instead of t…'
complete -c mdfind -o onlyin -d 'Limit the scope of the search to the directory specified'
complete -c mdfind -o name -d 'Searches for matching file names only'
complete -c mdfind -o literal -d 'Force the provided query string to be taken as a literal query string, withou…'
complete -c mdfind -o interpret -d 'Force the provided query string to be interpreted as if the user had typed th…'

