# mdimport
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/mdimport.1
complete -c mdimport -s i -d 'Request Spotlight to import file or recursively import directory'
complete -c mdimport -s t -d 'Request Spotlight to test import file, sending the result back to mdimport md…'
complete -c mdimport -s d -d 'Print debugging information.   This requires t.  -literal -offset indent'
complete -c mdimport -o d1 -d 'print summary of test import'
complete -c mdimport -o d2 -d 'print summary of import and all attributes, except kMDItemTextContent'
complete -c mdimport -o d3 -d 'print summary of import and all attributes Ed'
complete -c mdimport -s o -d 'Store attribute into outfile.  This requires t'
complete -c mdimport -s p -d 'Print out performance information gathered during the run.   This requires t'
complete -c mdimport -s A -d 'Print out the list of all of the attributes and their localizations in the cu…'
complete -c mdimport -s X -d 'Print the schema file and exit'
complete -c mdimport -s L -d 'Print the list of installed importers and exit'
complete -c mdimport -s r -d 'Ask the server to reimport files for UTIs claimed by the listed plugin'

