# mdls
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/mdls.1
complete -c mdls -o name -d 'Print only the matching metadata attribute value'
complete -c mdls -o raw -d 'Print raw attribute data in the order that was requested'
complete -c mdls -o nullMarker -d 'Sets a marker string to be used when a requested attribute is null'

