# mDNSResponder
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mDNSResponder.8
complete -c mDNSResponder -o AlwaysAppendSearchDomains -d 'Append search domains for multi-labeled Partially Qualified Domain Name as we…'
complete -c mDNSResponder -o NoMulticastAdvertisements -d 'Prevent the system from advertising Bonjour services via Multicast DNS'

