# mdutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/mdutil.1
complete -c mdutil -s i -d 'Sets the indexing status for the provided volumes to on or off'
complete -c mdutil -s d -d 'Disables Spotlight searches on the provided volume'
complete -c mdutil -s E -d 'This flag will cause each local store for the volumes indicated to be erased'
complete -c mdutil -s s -d 'Display the indexing status of the listed volumes'
complete -c mdutil -s a -d 'Apply command to all stores on all volumes'
complete -c mdutil -s t -d 'Resolve files from file id with an optional volume path or device id'
complete -c mdutil -s p -d 'Spotlight caches indexes of some network devices locally'
complete -c mdutil -s V -d 'Apply command to all stores on the specified volume'
complete -c mdutil -s v -d 'Print verbose information when available'
complete -c mdutil -s r -d 'Ask the server to reimport files for UTIs claimed by the listed plugin'
complete -c mdutil -s L -d 'List the directory contents of the Spotlight index on the specified volume'
complete -c mdutil -s P -d 'Dump the VolumeConfig. plist for the specified volume'
complete -c mdutil -s X -d 'Remove the Spotlight index directory on the specified volume'

