# mg
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/mg.1
complete -c mg -s b -d 'Turn on batch mode and execute the mg commands found in the specified file an…'
complete -c mg -s f -d 'Run the mode command for all buffers created from arguments on the command li…'
complete -c mg -s n -d 'Turn off backup file generation'
complete -c mg -s R -d 'Files specified on the command line will be opened read-only'
complete -c mg -s u -d 'Use file as the startup file, instead of the default ~/. mg'

