# migcom
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/migcom.1
complete -c migcom -o q/-Q -d 'Omit /  emit warning messages'
complete -c migcom -o v/-V -d 'Verbose mode ( on /  off ) will summarize types and routines as they are proc…'
complete -c migcom -o l/-L -d 'Controls (  off / on ) whether or not generated code logs RPC events to syste…'
complete -c migcom -o k/-K -d 'Controls (  on / off ) whether generated code complies with ANSI C standards'
complete -c migcom -o s/-S -d 'Controls ( on /  off ) whether generated server-side code includes a generate…'
complete -c migcom -s i -d 'Specify User file prefix'
complete -c migcom -o user -d 'Specify name of user-side RPC generated source file'
complete -c migcom -o server -d 'Specify name of server-side RPC generated source file'
complete -c migcom -o header -d 'Specify name of user-side generated header file'
complete -c migcom -o sheader -d 'Specify name of server-side generated header file'
complete -c migcom -o iheader -d 'Specify internal header file name'
complete -c migcom -o dheader -d 'Specify defines generated header file'
complete -c migcom -o maxonstack -d 'Specify maximum size of message on stack'
complete -c migcom -o split -d 'Use split headers'

