# mklocale
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/mklocale.1
complete -c mklocale -s d -d 'Turns on debugging messages'
complete -c mklocale -s o -d 'Specify output file'

