# mnthome
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/mnthome.1
complete -c mnthome -s v -d 'Display version number'
complete -c mnthome -s d -d 'Print debugging information'
complete -c mnthome -s m -d 'Alternative mount point is specified with the m option followed by a path to …'
complete -c mnthome -s n -d 'Do not force the unmount of the previous mount point'
complete -c mnthome -s b -d 'Exec the user\'s shell after mount of home'
complete -c mnthome -s p -d 'A password may be specified with the p option followed by a password'
complete -c mnthome -s i -d 'Display information about the AFP home mount point'
complete -c mnthome -s u -d 'Attempt to unmount the current home directory mount'
complete -c mnthome -s x -d 'This option must be followed by a path to an existing AFP mount point'
complete -c mnthome -s s -d 'Skip preflight check to see if the currently mounted home directory is alread…'

