# mount_afp
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount_afp.8
complete -c mount_afp -s i -d 'Interactive mode, you are prompted for the password if you did not supply one…'
complete -c mount_afp -s s -d 'Soft mount (default).  Network errors, e. g'
complete -c mount_afp -s k -d 'Hard mount.  Network errors, e. g'
complete -c mount_afp -s o -d 'Options passed to mount 2 are specified with the o option followed by a comma…'

