# mount_apfs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount_apfs.8
complete -c mount_apfs -s o -d 'Options passed to mount 2 are specified with the o option followed by a comma…'
complete -c mount_apfs -s u -d 'Set the owner of the files in the file system to user'
complete -c mount_apfs -s g -d 'Set the group of the files in the file system to group'
complete -c mount_apfs -s s -d 'The name of the snapshot to mount'

