# mount_cd9660
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount_cd9660.8
complete -c mount_cd9660 -s e -d 'Enable the use of extended attributes'
complete -c mount_cd9660 -s g -d 'Do not strip version numbers on files'
complete -c mount_cd9660 -s j -d 'Do not use any Joliet extensions included in the filesystem'
complete -c mount_cd9660 -s o -d 'Options are specified with a o flag followed by a comma separated string of o…'
complete -c mount_cd9660 -s r -d 'Do not use any Rockridge extensions included in the filesystem'
complete -c mount_cd9660 -s s -d 'Start the filesystem at startsector'

