# mount_9p
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount_9p.8
complete -c mount_9p -s r -d 'Mount filesystem as read-only'

