# mount_cddafs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount_cddafs.8
complete -c mount_cddafs -s o -d 'Options are specified with a o flag followed by a comma separated string of o…'

