# mount_udf
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount_udf.8
complete -c mount_udf -s o -d 'Options are specified with a o flag followed by a comma separated string of o…'
complete -c mount_udf -s v -d 'This is an advanced option not useful for regular use'
complete -c mount_udf -s s -d 'This is an advanced option not useful for regular use'
complete -c mount_udf -s n -d 'This is an advanced option not useful for regular use'
complete -c mount_udf -s b -d 'This is an advanced option not useful for regular use'
complete -c mount_udf -s p -d 'This is an advanced option not useful for regular use'
complete -c mount_udf -s w -d 'This is an advanced option not useful for regular use'

