# mount_hfs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount_hfs.8
complete -c mount_hfs -s u -d 'Set the owner of the files in the file system to user'
complete -c mount_hfs -s g -d 'Set the group of the files in the file system to group'
complete -c mount_hfs -s m -d 'Specify the maximum file permissions for files in the file system'
complete -c mount_hfs -s o -d 'Options are specified with a o flag followed by a comma separated string of o…'
complete -c mount_hfs -s j -d 'Ignore the journal for this mount'
complete -c mount_hfs -s c -d 'Disable group commit for journaling'

