# mount_smbfs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount_smbfs.8
complete -c mount_smbfs -s N -d 'Do not ask for a password'
complete -c mount_smbfs -s o -d 'Options passed to mount 2 are specified with the o option followed by a comma…'
complete -c mount_smbfs -s f -d 'Specify permissions that should be assigned to files and directories'
complete -c mount_smbfs -s h -d 'Prints a help message, much like the SYNOPSIS above'
complete -c mount_smbfs -s s -d 'Force a new session to be created to the server'
complete -c mount_smbfs -s t -d 'Do a read only mount using the specific snapshot of the share'
complete -c mount_smbfs -s v -d 'Prints version'

