# mount
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount.8
complete -c mount -s a -d 'All the filesystems listed via getfsent 3 are mounted'
complete -c mount -s d -d 'Causes everything to be done except for the actual system call'
complete -c mount -s f -d 'Forces the revocation of write access when trying to downgrade a filesystem m…'
complete -c mount -s k -d 'In the course of the mount system call, the kernel should not follow any syml…'
complete -c mount -s o -d 'Options are specified with a o flag followed by a comma separated string of o…'
complete -c mount -s r -d 'Mount the file system read-only (even the super-user may not write it)'
complete -c mount -s t -d 'The argument following the t is used to indicate the file system type'
complete -c mount -s u -d 'The u flag indicates that the status of an already mounted file system should…'
complete -c mount -s v -d 'Verbose mode'
complete -c mount -s w -d 'Mount the file system read-write'

