# mount_ftp
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount_ftp.8
complete -c mount_ftp -s i -d 'Interactive mode, you are prompted for the username and password if you did n…'
complete -c mount_ftp -s o -d 'Options passed to mount 2 are specified with the o option followed by a comma…'

