# mount_fdesc
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount_fdesc.8
complete -c mount_fdesc -s o -d 'Options are specified with a o flag followed by a comma separated string of o…'

