# mountd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mountd.8
complete -c mountd -s n
complete -c mountd -s r -d 'exportsfile Ta Fl F Pa exportsfile Ta alternate exports file El Pp However, s…'

