# mount_ntfs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount_ntfs.8
complete -c mount_ntfs -s s -d 'Mount the volume using case sensitive semantics'
complete -c mount_ntfs -s o -d 'Options are specified with a o flag followed by a comma separated string of o…'

