# mount_webdav
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount_webdav.8
complete -c mount_webdav -s s -d 'Require that authentication credentials be sent securely to the server'
complete -c mount_webdav -s S -d 'Suppresses all user interface including the authentication dialogs and the no…'
complete -c mount_webdav -s i -d 'Interactive mode, you are prompted for the username and password'
complete -c mount_webdav -s o -d 'Options passed to mount 2 are specified with the o option followed by a comma…'
complete -c mount_webdav -s v -d 'Allows the volume_name attribute (ATTR_VOL_NAME) returned by getattrlist 2 to…'

