# mount_tmpfs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mount_tmpfs.8
complete -c mount_tmpfs -s o -d 'Options passed to mount 2 are specified with the o option followed by a comma…'
complete -c mount_tmpfs -s i -d 'Make the volume case-insensitive (default)'
complete -c mount_tmpfs -s e -d 'Make the volume case-sensitive'
complete -c mount_tmpfs -s n -d 'Set the maximum number of nodes available to the file system to max_nodes'
complete -c mount_tmpfs -s s -d 'Set the maximum total file system size to max_mem_size bytes, unless suffixed…'

