# natpmpd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/natpmpd.8
complete -c natpmpd -o x/y -d 'The private interfaces that need the use the service.  El NOTES com'

