# nbdst
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/nbdst.8
complete -c nbdst -o recycle -d 'If a shadow file already exists, reset it and use it again'
complete -c nbdst -o preallocate -d 'Set the shadow file to the given size up front'

