# ncdestroy
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ncdestroy.1
complete -c ncdestroy -s h -d 'Print a help summary of the command and then exit'
complete -c ncdestroy -s v -d 'Be verbose and show what file system is being operated on and any resulting e…'
complete -c ncdestroy -s P -d 'If the trailing component resolves to a symbolic link do not resolve the link…'
complete -c ncdestroy -s p -d 'For the init, set and ncdestroy ncinit commands set the principal to principal'
complete -c ncdestroy -s F -d 'For the init, set and ncdestroy ncinit commands to not check the presence of …'

