# ncinit
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ncinit.1
complete -c ncinit -s h -d 'Print a help summary of the command and then exit'
complete -c ncinit -s v -d 'Be verbose and show what file system is being operated on and any resulting e…'
complete -c ncinit -s P -d 'If the trailing component resolves to a symbolic link do not resolve the link…'
complete -c ncinit -s p -d 'For the init, set and ncinit ncinit commands set the principal to principal'
complete -c ncinit -s F -d 'For the init, set and ncinit ncinit commands to not check the presence of the…'

