# ncurses5
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ncurses5.4-config.1
complete -c ncurses5 -l -prefix -d 'Reports package-prefix ncurses5 was installed with'
complete -c ncurses5 -l -exec-prefix -d 'Reports executable-prefix ncurses5 was installed with'
complete -c ncurses5 -l -cflags -d 'Reports C compiler flags needed to compile with ncurses'
complete -c ncurses5 -l -libs -d 'Reports libraries needed to link with ncurses'
complete -c ncurses5 -l -version -d 'Reports release+patchdate version ncurses5 was installed with'
complete -c ncurses5 -l -abi-version -d 'Reports ABI version ncurses5 was installed with'
complete -c ncurses5 -l -mouse-version -d 'Reports mouse-interface version ncurses5 was installed with'
complete -c ncurses5 -l -bindir -d 'Reports directory containing ncurses5 programs'
complete -c ncurses5 -l -datadir -d 'Reports directory containing ncurses5 data'
complete -c ncurses5 -l -libdir -d 'Reports directory containing ncurses5 libraries'
complete -c ncurses5 -l -mandir -d 'Reports directory containing ncurses5 manpages'
complete -c ncurses5 -l -terminfo -d 'Reports $TERMINFO terminfo database path'
complete -c ncurses5 -l -terminfo-dirs -d 'Reports $TERMINFO_DIRS directory list'
complete -c ncurses5 -l -termpath -d 'Reports $TERMPATH termcap list El EXIT STATUS -std'

