# net-snmp-create-v3-user
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/net-snmp-create-v3-user.1
complete -c net-snmp-create-v3-user -l version -d 'displays the net-snmp version number'
complete -c net-snmp-create-v3-user -o ro -d 'create an user with read-only permissions'
complete -c net-snmp-create-v3-user -s a -d 'specify authentication password'
complete -c net-snmp-create-v3-user -s x -d 'specify encryption password'
complete -c net-snmp-create-v3-user -s X -d 'specify encryption algorithm'

