# net-snmp-config
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/net-snmp-config.1
complete -c net-snmp-config -l version -d 'displays the net-snmp version number'
complete -c net-snmp-config -l indent-options -d 'displays the indent options from the Coding Style'
complete -c net-snmp-config -l debug-tokens -d 'displays a example command line to search to source code for a list of availa…'
complete -c net-snmp-config -l create-snmpv3-user -s a -s x -s X -d '[-A MD5|SHA] [username] '
complete -c net-snmp-config -l base-cflags -d 'lists additional compilation flags needed for external applications (excludes…'
complete -c net-snmp-config -l cflags -d 'lists additional compilation flags needed'
complete -c net-snmp-config -l libs -d 'lists libraries needed for building applications'
complete -c net-snmp-config -l agent-libs -d 'lists libraries needed for building subagents'
complete -c net-snmp-config -l netsnmp-libs -d 'lists netsnmp specific libraries'
complete -c net-snmp-config -l external-libs -d 'lists libraries needed by netsnmp libs'
complete -c net-snmp-config -l netsnmp-agent-libs -d 'lists netsnmp specific agent libraries '
complete -c net-snmp-config -l compile-subagent -d '[--ldflags flags] mibmodule1. c [. ]]'
complete -c net-snmp-config -l norm -d 'leave the generated . c file around to read'
complete -c net-snmp-config -l ldflags -d 'extra ld flags to use (e. g.  -L.  -l. )'
complete -c net-snmp-config -l configure-options -d 'Display original configure arguments'
complete -c net-snmp-config -l snmpd-module-list -d 'Display the modules compiled into the agent'
complete -c net-snmp-config -l external-agent-libs
complete -c net-snmp-config -l prefix -d 'Display the installation prefix'

