# netbiosd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/netbiosd.8
complete -c netbiosd -o debug -d 'The service will log extensive debug information and may perform extra diagno…'
complete -c netbiosd -o dump-packets -d 'Pretty-print all sent and received NetBIOS packets to the output log'
complete -c netbiosd -o help -d 'Prints a usage message and exits'
complete -c netbiosd -o max-refresh -d 'Maximum time (in seconds) between searches to refresh the workgroup list'
complete -c netbiosd -o min-refresh -d 'Minimum time (in seconds) between searches to refresh the workgroup list'
complete -c netbiosd -o stdout -d 'Causes netbiosd to print log messages to standard output instead of the syste…'

