# netlog
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/netlog.1
complete -c netlog -s v -d 'Verbose output'
complete -c netlog -s i -d 'Report socket statistics periodically'
complete -c netlog -s I -d 'Used in combination with i, will make netlog exit after the specified number …'
complete -c netlog -s t -d 'Specify the type of interface.  By default, all interfaces will be monitored'
complete -c netlog -s p -d 'Select a process for display'
complete -c netlog -s c -d 'Print details in comma-separated values (CSV) form'
complete -c netlog -s z -d 'Print details even if there was no data transfer on the socket El'

