# nettop
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/nettop.1
complete -c nettop -s m -d 'Specify the mode.  By default, nettop will monitor TCP and UDP sockets'
complete -c nettop -s t -d 'Specify the type of interface.  By default, all interfaces will be monitored'
complete -c nettop -s n -d 'Disable address to name resolution'
complete -c nettop -s c -d 'Less intensive use of the CPU - draws less often'
complete -c nettop -s d -d 'Delta mode'
complete -c nettop -s x -d 'Extended display of numbers instead of human readable suffixes such as MiB'
complete -c nettop -s P -d 'Display per-process summary only, skipping details of open connections'
complete -c nettop -s s -d 'Set the delay between updates to <delay> seconds'
complete -c nettop -s l -d 'Use  logging  mode  and  display  <samples> samples, even if standard output …'
complete -c nettop -s L -d 'Use  logging  mode  and  display  <samples> samples, even if standard output …'
complete -c nettop -s p -d 'Select a process for display'
complete -c nettop -s j -d 'Specifiy a list of column headings to be included in the display'
complete -c nettop -s J -d 'Specifiy a list of column headings that are to be the only ones included in t…'
complete -c nettop -s k -d 'Specifiy a list of column headings to be excluded from the display'

