# networkQuality
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/networkQuality.8
complete -c networkQuality -s C -d 'Use custom configuration URL.  See https://github'
complete -c networkQuality -s I -d 'Bind test to interface (e. g. , en0, pdp_ip0,'
complete -c networkQuality -s c -d 'Produce computer-readable output'
complete -c networkQuality -s h -d 'Show help'
complete -c networkQuality -s s -d 'Run tests sequentially instead of parallel upload/download'
complete -c networkQuality -s v -d 'Verbose output \\" Ends the list Pp SEE ALSO ping 8, traceroute 8'

