# newfs_hfs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/newfs_hfs.8
complete -c newfs_hfs -s N -d 'Causes the file system parameters to be printed out without really creating t…'
complete -c newfs_hfs -s U -d 'Set the owner of the file system\'s root directory to uid'
complete -c newfs_hfs -s G -d 'Set the group of the file system\'s root directory to gid'
complete -c newfs_hfs -s M -d 'Specify the octal access permissions mask for the file system\'s root directory'
complete -c newfs_hfs -s P -d 'Set kHFSContentProtectionBit in the volume\'s attributes, which will cause the…'
complete -c newfs_hfs -s s -d 'Creates a case-sensitive HFS Plus filesystem'
complete -c newfs_hfs -s b -d 'The allocation block size of the file system.  The default value is 4096'
complete -c newfs_hfs -s c -d 'This specifies the clump and/or initial sizes, in allocation blocks, for the …'
complete -c newfs_hfs -s i -d 'This specifies the initial catalog node ID for user files and directories'
complete -c newfs_hfs -s I -d 'This specifies the initial size, in allocation blocks, for the various metada…'
complete -c newfs_hfs -s J -d 'Creates a journaled HFS+ volume'
complete -c newfs_hfs -s D -d 'Creates the journal on special device journal-device'
complete -c newfs_hfs -s n -d 'This specifies the b-tree node sizes, in bytes, for the various b-tree files'
complete -c newfs_hfs -s v -d 'Volume name (file system name) in ascii or UTF-8 format'

