# newfs_exfat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/newfs_exfat.8
complete -c newfs_exfat -s N -d 'Don\'t create a file system: just print out parameters'
complete -c newfs_exfat -s R -d 'Do not check whether the device is currently formatted as ExFAT'
complete -c newfs_exfat -s I -d 'Volume ID, a 32-bit integer'
complete -c newfs_exfat -s S -d 'Number of bytes per sector'
complete -c newfs_exfat -s a -d 'Number of sectors per FAT'
complete -c newfs_exfat -s b -d 'File system block size (bytes per cluster)'
complete -c newfs_exfat -s c -d 'Sectors per cluster'
complete -c newfs_exfat -s n -d 'Number of FATs.   Acceptable values are 1 or 2.   The default is 1'
complete -c newfs_exfat -s s -d 'The total number of sectors in the device'
complete -c newfs_exfat -s v -d 'Volume name (label)'

