# newgrp
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/newgrp.1
complete -c newgrp -s l -d 'Simulate a full login'

