# nfsd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/nfsd.8
complete -c nfsd -s F -d 'The exports_file argument specifies an alternate location for the exports fil…'
complete -c nfsd -s N -d 'Allow non-root mount requests to be served'
complete -c nfsd -s P -d 'Specifies which port to use for the MOUNT service'
complete -c nfsd -s R -d 'Allow mount RPCs requests for regular files to be served'
complete -c nfsd -s n -d 'Specifies how many NFS server threads to create'
complete -c nfsd -s p -d 'Specifies which port to use for the NFS service (instead of the default of 20…'
complete -c nfsd -s r -d 'Register the NFS service with portmap 8'
complete -c nfsd -s t -d 'Serve TCP NFS clients'
complete -c nfsd -s u -d 'Serve UDP NFS clients'
complete -c nfsd -s v -d 'Increase nfsd Ns \'s logging level by one (may be used multiple times)'

