# nfsiod
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/nfsiod.8
complete -c nfsiod -s n -d 'Specify maximum number of asynchronous I/O threads to be used'

