# nfsstat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/nfsstat.1
complete -c nfsstat -s c -d 'Show NFS client statistics'
complete -c nfsstat -s e -d 'Show NFS server exported directory statistics'
complete -c nfsstat -s m -d 'Show NFS mount information'
complete -c nfsstat -s s -d 'Show NFS server statistics'
complete -c nfsstat -s 3 -d 'Print only NFS v3 statistics'
complete -c nfsstat -s 4 -d 'Print only NFS v4 statistics'
complete -c nfsstat -s u -d 'Show NFS server active user statistics'
complete -c nfsstat -s f -d 'Print output as JSON format'
complete -c nfsstat -s w -d 'Display a shorter summary at wait second intervals'
complete -c nfsstat -s n -d 'Show network addresses as numbers, or show users as uid numbers'
complete -c nfsstat -s z -d 'Zero NFS client and server statistics'
complete -c nfsstat -s v -d 'Show additional information (if available)'

