# nice
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/nice.1
complete -c nice -s n -d 'A positive or negative decimal integer used to modify the system scheduling p…'

