# nlcontrol
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/nlcontrol.8
complete -c nlcontrol -o domain -d 'The service will log extensive debug information and may perform extra diagno…'
complete -c nlcontrol -o help -d 'Prints a usage message and exits'
complete -c nlcontrol -o server -d 'The service will listen on each of the TCP ports specified in the comma-separ…'

