# nm
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/nm.1
complete -c nm -s a -d 'Display all symbol table entries, including those inserted for use by debugge…'
complete -c nm -s g -d 'Display only global (external) symbols'
complete -c nm -s n -d 'Sort numerically rather than alphabetically'
complete -c nm -s o -d 'Prepend file or archive element name to each output line, rather than only on…'
complete -c nm -s p -d 'Don\'t sort; display in symbol-table order'
complete -c nm -s r -d 'Sort in reverse order'
complete -c nm -s u -d 'Display only undefined symbols'
complete -c nm -s U -d 'Don\'t display undefined symbols'
complete -c nm -s m -d 'Display the N_SECT type symbols (Mach-O symbols) as '
complete -c nm -s x -d 'Display the symbol table entry\'s fields in hexadecimal, along with the name a…'
complete -c nm -s j -d 'Just display the symbol names (no value or type)'
complete -c nm -s s -d 'List only those symbols in the section  (segname,sectname)'
complete -c nm -s l -d 'List a pseudo symbol  "'
complete -c nm -o arch -d 'Specifies the architecture,  arch_type, of the file for R nm (1) to operate o…'
complete -c nm -s f -d 'For R llvm-nm (1) this specifies the output format'
complete -c nm -s A -d 'Write the pathname or library name of an object on each line'
complete -c nm -s P -d 'Write information in a portable output format'
complete -c nm -s t -d 'For the  -P output, write the numeric value in the specified format'
complete -c nm -s L -d 'as described below'
complete -c nm -l help -d option
complete -c nm -s T -d 'option used on the object, that can be different than the dyld information'

