# nmedit
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/nmedit.1
complete -c nmedit -s s -d 'Leave the symbol table entries for the global symbols listed in  filename glo…'
complete -c nmedit -s R -d 'Change the symbol table entries for the global symbols listed in  filename in…'
complete -c nmedit -s p -d 'Change symbols to private externs instead of static'
complete -c nmedit -s A -d 'Leave all global absolute symbols except those with a value of zero, and save…'
complete -c nmedit -s D -d 'When editing a static library, set the archive\'s SYMDEF file\'s user id, group…'
complete -c nmedit -o arch -d 'Specifies the architecture,  arch_type, of the file for R nmedit (1) to proce…'
complete -c nmedit -s g -d 'option to cc (1)) for the global symbols it changes to static symbols so that…'
complete -c nmedit -s o -d 'Write the result into the file output'

