# notarytool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/notarytool.1
complete -c notarytool -s k -d 'App Store Connect API key.  File system path to the private key'
complete -c notarytool -s d -d 'App Store Connect API Key ID'
complete -c notarytool -s i -d 'App Store Connect API Issuer ID.  The issuer ID is a UUID format string'
complete -c notarytool -l apple-id -d 'The Apple ID login username you use with Developer ID services'
complete -c notarytool -l team-id -d 'The team identifier for the Developer Team to be used with this notarytool su…'
complete -c notarytool -s p -d 'Authenticate using credentials stored in the Keychain by notarytool'
complete -c notarytool -l keychain -d 'Pass the path to a keychain file to use for reading the keychain item specifi…'
complete -c notarytool -l version -d 'Outputs the current version and build number of notarytool'
complete -c notarytool -s v -d 'Enable streaming of DEBUG level logs to stderr'
complete -c notarytool -l progress -d 'Display progress indicators.  Only compatible with normal output formal'
complete -c notarytool -s f -d 'Desired output format'
complete -c notarytool -l validate -d 'Verify that the authentication credentials are valid for use with the Apple n…'
complete -c notarytool -l sync -d 'Make the new profile synchronize and accessible across devices with iCloud Ke…'
complete -c notarytool -l wait -d 'Rather than exiting after a successful upload, begin waiting for your submiss…'
complete -c notarytool -l timeout -d 'If -wait is enabled, notarytool will exit after polling for the specified dur…'
complete -c notarytool -l s3-acceleration -d 'Use S3 Transfer Acceleration for potentially faster uploads'

