# notifyutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/notifyutil.1
complete -c notifyutil -s p -d 'Post a notification for key'
complete -c notifyutil -s w -d 'Register for key and wait forever for notifications'
complete -c notifyutil -s '#' -d 'Register for key and wait for # (an integer) notifications.  "" E. g'
complete -c notifyutil -s g -d 'Get state value for key'
complete -c notifyutil -s s -d 'Set state value for key'
complete -c notifyutil -o port -d 'Use mach port notifications for subsequent w or # registrations'
complete -c notifyutil -o file -d 'Use file descriptor notifications for subsequent registrations'
complete -c notifyutil -o check -d 'Use shared memory notifications for subsequent registrations'
complete -c notifyutil -o signal -d 'Use signal notifications for subsequent registrations'
complete -c notifyutil -o dispatch -d 'Use dispatch for subsequent registrations'

