# nroff
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/nroff.1
complete -c nroff -s T -d 'option, selecting the output encoding emitted by grotty , groff\'s TTY output …'
complete -c nroff -s h -d and
complete -c nroff -s c -d 'options are equivalent to grotty \'s options'
complete -c nroff -s d
complete -c nroff -s C
complete -c nroff -s i
complete -c nroff -s M
complete -c nroff -s m
complete -c nroff -s n
complete -c nroff -s o -d and
complete -c nroff -s r -d 'options have the effect described in troff (1)'
complete -c nroff -s e
complete -c nroff -s q -d and
complete -c nroff -s s -d '(which are not implemented in troff ).  Options '
complete -c nroff -s p -d '(pic),'
complete -c nroff -s t -d '(tbl),'
complete -c nroff -s S -d '(safer), and'
complete -c nroff -s U -d '(unsafe) are passed to groff '
complete -c nroff -s v -d 'shows the version number'

