# nslookup
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/nslookup.1
complete -c nslookup -o version -d 'option causes nslookup to print the version number and immediately exits'

