# nsupdate
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/nsupdate.1
complete -c nsupdate -s d -d 'Debug mode'
complete -c nsupdate -s D -d 'Extra debug mode'
complete -c nsupdate -s k -d 'The file containing the TSIG authentication key'
complete -c nsupdate -s l -d 'Local-host only mode'
complete -c nsupdate -s L -d 'Set the logging debug level.  If zero, logging is disabled'
complete -c nsupdate -s p -d 'Set the port to use for connections to a name server.  The default is 53'
complete -c nsupdate -s P -d 'Print the list of private BIND-specific resource record types whose format is…'
complete -c nsupdate -s r -d 'The number of UDP retries.  The default is 3'
complete -c nsupdate -s R -d 'Where to obtain randomness'
complete -c nsupdate -s t -d 'The maximum time an update request can take before it is aborted'
complete -c nsupdate -s T -d 'Print the list of IANA standard resource record types whose format is underst…'
complete -c nsupdate -s u -d 'The UDP retry interval.  The default is 3 seconds'
complete -c nsupdate -s v -d 'Use TCP even for small update requests'
complete -c nsupdate -s V -d 'Print the version number and exit'
complete -c nsupdate -s y -d 'Literal TSIG authentication key'
complete -c nsupdate -s g -d flag
complete -c nsupdate -s o -d 'flag.  OPTIONS'

