# nvram
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/nvram.8
complete -c nvram -s d -d 'Deletes the named firmware variable'
complete -c nvram -s f -d 'Set firmware variables from a text file'
complete -c nvram -s x -d 'Use XML format for reading and writing variables'
complete -c nvram -s c -d 'Delete all of the firmware variables'
complete -c nvram -s p -d 'Print all of the firmware variables'

