# osacompile
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/osacompile.1
complete -c osacompile -s l -d 'Override the language for any plain text files'
complete -c osacompile -s e -d 'Enter one line of a script'
complete -c osacompile -s o -d 'Place the output in the file name'
complete -c osacompile -s x -d 'Save the resulting script as execute-only'
complete -c osacompile -s s -d 'Stay-open applet'
complete -c osacompile -s u -d 'Use startup screen'
complete -c osacompile -s d -d 'Place the resulting script in the data fork of the output file'
complete -c osacompile -s r -d 'Place the resulting script in the resource fork of the output file, in the sp…'
complete -c osacompile -s t -d 'Set the output file type to type, where type is a four-character code'
complete -c osacompile -s c -d 'Set the output file creator to creator, where creator is a four-character code'

