# osalang
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/osalang.1
complete -c osalang -s d -d 'Only print the default language'
complete -c osalang -s l -d 'List in long format'
complete -c osalang -s L -d 'Same as l, but also prints the description of each component after its name'

