# osascript
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/osascript.1
complete -c osascript -s e -d 'Enter one line of a script'
complete -c osascript -s i -d 'Interactive mode: osascript will prompt for one line at a time, and print the…'
complete -c osascript -s l -d 'Override the language for any plain text files'
complete -c osascript -s s -d 'Modify the output style'

