# pagestuff
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/pagestuff.1
complete -c pagestuff -o arch -d 'Specifies the architecture,  arch_type, of the file for  pagestuff to operate…'
complete -c pagestuff -o pagesize -d 'Specifies the page size to use when computing logical page boundaries'
complete -c pagestuff -s a -d 'Display all pages in the file'
complete -c pagestuff -s p -d 'Print a list of the sections of the specified file, offsets and lengths'

