# passwd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/passwd.1
complete -c passwd -s i -d 'This option specifies where the password update should be applied'
complete -c passwd -s l -d 'This option causes the password to be updated in the given location of the ch…'
complete -c passwd -s u -d 'This option specifies the user name to use when authenticating to the directo…'

