# PasswordService
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/PasswordService.8
complete -c PasswordService -s n -d 'Do not daemonize'

