# patch
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/patch.1
complete -c patch -s b -d 'Make backup files'
complete -c patch -s B -d 'Prefix  pref to a file name when generating its simple backup file name'
complete -c patch -s c -d 'Interpret the patch file as a ordinary context diff'
complete -c patch -s d -d 'Change to the directory  dir immediately, before doing anything else'
complete -c patch -s D -d 'Use the  #ifdef " . \\|. \\|'
complete -c patch -s e -d 'Interpret the patch file as an  ed script'
complete -c patch -s E -d 'Remove output files that are empty after the patches have been applied'
complete -c patch -s f -d 'Assume that the user knows exactly what he or she is doing, and do not ask an…'
complete -c patch -s F -d 'Set the maximum fuzz factor'
complete -c patch -s g -d 'This option controls  patch \'s actions when a file is under \\s-1RCS\\s0 or \\s-…'
complete -c patch -s i -d 'Read the patch from R patchfile '
complete -c patch -s l -d 'Match patterns loosely, in case tabs or spaces have been munged in your files'
complete -c patch -s n -d 'Interpret the patch file as a normal diff'
complete -c patch -s N -d 'Ignore patches that seem to be reversed or already applied.  See also  -R '
complete -c patch -s o -d 'Send output to  outfile instead of patching files in place'
complete -c patch -o pnum -d 'Strip the smallest prefix containing  num leading slashes from each file name…'
complete -c patch -s r -d 'Put rejects into  rejectfile instead of the default  . rej file'
complete -c patch -s R -d 'Assume that this patch was created with the old and new files swapped'
complete -c patch -s s -d 'Work silently, unless an error occurs'
complete -c patch -s t -d 'Suppress questions like  -f , but make some different assumptions: skip patch…'
complete -c patch -s T -d 'Set the modification and access times of patched files from time stamps given…'
complete -c patch -s u -d 'Interpret the patch file as a unified context diff'
complete -c patch -s v -d 'Print out  patch \'s revision header and patch level, and exit'
complete -c patch -s V -d 'Use  method to determine backup file names'
complete -c patch -s x -d 'Set internal debugging flags of interest only to  patch patchers'
complete -c patch -s Y -d 'Prefix  pref to the basename of a file name when generating its simple backup…'
complete -c patch -s z -d 'Use  suffix as the simple backup suffix'
complete -c patch -l option -d 'The names of the files to be patched are usually taken from the patch file, b…'
complete -c patch -l -e -l -n -l or
complete -c patch -s p -d or
complete -c patch -l Make -d 'That is, when patching a file, rename or copy the original instead of removin…'
complete -c patch -l Back -d 'and if backups are not otherwise requested'
complete -c patch -l Do -d 'and if backups are not otherwise requested'
complete -c patch -l Prefix -d 'pref to a file name when generating its simple backup file name'
complete -c patch -l Read -d 'except for standard output and /dev/tty '
complete -c patch -l Interpret
complete -c patch -l Change -d 'dir immediately, before doing anything else'
complete -c patch -l Use -d '#ifdef  '
complete -c patch -l Print
complete -c patch -l Remove -d 'Normally this option is unnecessary, since patch can examine the time stamps …'
complete -c patch -l Assume -d 'ask any questions'
complete -c patch -l Set -d 'This option only applies to diffs that have context, and causes patch to igno…'
complete -c patch -l This -d 'patch \'s actions when a file is under RCS or SCCS control, and does not exist…'
complete -c patch -l Match -d 'have been munged in your files'
complete -c patch -l Ignore -d 'See also'
complete -c patch -l Send -d 'outfile instead of patching files in place'
complete -c patch -l Strip -d 'num leading slashes from each file name found in the patch file'
complete -c patch -o p0 -d 'gives the entire file name unmodified,'
complete -c patch -o p1 -d gives
complete -c patch -o p4 -d gives
complete -c patch -l Conform -d ' o Take the first existing file from the list (old, new, index) when intuitin…'
complete -c patch -l Put -d 'rejectfile instead of the default . rej file'
complete -c patch -l Work
complete -c patch -l Suppress
complete -c patch -s Z -d or
complete -c patch -l -Y -d or
complete -c patch -l and
complete -c patch -l options -d 'If none of these options are given, then a simple backup suffix is used; it i…'
complete -c patch -l Output
complete -c patch -o Np1 -d 'is recommended'

