# pbs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/pbs.8
complete -c pbs -o debug -d 'Output debugging information regarding what pbs is doing'
complete -c pbs -o dump -d 'Prints the userdef cache of Services information'
complete -c pbs -o read_bundle -d 'Prints the Services information for the given application or service bundle'
complete -c pbs -o flush -d 'Erases the userdef cache, entirely resetting pbs'
complete -c pbs -o update -d 'Updates the userdef cache'

