# pdisk
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/pdisk.8
complete -c pdisk -s a
complete -c pdisk -l abbr -d 'Abbreviate the partition types shown in the partition list'
complete -c pdisk -s c
complete -c pdisk -l compute_size -d 'Causes pdisk to always ignore the device size listed in the partition table a…'
complete -c pdisk -s d
complete -c pdisk -l debug -d 'Turns on debugging'
complete -c pdisk -s f
complete -c pdisk -l fname -d 'Show HFS volume names instead of partition name when available'
complete -c pdisk -s h
complete -c pdisk -l help -d 'Prints a short help message'
complete -c pdisk -s i
complete -c pdisk -l interactive -d 'Causes pdisk to go into an interactive mode similar to the MacOS version of t…'
complete -c pdisk -s l
complete -c pdisk -l list -d 'If no device argument is given, pdisk tries to list partition tables for all …'
complete -c pdisk -s L
complete -c pdisk -l logical -d 'Show partition limits in logical blocks.  Default is physical blocks'
complete -c pdisk -s r
complete -c pdisk -l readonly -d 'Prevents pdisk from writing to the device'
complete -c pdisk -s v
complete -c pdisk -l version -d 'Prints the version number of pdisk'

