# pfbtops
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/pfbtops.1
complete -c pfbtops -s v -d 'Print the version number.  SEE ALSO grops (1)'

