# pkreporter
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/pkreporter.8
complete -c pkreporter -s v -d 'Enable verbose output'

