# PlistBuddy
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/PlistBuddy.8
complete -c PlistBuddy -s c -d 'Execute command and exit'
complete -c PlistBuddy -s x -d 'Output will be in the form of an xml plist where appropriate'
complete -c PlistBuddy -s h -d 'Print the complete help info'

