# plockstat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/plockstat.1
complete -c plockstat -s v -d 'print a message when tracing starts'
complete -c plockstat -s A -d 'trace contention and hold events (same as -CH)'
complete -c plockstat -s C -d 'trace contention events for mutexes and rwlocks'
complete -c plockstat -s H -d 'trace hold events for mutexes and rwlocks'
complete -c plockstat -s V -d 'print the dtrace script to run'
complete -c plockstat -s n -d 'display only \'count\' entries for each event type'
complete -c plockstat -s s -d 'show stack trace upto \'depth\' entries'
complete -c plockstat -s e -d 'exit after specified seconds'
complete -c plockstat -s x -d 'enable a DTrace runtime option or a D compiler option'
complete -c plockstat -s p -d 'attach and trace the specified process id SEE ALSO dtrace(1)'

