# pluginkit
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/pluginkit.8
complete -c pluginkit -s A -d 'Matches find all versions of a given plug-in known to the system'
complete -c pluginkit -s a -d 'Explicitly adds plugins at the file location(s) given, even if they are not n…'
complete -c pluginkit -s e -d 'Perform a matching operation (see -m) and apply the given user election setti…'
complete -c pluginkit -s D -d 'Matches find all physical instances of a given plug-in known to the system, e…'
complete -c pluginkit -s i -d 'Specifies a plug-in identifier to match, a short-hand for NSExtensionIdentifi…'
complete -c pluginkit -s m -d 'Requests pluginkit to scan all registered plug-ins for those matching the giv…'
complete -c pluginkit -s p -d 'Specifies a plug-in protocol to  match, a short-hand for NSExtensionPointName…'
complete -c pluginkit -s r -d 'Explicitly removes plugins at the file location(s) given'
complete -c pluginkit -l raw -d 'Present replies from the management daemon (pkd) in raw XML form'
complete -c pluginkit -s v -d 'Asks for more verbose operation'

