# pod2text5
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/pod2text5.30.1
complete -c pod2text5 -l errors -d 'Set the error handling style'

