# postsuper
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/postsuper.1
complete -c postsuper -s s -s p -d 'directories - this includes the incoming, active and deferred directories wit…'
complete -c postsuper -s c -d 'The main'
complete -c postsuper -s d -d 'Delete one message with the named queue ID from the named mail queue(s) (defa…'
complete -c postsuper -s h -d 'Put mail "on hold" so that no attempt is made to deliver it'
complete -c postsuper -s H -d 'Release mail that was put "on hold"'
complete -c postsuper -s r -d 'Requeue the message with the named queue ID from the named mail queue(s) (def…'
complete -c postsuper -s S -d 'A redundant version of -s that requires that long file names also match the m…'
complete -c postsuper -s v -d 'Enable verbose logging for debugging purposes'

