# postlock
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/postlock.1
complete -c postlock -s c -d 'Read the main'
complete -c postlock -s l -d 'Override the locking method specified via the mailbox_delivery_lock configura…'
complete -c postlock -s v -d 'Enable verbose logging for debugging purposes'

