# postkick
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/postkick.1
complete -c postkick -s c -d 'Read the main'
complete -c postkick -s v -d 'Enable verbose logging for debugging purposes'

