# postlog
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/postlog.1
complete -c postlog -s c -d 'Read the main'
complete -c postlog -s i -d 'Include the process ID in the logging tag'
complete -c postlog -s p -d 'Specifies the logging severity: info, warn, error, fatal, or panic'
complete -c postlog -s t -d 'Specifies the logging tag, that is, the identifying name that appears at the …'
complete -c postlog -s v -d 'Enable verbose logging for debugging purposes'

