# postconf
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/postconf.1
complete -c postconf -s a -d 'List the available SASL plug-in types for the Postfix SMTP server'
complete -c postconf -s A -d 'List the available SASL plug-in types for the Postfix SMTP client'
complete -c postconf -s b -d 'Display the message text that appears at the beginning of delivery status not…'
complete -c postconf -s c -d 'The main'
complete -c postconf -s C -d 'When displaying main'
complete -c postconf -s d -d 'Print main. cf default parameter settings instead of actual settings'
complete -c postconf -s e -d 'Edit the main'
complete -c postconf -s f -d 'Fold long lines when printing main. cf or master'
complete -c postconf -s F -d 'Show master'
complete -c postconf -o Ff
complete -c postconf -s h -d 'Show parameter or attribute values without the "name = " label that normally …'
complete -c postconf -s H -d 'Show parameter or attribute names without the " = value" that normally follow…'
complete -c postconf -s l -d 'List the names of all supported mailbox locking methods'
complete -c postconf -s m -d 'List the names of all supported lookup table types'
complete -c postconf -s M -d 'Show master. cf file contents instead of main. cf file contents'
complete -c postconf -s n -d 'Show only configuration parameters that have explicit name=value settings in …'
complete -c postconf -s o -d 'Override main. cf parameter settings'
complete -c postconf -s p -d 'Show main. cf parameter settings.  This is the default'
complete -c postconf -s P -d 'Show master'
complete -c postconf -o Pf
complete -c postconf -s t -d 'Display the templates for text that appears at the beginning of delivery stat…'
complete -c postconf -s T -d 'If Postfix is compiled without TLS support, the -T option produces no output'
complete -c postconf -s v -d 'Enable verbose logging for debugging purposes.  Multiple'
complete -c postconf -s x -d 'Expand $name in main. cf or master. cf parameter values'
complete -c postconf -s X -d 'Edit the main'
complete -c postconf -s '#' -d 'Edit the main'

