# postalias
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/postalias.1
complete -c postalias -s c -d 'Read the main'
complete -c postalias -s d -d 'Search the specified maps for key and remove one entry per map'
complete -c postalias -s f -d 'Do not fold the lookup key to lower case while creating or querying a table'
complete -c postalias -s i -d 'Incremental mode'
complete -c postalias -s N -d 'Include the terminating null character that terminates lookup keys and values'
complete -c postalias -s n -d 'Don\'t include the terminating null character that terminates lookup keys and …'
complete -c postalias -s o -d 'Do not release root privileges when processing a non-root input file'
complete -c postalias -s p -d 'Do not inherit the file access permissions from the input file when creating …'
complete -c postalias -s q -d 'Search the specified maps for key and write the first value found to the stan…'
complete -c postalias -s r -d 'When updating a table, do not complain about attempts to update existing entr…'
complete -c postalias -s s -d 'Retrieve all database elements, and write one line of key: value output for e…'
complete -c postalias -s u -d 'Disable UTF-8 support'
complete -c postalias -s v -d 'Enable verbose logging for debugging purposes'
complete -c postalias -s w -d 'When updating a table, do not complain about attempts to update existing entr…'

