# postcat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/postcat.1
complete -c postcat -s b -d 'Show body content'
complete -c postcat -s c -d 'The main'
complete -c postcat -s d -d 'Print the decimal type of each record'
complete -c postcat -s e -d 'Show message envelope content'
complete -c postcat -s h -d 'Show message header content'
complete -c postcat -s o -d 'Print the queue file offset of each record'
complete -c postcat -s q -d 'Search the Postfix queue for the named files instead of taking the names lite…'
complete -c postcat -s v -d 'Enable verbose logging for debugging purposes'

