# postdrop
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/postdrop.1
complete -c postdrop -s c -d 'The main'
complete -c postdrop -s r -d 'Use a Postfix-internal protocol for reading the message from standard input, …'
complete -c postdrop -s v -d 'Enable verbose logging for debugging purposes'

