# postmulti
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/postmulti.1
complete -c postmulti -s a -d 'Perform the operation on all instances.  This is the default'
complete -c postmulti -s g -d 'Perform the operation only for members of the named group'
complete -c postmulti -s i -d 'Perform the operation only for the instance with the specified name'
complete -c postmulti -s R -d 'Reverse the iteration order'
complete -c postmulti -s l -d 'List Postfix instances with their instance name, instance group name, enable/…'
complete -c postmulti -s p -d 'Invoke postfix(1) to execute postfix-command'
complete -c postmulti -s x -d 'Execute the specified unix-command for all Postfix instances'
complete -c postmulti -s v -d 'Enable verbose logging for debugging purposes.  Multiple'
complete -c postmulti -s I -d 'Assign the specified instance name to an existing instance, newly-created ins…'
complete -c postmulti -s G -d 'Assign the specified group name to an existing instance or to a newly created…'
complete -c postmulti -s e -d '"Edit" managed instances.  The following actions are supported:'

