# postfix
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/postfix.1
complete -c postfix -s c -d 'Read the main. cf and master'
complete -c postfix -s D -d 'Run each Postfix daemon under control of a debugger as specified via the debu…'
complete -c postfix -s v -d 'Enable verbose logging for debugging purposes'

