# postqueue
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/postqueue.1
complete -c postqueue -s c -d 'The main'
complete -c postqueue -s f -d 'Flush the queue: attempt to deliver all queued mail'
complete -c postqueue -s i -d 'Schedule immediate delivery of deferred mail with the specified queue ID'
complete -c postqueue -s j -d 'Produce a queue listing in JSON format, based on output from the showq(8) dae…'
complete -c postqueue -s p -d 'Produce a traditional sendmail-style queue listing'
complete -c postqueue -s s -d 'Schedule immediate delivery of all mail that is queued for the named site'
complete -c postqueue -s v -d 'Enable verbose logging for debugging purposes'

