# ppdi
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ppdi.1
complete -c ppdi -s I -d 'Specifies an alternate include directory'
complete -c ppdi -s o -d 'Specifies the PPD source file to update'

