# ppdmerge
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ppdmerge.1
complete -c ppdmerge -s o -d 'Specifies the PPD file to create'

