# printtool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/printtool.8
complete -c printtool -l reset -d 'Reset the printing system'
complete -c printtool -s f -d 'Do not prompt for confirmation El FILES -tag -width indent -compact /System/L…'

