# psed
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/psed.1
complete -c psed -s a -d 'A file specified as argument to the w edit command is by default opened befor…'
complete -c psed -s e -d 'The editing commands defined by script are appended to the script'
complete -c psed -s f -d 'Editing commands from the specified script-file are read and appended to the …'

