# psm
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/psm.1
complete -c psm -s d -d 'specify a disk to operate on <disk3s5>'
complete -c psm -s s -d 'specify a specifc slot number'
complete -c psm -s v -d 'will make psm more verbose'

