# pstopdf
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/pstopdf.1
complete -c pstopdf -s o -d 'The name of the output file to create'
complete -c pstopdf -s l -d 'Specifies that any messages generated during file conversion be written to a …'
complete -c pstopdf -s p -d 'Generates a simple progress message to stdout at the end of each page'

