# ptargrep
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ptargrep.1
complete -c ptargrep -l basename -s b -d 'When matching files are extracted, ignore the directory path from the archive…'
complete -c ptargrep -l ignore-case -s i -d 'Make pattern matching case-insensitive'
complete -c ptargrep -l list-only -s l -d 'Print the pathname of each matching file from the archive to \\s-1STDOUT'
complete -c ptargrep -l verbose -s v -d 'Log debugging info to \\s-1STDERR. \\s0'

