# pwd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/pwd.1
complete -c pwd -s L -d 'Display the logical current working directory'
complete -c pwd -s P -d 'Display the physical current working directory (all symbolic links resolved)'

