# pwd_mkdb
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/pwd_mkdb.8
complete -c pwd_mkdb -s c -d 'Check if the password file is in the correct format'
complete -c pwd_mkdb -s d -d 'Operate in a base directory other than the default of /etc'
complete -c pwd_mkdb -s p -d 'Create a Version 7 style password file and install it into /etc/passwd'
complete -c pwd_mkdb -s s -d 'Only update the secure version of the database'
complete -c pwd_mkdb -s u -d 'Only update the record for the specified user'

