# quotacheck
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/quotacheck.8
complete -c quotacheck -s a -d 'If the a flag is supplied in place of any filesystem names, quotacheck quotac…'
complete -c quotacheck -s g -d 'Only group quotas are checked.  The mount option file, . quota. ops'
complete -c quotacheck -s u -d 'Only user quotas are checked.   The mount option file, . quota. ops'
complete -c quotacheck -s v -d 'quotacheck quotacheck reports discrepancies between the calculated and record…'

