# quotaon
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/quotaon.8
complete -c quotaon -s a -d 'If the a flag is supplied in place of any filesystem names, quotaon quotaon N…'
complete -c quotaon -s g -d 'Only group quotas will be enabled/disabled.  The mount option file, . quota'
complete -c quotaon -s u -d 'Only user quotas will be enabled/disabled.  The mount option file, . quota'
complete -c quotaon -s v -d 'Causes quotaon quotaon and quotaon quotaoff to print a message for each files…'

