# quota
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/quota.1
complete -c quota -s g -d 'Print group quotas for the group of which the user is a member'
complete -c quota -s v -d 'quota quota will display quotas on filesystems where no storage is allocated'
complete -c quota -s q -d 'Print a more terse message, containing only information on filesystems where …'

