# racoon
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/racoon.8
complete -c racoon -s 4
complete -c racoon -s 6 -d 'Specify the default address family for the sockets'
complete -c racoon -s B -d 'Install SA(s) from the file which is specified in racoon. conf 5'
complete -c racoon -s d -d 'Increase the debug level'
complete -c racoon -s F -d 'Run racoon in the foreground'
complete -c racoon -s f -d 'Use configfile as the configuration file instead of the default'
complete -c racoon -s L -d 'Include file_name:line_number:function_name in all messages'
complete -c racoon -s l -d 'Use logfile as the logging file instead of syslogd 8'
complete -c racoon -s v -d 'This flag causes the packet dump be more verbose, with higher debugging level'

