# reboot
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/reboot.8
complete -c reboot -s l -d 'The halt or reboot is not recorded in the system log'
complete -c reboot -s n -d 'The file system cache is not flushed'
complete -c reboot -s q -d 'The system is halted or restarted quickly and ungracefully, and only the flus…'
complete -c reboot -s u -d 'The system is halted up until the point of removing system power, but waits b…'

