# remindd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/remindd.8
complete -c remindd -s a -d 'Description of -a flag'
complete -c remindd -s b -d 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

