# renice
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/renice.8
complete -c renice -s g -d 'Force who parameters to be interpreted as process group ID\'s'
complete -c renice -s n -d 'Instead of changing the specified processes to the given priority, interpret …'
complete -c renice -s u -d 'Force the who parameters to be interpreted as user names or user ID\'s'
complete -c renice -s p -d 'Reset the who interpretation to be (the default) process ID\'s'

