# repquota
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/repquota.8
complete -c repquota -s a -d 'Print the quotas of all the filesystems configured with a quota mount option …'
complete -c repquota -s g -d 'Print only group quotas (the default is to print both group and user quotas i…'
complete -c repquota -s u -d 'Print only user quotas (the default is to print both group and user quotas if…'
complete -c repquota -s v -d 'Print a header line before printing each filesystem quotas'

