# ResMerger
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/ResMerger.1
complete -c ResMerger -o fileCreator -d 'Sets the HFS creator type of the output file.   The default is \'????\''
complete -c ResMerger -o fileType -d 'Sets the HFS file type of the output file.   The default is \'????\''
complete -c ResMerger -o ppend -d 'Append to output file, rather than overwriting it'
complete -c ResMerger -o srcIs -d 'The fork in which to look for resources in the input file(s)'
complete -c ResMerger -o dstIs -d 'The fork in which to write resources in the output file'
complete -c ResMerger -o skip -d 'Specifies resource type to skip during the resource merge'
complete -c ResMerger -s o -d 'Specifies the output file'

