# rmiregistry
# Autogenerated from man page /opt/homebrew/opt/openjdk/share/man/man1/rmiregistry.1
complete -c rmiregistry -o Joption -d 'Used with any Java option to pass the option following the'
complete -c rmiregistry -s J -s J -d 'Java interpreter'

