# rotatelogs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/rotatelogs.8
complete -c rotatelogs -s l -d 'Causes the use of local time rather than GMT as the base for the interval or …'
complete -c rotatelogs -s L -d 'PP Causes a hard link to be made from the current logfile to the specified li…'
complete -c rotatelogs -s p -d 'If given, rotatelogs will execute the specified program every time a new log …'
complete -c rotatelogs -s f -d 'Causes the logfile to be opened immediately, as soon as rotatelogs starts, in…'
complete -c rotatelogs -s D -d 'Creates the parent directories of the path that the log file will be placed i…'
complete -c rotatelogs -s t -d 'Causes the logfile to be truncated instead of rotated'
complete -c rotatelogs -s v -d 'Produce verbose output on STDERR'
complete -c rotatelogs -s e -d 'Echo logs through to stdout'
complete -c rotatelogs -s c -d 'Create log file for each interval, even if empty'
complete -c rotatelogs -s n -d 'Use a circular list of filenames without timestamps'

