# route
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/route.8
complete -c route -s d -d 'Run in debug-only mode, i. e. , do not actually modify the routing table'
complete -c route -s n -d 'Bypass attempts to print host and network names symbolically when reporting a…'
complete -c route -s t -d 'Run in test-only mode.  /dev/null is used instead of a socket'
complete -c route -s v -d '(verbose) Print additional details'
complete -c route -s q -d 'Suppress all output'

