# rpcbind
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/rpcbind.8
complete -c rpcbind -s d -d 'causes rpcbind errors and debugging information to be printed to the standard…'
complete -c rpcbind -s v -d 'Enable verbose logging of access control checks'
complete -c rpcbind -s h -d 'Specify specific IP addresses to bind to for UDP requests'

