# rpcsvchost
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/rpcsvchost.8
complete -c rpcsvchost -o debug -d 'rpcsvchost will log debug information and may perform extra diagnostic checks'
complete -c rpcsvchost -o endpoints -d 'This argument specifies additional endpoints that rpcsvchost should attempt t…'
complete -c rpcsvchost -o help -d 'Prints a usage message and exits'
complete -c rpcsvchost -o launchd -d 'Normally, rpcsvchost attempts to bind all the well-known endpoints specified …'
complete -c rpcsvchost -o sandbox -d 'When this option is specified, the modules loaded by rpcsvchost will be run i…'
complete -c rpcsvchost -o register -d 'When this option is specified, rpcsvchost attempts to register the loaded ser…'
complete -c rpcsvchost -o stdout -d 'Causes rpcsvchost to print log messages to standard output instead of the sys…'
complete -c rpcsvchost -o wait-for-debugger -d 'Causes rpcsvchost to wait for a debugger to attach after it has loaded and in…'

