# rtadvd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/rtadvd.8
complete -c rtadvd -s c -d 'Specify an alternate location, configfile, for the configuration file'
complete -c rtadvd -s d -d 'Print debugging information'
complete -c rtadvd -s D -d 'Even more debugging information is printed'
complete -c rtadvd -s f -d 'This option is now deprecated and ignored'
complete -c rtadvd -s F -d 'Specify an alternative file in which to dump internal states when rtadvd rece…'
complete -c rtadvd -s M -d 'Specify an interface to join the all-routers site-local multicast group'
complete -c rtadvd -s p -d 'Specify an alternative file in which to store the process ID'
complete -c rtadvd -s R -d 'Accept router renumbering requests'
complete -c rtadvd -s s -d 'Do not add or delete prefixes dynamically'

