# sandbox-exec
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/sandbox-exec.1
complete -c sandbox-exec -s f -d 'Read the profile from the file named profile-file'
complete -c sandbox-exec -s n -d 'Use the pre-defined profile profile-name'
complete -c sandbox-exec -s p -d 'Specify the profile to be used on the command line'
complete -c sandbox-exec -s D -d 'Set the profile parameter key to value'

