# sandboxd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/sandboxd.8
complete -c sandboxd -s b -d 'Just log basic sandbox violation information without a backtrace'
complete -c sandboxd -s s -d 'Do not symbolicate backtraces'

