# sc_auth
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/sc_auth.8
complete -c sc_auth -s u -d 'Specifies the user whose account is to be modified'
complete -c sc_auth -s d -d 'Specifies the directory domain containing the user account'
complete -c sc_auth -s k -d 'Specifies a public key by its name'
complete -c sc_auth -s h -d 'Specifies a public key by its hash'
complete -c sc_auth -s v -d 'Verbose mode'
complete -c sc_auth -s f -d 'Force to display pairing dialog'
complete -c sc_auth -s t -d 'Specifies a token by tokenID'
complete -c sc_auth -s c -d 'Specifies a token by  \'com. apple. ctk. class-id\' from Info. plist'
complete -c sc_auth -s p -d 'Specifies a PIN'
complete -c sc_auth -s o -d 'Use status to query the status of SmartCard support for FileVault unlock for …'

