# sc_usage
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/sc_usage.1
complete -c sc_usage -s c -d 'When the c option is specified, it expects a path to a codefile that contains…'
complete -c sc_usage -s e -d 'Specifying the e option generates output that is sorted by call count'
complete -c sc_usage -s l -d 'The l option causes sc_usage sc_usage to turn off its continuous window updat…'
complete -c sc_usage -s s -d 'By default, sc_usage sc_usage updates its output at one second intervals'

