# scselect
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/scselect.8
complete -c scselect -s n -d 'Delay changing the system\'s location until the next system boot (or the next …'

