# scutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/scutil.8
complete -c scutil -s r -d 'Check the network reachability of the specified host name, IP address, or a p…'
complete -c scutil -s w -d 'Check if the specified key exists in the dynamic store data maintained by con…'
complete -c scutil -l get -d 'Retrieves the specified preference'
complete -c scutil -l set -d 'Updates the specified preference with the new value'
complete -c scutil -l dns -d 'Reports the current DNS configuration'
complete -c scutil -l proxy -d 'Reports the current proxy configuration'
complete -c scutil -l nc -d 'Provides a set of commands for monitoring and interacting with VPN connections'

