# sdp
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/sdp.1
complete -c sdp -s f -d 'Specify the output format.   The format may be one or more of the following'
complete -c sdp -s o -d 'Specify where to write the output'
complete -c sdp -s A -d 'Output definitions even for items the scripting definition marks as hidden'
complete -c sdp -s V -d 'Specify the minimum compatible system version for the output, for example, -V…'
complete -c sdp -s N -d 'Em Bo Objective-C -fh only Bc Ef Specify the base name'
complete -c sdp -s i -d 'Include the type and class definitions from the specified sdef'

