# segedit
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/segedit.1
complete -c segedit -o extract -d 'Extracts each section specified by the segment and section names and places t…'
complete -c segedit -o replace -d 'Replaces each section specified by the segment and section names and takes th…'
complete -c segedit -o sectcreate -d option
complete -c segedit -s l -d 'option to otool (1)'
complete -c segedit -o output -d 'option must also be specified'

