# SetFile
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/SetFile.1
complete -c SetFile -s P -d 'Acts on a symlink file instead on the file the symlink resolves to'
complete -c SetFile -s a -d 'Sets the file attributes bits where attributes is a string of case sensitive …'
complete -c SetFile -s c -d 'Specifies the file\'s creator, where creator can be a string of four MacRoman …'
complete -c SetFile -s d -d 'Sets the creation date, where date is a string of the form: "mm/dd/[yy]yy [hh…'
complete -c SetFile -s m -d 'Sets the modification date where date is a string of the form in d above'
complete -c SetFile -s t -d 'Sets the file type, where type can be a string of four MacRoman characters, a…'

