# setkey
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/setkey.8
complete -c setkey -s '?' -d 'Print short help'
complete -c setkey -s a -d 'setkey usually does not display dead SAD entries with D'
complete -c setkey -s D -d 'Dump the SAD entries.  If P is also specified, the SPD entries are dumped'
complete -c setkey -s F -d 'Flush the SAD entries.  If P is also specified, the SPD entries are flushed'
complete -c setkey -s H -d 'Add hexadecimal dump in x mode'
complete -c setkey -s h -d 'On , synonym for H.  On other systems, synonym for ?'
complete -c setkey -s k -d 'Use semantics used in kernel.  Available only in Linux.  See also r'
complete -c setkey -s l -d 'Loop forever with short output on D'
complete -c setkey -s n -d 'No action'
complete -c setkey -s r -d 'Use semantics described in IPsec RFCs.  This mode is default'
complete -c setkey -s x -d 'Loop forever and dump all the messages transmitted to the PF_KEY socket'
complete -c setkey -s V -d 'Print version string'
complete -c setkey -s v -d 'Be verbose'
complete -c setkey -s m -d 'Specify a security protocol mode for use'
complete -c setkey -s u -d 'Specify the identifier of the policy entry in the SPD.  See policy'
complete -c setkey -s f -d 'defines the content of the ESP padding'
complete -c setkey -o lh
complete -c setkey -o ls -d 'Specify hard/soft life time duration of the SA measured in seconds'
complete -c setkey -o bh
complete -c setkey -o bs -d 'Specify hard/soft life time duration of the SA measured in bytes transported'
complete -c setkey -s E -d 'Specify an encryption algorithm ealgo for ESP'
complete -c setkey -s A -d 'Specify an authentication algorithm for AH'
complete -c setkey -s C -d 'Specify a compression algorithm for IPComp'
complete -c setkey -s P

