# setquota
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/setquota.1
complete -c setquota -s a -d 'sets home directory quota for users defined in all directory domains of the s…'
complete -c setquota -s l -d 'sets home directory quota for users defined in the local directory domain'
complete -c setquota -s n -d 'sets home directory quota for users defined in a specific directory domain in…'
complete -c setquota -s u -d 'sets home directory quota for a specific user defined in the domain(s) identi…'

