# sftp-server
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/sftp-server.8
complete -c sftp-server -s d -d 'specifies an alternate starting directory for users'
complete -c sftp-server -s e -d 'Causes sftp-server to print logging information to stderr instead of syslog f…'
complete -c sftp-server -s f -d 'Specifies the facility code that is used when logging messages from sftp-serv…'
complete -c sftp-server -s h -d 'Displays sftp-server usage information'
complete -c sftp-server -s l -d 'Specifies which messages will be logged by sftp-server'
complete -c sftp-server -s P -d 'Specify a comma-separated list of SFTP protocol requests that are banned by t…'
complete -c sftp-server -s p -d 'Specify a comma-separated list of SFTP protocol requests that are permitted b…'
complete -c sftp-server -s Q -d 'Query protocol features supported by sftp-server'
complete -c sftp-server -s R -d 'Places this instance of sftp-server into a read-only mode'
complete -c sftp-server -s u -d 'Sets an explicit umask 2 to be applied to newly-created files and directories…'

