# sharing
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/sharing.8
complete -c sharing -s a -d 'Add a new share point for the directory specified by <path>'
complete -c sharing -s e -d 'Edit the share point record specified by <share point name>'
complete -c sharing -s r -d 'Delete the share point record specified by <share point name>'
complete -c sharing -s l -d 'List all existing share point records'
complete -c sharing -s S -d 'Use customized name <smb name> when using share points with smb'
complete -c sharing -s s -d 'Use this option to enable and disable sharing via smb'
complete -c sharing -s g -d 'Use this option to enable and disable guest access for smb'
complete -c sharing -s n -d 'Specify a <customized record name> to be used as the share point record name'
complete -c sharing -s R -d 'Make share read only for smb.  Specify 1 to enable read only'
complete -c sharing -s E -d 'Make share encrypted for smb v3 and later.  Specify 1 to enable encryption'
complete -c sharing -s f -d 'Only used when listing share points and only json format is supported'

