# shortcuts
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/shortcuts.1
complete -c shortcuts -o '\\-input' -d 'The shortcut file to sign'
complete -c shortcuts -o '\\-output' -d 'Output path for the signed shortcut file.  El Pp'

