# showmount
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/showmount.8
complete -c showmount -s A -d 'Search for NFS servers advertised via Bonjour'
complete -c showmount -s a -d 'List all mount points in the form: host : Ns Ar dirpath'
complete -c showmount -s d -d 'List directory paths of mount points instead of hosts'
complete -c showmount -s e -d 'Show the host Ns \'s exports list'
complete -c showmount -s 3 -d 'Use mount protocol Version 3, compatible with NFS Version 3'
complete -c showmount -s 6 -d 'Use only IPv6 addresses to contact servers'

