# shutdown
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/shutdown.8
complete -c shutdown -s h -d 'The system is halted at the specified time'
complete -c shutdown -s k -d 'Kick everybody off'
complete -c shutdown -s n -d 'If the o is specified, prevent the file system cache from being flushed by pa…'
complete -c shutdown -s o -d 'If h or r is specified, shutdown shutdown will execute halt 8 or reboot 8 ins…'
complete -c shutdown -s r -d 'The system is rebooted at the specified time'
complete -c shutdown -s s -d 'The system is put to sleep at the specified time'
complete -c shutdown -s u -d 'The system is halted up until the point of removing system power, but waits b…'

