# sips
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/sips.1
complete -c sips -s g
complete -c sips -l getProperty -d 'Output the property value for key to stdout.  Pp'
complete -c sips -s X
complete -c sips -l extractTag -d 'Write a profile tag element to tagFile.  Pp'
complete -c sips -l verify -d 'Verify any profile problems and log output to stdout.  Pp'
complete -c sips -s 1
complete -c sips -l oneLine -d 'Output for each file on a single line with tab delimiter Pp El Image query fu…'
complete -c sips -s x
complete -c sips -l extractProfile -d 'Get the embedded profile from image and write it to profile.  Pp'
complete -c sips -s s
complete -c sips -l setProperty -d 'Set a property value for key to value.  Pp'
complete -c sips -s d
complete -c sips -l deleteProperty -d 'Remove a property value for key.  Pp'
complete -c sips -l deleteTag -d 'Remove the tag element from a profile.  Pp'
complete -c sips -l copyTag -d 'Copy the srcTag element of a profile to dstTag.  Pp'
complete -c sips -l loadTag -d 'Set the tag element of a profile to the contents of tagFile.  Pp'
complete -c sips -l repair -d 'Repair any profile problems and log output to stdout.  Pp'
complete -c sips -s o
complete -c sips -l out -d 'Pp El Image modification functions: -tag -width xxxx -compact Pp'
complete -c sips -s e
complete -c sips -l embedProfile -d 'Embed profile in image.  Pp'
complete -c sips -s E
complete -c sips -l embedProfileIfNone -d 'Embed profile in image only if image doen\'t have a profile.  Pp'
complete -c sips -s m
complete -c sips -l matchTo -d 'Color match image to profile.  Pp'
complete -c sips -s M
complete -c sips -l matchToWithIntent -d 'Color match image to profile with rendering intent perceptual | relative | sa…'
complete -c sips -l deleteColorManagementProperties -d 'Delete color management properties in TIFF, PNG, and EXIF dictionaries.  Pp'
complete -c sips -s r
complete -c sips -l rotate -d Pp
complete -c sips -s f
complete -c sips -l flip -d Pp
complete -c sips -s c
complete -c sips -l cropToHeightWidth -d 'Crop image to fit specified size.  Pp'
complete -c sips -l cropOffset -d 'Crop offset from top left corner.  Pp'
complete -c sips -s p
complete -c sips -l padToHeightWidth -d 'Pad image with pixels to fit specified size.  Pp'
complete -c sips -l padColor -d 'Use this color when padding'
complete -c sips -s z
complete -c sips -l resampleHeightWidth -d 'Resample image at specified size.  Image apsect ratio may be altered.  Pp'
complete -c sips -l resampleWidth -d 'Resample image to specified width.  Pp'
complete -c sips -l resampleHeight -d 'Resample image to specified height.  Pp'
complete -c sips -s Z
complete -c sips -l resampleHeightWidthMax -d 'Resample image so height and width aren\'t greater than specified size.  Pp'
complete -c sips -s i
complete -c sips -l addIcon -d 'Add a Finder icon to image file.  Pp'
complete -c sips -l optimizeColorForSharing -d 'Optimize color for sharing.  Pp'
complete -c sips -s j
complete -c sips -l js -d 'Execute JavaScript file Pp El Other functions: -tag -width xxxx -compact Pp'
complete -c sips -l debug -d 'Enable debugging output Pp'
complete -c sips -s h
complete -c sips -l help -d 'Show help Pp'
complete -c sips -s H
complete -c sips -l helpProperties -d 'Show help for properties Pp'
complete -c sips -l man -d 'Generate man pages Pp'
complete -c sips -s v
complete -c sips -l version -d 'Show the version Pp'
complete -c sips -l formats -d 'Show the read/write formats Pp El JavaScript HTML Canvas objects can be creat…'

