# size
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/size.1
complete -c size -s m -d 'Print the sizes of the Mach-O segments and sections as well as the total size…'
complete -c size -s l -d 'When used with the  -m option, also print the addresses and offsets of the se…'
complete -c size -s x -d 'When used with the  -m option, print the values in hexadecimal (with leading …'
complete -c size -o arch -d 'Specifies the architecture, arch_type, of the file for size (1) to operate on…'

