# slapindex
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/slapindex.8
complete -c slapindex -s b -d 'Use the specified suffix to determine which database to generate output for'
complete -c slapindex -s c -d 'enable continue (ignore errors) mode'
complete -c slapindex -s d -d 'enable debugging messages as defined by the specified R debug-level ; see  sl…'
complete -c slapindex -s f -d 'specify an alternative  slapd. conf (5) file'
complete -c slapindex -s F -d 'specify a config directory'
complete -c slapindex -s g -d 'disable subordinate gluing'
complete -c slapindex -s n -d 'Generate output for the dbnum-th database listed in the configuration file'
complete -c slapindex -s o -d 'Specify an  option with a(n optional) R value '
complete -c slapindex -s q -d 'enable quick (fewer integrity checks) mode'
complete -c slapindex -s t -d 'enable truncate mode'
complete -c slapindex -s u -d 'in slapd (8)), or change file ownership before running slapd (8).  OPTIONS'
complete -c slapindex -s v -d 'enable verbose mode'

