# slaptest
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/slaptest.8
complete -c slaptest -s d -d 'enable debugging messages as defined by the specified R debug-level ; see  sl…'
complete -c slaptest -s f -d 'specify an alternative  slapd. conf (5) file'
complete -c slaptest -s F -d 'specify a config directory'
complete -c slaptest -s n -d 'Just open and test the dbnum-th database listed in the configuration file'
complete -c slaptest -s o -d 'Specify an  option with a(n optional) R value '
complete -c slaptest -s Q -d 'Be extremely quiet: only the exit code indicates success (0) or not  (any oth…'
complete -c slaptest -s u -d 'enable dry-run mode (i. e'
complete -c slaptest -s v -d 'enable verbose mode.  EXAMPLES To check a  slapd'

