# slapd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/slapd.8
complete -c slapd -s 4 -d 'Listen on IPv4 addresses only'
complete -c slapd -s 6 -d 'Listen on IPv6 addresses only'
complete -c slapd -s T -d 'Run in Tool mode'
complete -c slapd -s d -d 'Turn on debugging as defined by R debug-level '
complete -c slapd -s s -d 'This option tells  slapd at what debug-level debugging statements should be l…'
complete -c slapd -s n -d 'Specifies the service name for logging and other purposes'
complete -c slapd -s l -d 'Selects the local user of the  syslog (8) facility'
complete -c slapd -s f -d 'Specifies the slapd configuration file.  The default is  /etc/openldap/slapd'
complete -c slapd -s F -d 'Specifies the slapd configuration directory'
complete -c slapd -s h -d 'slapd will by default serve  ldap:/// (LDAP over TCP on all interfaces on def…'
complete -c slapd -s r -d 'Specifies a directory to become the root directory'
complete -c slapd -s u -d 'slapd will run slapd with the specified user name or id, and that user\'s supp…'
complete -c slapd -s g -d 'slapd will run with the specified group name or id'
complete -c slapd -s c -d 'This option provides a cookie for the syncrepl replication consumer'
complete -c slapd -s o -d 'This option provides a generic means to specify options without the need to r…'

