# slappasswd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/slappasswd.8
complete -c slappasswd -s v -d 'enable verbose mode'
complete -c slappasswd -s u -d 'Generate RFC 2307 userPassword values (the default)'
complete -c slappasswd -s s -d 'The secret to hash'
complete -c slappasswd -s g -d 'Generate the secret'
complete -c slappasswd -s T -d 'Hash the contents of the file'
complete -c slappasswd -s h -d 'If -h is specified, one of the following RFC 2307 schemes may be specified:  …'
complete -c slappasswd -s c -d 'Specify the format of the salt passed to  crypt (3) when generating {CRYPT} p…'
complete -c slappasswd -s n -d 'Omit the trailing newline; useful to pipe the credentials into a command'

