# slapschema
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/slapschema.8
complete -c slapschema -s a -d 'Only check entries matching the asserted filter'
complete -c slapschema -s b -d 'Use the specified suffix to determine which database to check'
complete -c slapschema -s c -d 'Enable continue (ignore errors) mode'
complete -c slapschema -s d -d 'Enable debugging messages as defined by the specified R debug-level ; see  sl…'
complete -c slapschema -s f -d 'Specify an alternative  slapd. conf (5) file'
complete -c slapschema -s F -d 'specify a config directory'
complete -c slapschema -s g -d 'disable subordinate gluing'
complete -c slapschema -s H -d 'use dn, scope and filter from URI to only handle matching entries'
complete -c slapschema -s l -d 'Write errors to specified file instead of standard output'
complete -c slapschema -s n -d 'Check the dbnum-th database listed in the configuration file'
complete -c slapschema -s o -d 'Specify an  option with a(n optional) R value '
complete -c slapschema -s s -d 'Only check entries in the subtree specified by this DN'
complete -c slapschema -s v -d 'Enable verbose mode'

