# slapauth
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/slapauth.8
complete -c slapauth -s d -d 'enable debugging messages as defined by the specified R debug-level ; see  sl…'
complete -c slapauth -s f -d 'specify an alternative  slapd. conf (5) file'
complete -c slapauth -s F -d 'specify a config directory'
complete -c slapauth -s M -d 'specify a mechanism'
complete -c slapauth -s o -d 'Specify an  option with a(n optional) R value '
complete -c slapauth -s R -d 'specify a realm'
complete -c slapauth -s U -d 'specify an ID to be used as   authcID throughout the test session'
complete -c slapauth -s X -d 'specify an ID to be used as   authzID throughout the test session'
complete -c slapauth -s v -d 'enable verbose mode'

