# slapacl
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/slapacl.8
complete -c slapacl -s b -d 'specify the   DN  which access is requested to; the corresponding entry is fe…'
complete -c slapacl -s d -d 'enable debugging messages as defined by the specified R debug-level ; see  sl…'
complete -c slapacl -s D -d 'specify a DN to be used as identity through the test session when selecting a…'
complete -c slapacl -s f -d 'specify an alternative  slapd. conf (5) file'
complete -c slapacl -s F -d 'specify a config directory'
complete -c slapacl -s o -d 'Specify an  option with a(n optional) R value '
complete -c slapacl -s u -d 'do not fetch the entry from the database'
complete -c slapacl -s U -d 'specify an ID to be mapped to a   DN  as by means of   authz-regexp or  authz…'
complete -c slapacl -s v -d 'enable verbose mode'
complete -c slapacl -s X -d 'specify an authorization ID to be mapped to a DN as by means of authz-regexp …'

