# slapadd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/slapadd.8
complete -c slapadd -s b -d 'Use the specified suffix to determine which database to add entries to'
complete -c slapadd -s c -d 'enable continue (ignore errors) mode'
complete -c slapadd -s d -d 'enable debugging messages as defined by the specified R debug-level ; see  sl…'
complete -c slapadd -s f -d 'specify an alternative  slapd. conf (5) file'
complete -c slapadd -s F -d 'specify a config directory'
complete -c slapadd -s g -d 'disable subordinate gluing'
complete -c slapadd -s j -d 'Jump to the specified line number in the LDIF file before processing any entr…'
complete -c slapadd -s l -d 'Read LDIF from the specified file instead of standard input'
complete -c slapadd -s n -d 'Add entries to the dbnum-th database listed in the configuration file'
complete -c slapadd -s o -d 'Specify an  option with a(n optional) R value '
complete -c slapadd -s q -d 'enable quick (fewer integrity checks) mode'
complete -c slapadd -s s -d 'disable schema checking'
complete -c slapadd -s S -d 'Server ID to use in generated entryCSN'
complete -c slapadd -s u -d 'enable dry-run (don\'t write to backend) mode'
complete -c slapadd -s v -d 'enable verbose mode'
complete -c slapadd -s w -d 'write syncrepl context information'

