# slapcat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/slapcat.8
complete -c slapcat -s a -d 'Only dump entries matching the asserted filter'
complete -c slapcat -s b -d 'Use the specified suffix to determine which database to generate output for'
complete -c slapcat -s c -d 'Enable continue (ignore errors) mode'
complete -c slapcat -s d -d 'Enable debugging messages as defined by the specified R debug-level ; see  sl…'
complete -c slapcat -s f -d 'Specify an alternative  slapd. conf (5) file'
complete -c slapcat -s F -d 'specify a config directory'
complete -c slapcat -s g -d 'disable subordinate gluing'
complete -c slapcat -s H -d 'use dn, scope and filter from URI to only handle matching entries'
complete -c slapcat -s l -d 'Write LDIF to specified file instead of standard output'
complete -c slapcat -s n -d 'Generate output for the dbnum-th database listed in the configuration file'
complete -c slapcat -s o -d 'Specify an  option with a(n optional) R value '
complete -c slapcat -s s -d 'Only dump entries in the subtree specified by this DN'
complete -c slapcat -s v -d 'Enable verbose mode'

