# slapdn
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/slapdn.8
complete -c slapdn -s d -d 'enable debugging messages as defined by the specified R debug-level ; see  sl…'
complete -c slapdn -s f -d 'specify an alternative  slapd. conf (5) file'
complete -c slapdn -s F -d 'specify a config directory'
complete -c slapdn -s N -d 'only output a normalized form of the DN, suitable to be used in a normalizati…'
complete -c slapdn -s o -d 'Specify an  option with a(n optional) R value '
complete -c slapdn -s P -d 'only output a prettified form of the DN, suitable to be used in a check and b…'
complete -c slapdn -s v -d 'enable verbose mode'

