# smbd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/smbd.8
complete -c smbd -o debug -d 'The service will log extensive debug information and may perform extra diagno…'
complete -c smbd -o help -d 'Prints a usage message and exits'
complete -c smbd -o ports -d 'The service will listen on each of the TCP ports specified in the comma-separ…'
complete -c smbd -o stdout -d 'Causes smbd to print log messages to standard output instead of the system log'
complete -c smbd -o no-symlinks -d 'In normal operation, smbd will respond to client symlink requests but will ne…'

