# smbutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/smbutil.1
complete -c smbutil -s h -d 'Print a short help message'
complete -c smbutil -s v -d 'Verbose output'
complete -c smbutil -s A -d 'authorize only'
complete -c smbutil -s N -d 'don\'t prompt for a password'
complete -c smbutil -s G -d 'allow guest access'
complete -c smbutil -s g -d 'authorize with guest only'
complete -c smbutil -s a -d 'authorize with anonymous only'
complete -c smbutil -s f -d 'don\'t share session'
complete -c smbutil -s i -d 'print information about the session'
complete -c smbutil -s c -d 'print information about the client\'s interfaces'
complete -c smbutil -s s -d 'print information about the server\'s interfaces'
complete -c smbutil -s x -d 'print information about the established connection'

