# smtpd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/smtpd.8
complete -c smtpd -o bs -d '$mail_owner privileges, it receives mail even while the mail system is not ru…'
complete -c smtpd -s V -d 'and later'

