# snmpbulkwalk
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/snmpbulkwalk.1
complete -c snmpbulkwalk -o Cc -d 'Do not check whether the returned OIDs are increasing'
complete -c snmpbulkwalk -o Ci -d 'Include the given OID in the search range'
complete -c snmpbulkwalk -o Cn -d 'Set the  non-repeaters field in the GETBULK PDUs'
complete -c snmpbulkwalk -o Cp -d 'Upon completion of the walk, print the number of variables found'
complete -c snmpbulkwalk -o Cr -d 'Set the max-repetitions field in the GETBULK PDUs'

