# snmpusm
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/snmpusm.1
complete -c snmpusm -o CE -d 'Set usmUserEngineID to be used as part of the index of the usmUserTable'
complete -c snmpusm -o Cp -d 'Set the usmUserPublic value of the (new) user to the specified STRING'
complete -c snmpusm -o Ca -d 'Change the authentication key'
complete -c snmpusm -o Cx -d 'Change the privacy key'
complete -c snmpusm -o Ck -d 'Allows to use localized key (must start with 0x) instead of passphrase'

