# snmpconf
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/snmpconf.1
complete -c snmpconf -s g -d 'switch, which walks a user through a specific set of configuration questions'
complete -c snmpconf -s f -d 'Force overwriting existing files in the current directory without prompting t…'
complete -c snmpconf -s i -d 'When finished, install the files into the location where the global system co…'
complete -c snmpconf -s p -d 'When finished, install the files into the users home directory\'s '
complete -c snmpconf -s I -d 'When finished, install the files into the directory  DIRECTORY '
complete -c snmpconf -s a -d 'Don\'t ask any questions'
complete -c snmpconf -s r -d 'Read in either all or none of the found configuration files'
complete -c snmpconf -s R -d 'Read in a specific list of configuration files'
complete -c snmpconf -s G -d 'List all the known groups'
complete -c snmpconf -s c -d 'snmpconf uses a directory of configuration information to learn about the fil…'
complete -c snmpconf -s q -d 'Run slightly more quietly'
complete -c snmpconf -s d -d 'Turn on  lots of debugging output'
complete -c snmpconf -s D -d 'Add  even more debugging output in the form of Perl variable dumps'

