# snmptable
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/snmptable.1
complete -c snmptable -o Cb -d 'Display only a brief heading'
complete -c snmptable -o CB -d 'Do not use GETBULK requests to retrieve data, only GETNEXT'
complete -c snmptable -o Cc -d 'Print table in columns of  CHARS characters width'
complete -c snmptable -o Cf -d 'The string  STRING is used to separate table columns'
complete -c snmptable -o Ch -d 'Display  only the column headings'
complete -c snmptable -o CH -d 'Do not display the column headings'
complete -c snmptable -o Ci -d 'This option prepends the index of the entry to all printed lines'
complete -c snmptable -o Cl -d 'Left justify the data in each column'
complete -c snmptable -o Cr -d 'For GETBULK requests,   REPEATERS specifies the max-repeaters value to use'
complete -c snmptable -o Cw -d 'Specifies the width of the lines when the table is printed'

