# snmptrap
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/snmptrap.1
complete -c snmptrap -o Ci -d 'is added to the command line flags of snmptrap, it sends an INFORM-PDU, expec…'

