# snmpgetnext
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/snmpgetnext.1
complete -c snmpgetnext -o Cf -d If

