# snmpnetstat
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/snmpnetstat.1
complete -c snmpnetstat -o Ca -d 'With the default display, show the state of all sockets; normally sockets use…'
complete -c snmpnetstat -o Ci -d 'Show the state of all of the network interfaces'
complete -c snmpnetstat -o Co -d 'Show an abbreviated interface status, giving octets in place of packets'
complete -c snmpnetstat -o CI -d 'Show information only about this interface; used with an interval as describe…'
complete -c snmpnetstat -o Cn -d 'Show network addresses as numbers (normally  snmpnetstat interprets addresses…'
complete -c snmpnetstat -o Cp -d 'Show statistics about  protocol, which is either a well-known name for a prot…'
complete -c snmpnetstat -o Cs -d 'Show per-protocol statistics.   When used with the'
complete -c snmpnetstat -o Cr -d 'option, show routing statistics instead'
complete -c snmpnetstat -o CR -d 'For GETBULK requests, repeaters specifies the max-repeaters value to use'

