# snmpwalk
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/snmpwalk.1
complete -c snmpwalk -o Cc -d 'Do not check whether the returned OIDs are increasing'
complete -c snmpwalk -o CE -d 'End the walk at the specified OID, rather than a simple subtree'
complete -c snmpwalk -o Ci -d 'Include the given OID in the search range'
complete -c snmpwalk -o CI -d 'In fact, the given OID will be retrieved automatically if the main subtree wa…'
complete -c snmpwalk -o Cp -d 'Upon completion of the walk, print the number of variables found'
complete -c snmpwalk -o Ct -d 'Upon completion of the walk, print the total wall-clock time it took to colle…'

