# snmpdelta
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/snmpdelta.1
complete -c snmpdelta -o Cf -d 'Don\'t fix errors and retry the request'
complete -c snmpdelta -o Ct -d 'Flag will determine time interval from the monitored entity'
complete -c snmpdelta -o Cs -d 'Flag will display a timestamp'
complete -c snmpdelta -o CS -d 'Generates a "sum count" in addition to the individual instance counts'
complete -c snmpdelta -o Cm -d 'Prints the max value ever attained'
complete -c snmpdelta -o CF -d 'Tells  snmpdelta to read it\'s configuration from the specified file'
complete -c snmpdelta -o Cl -d 'Tells  snmpdelta to write it\'s configuration to files whose names correspond …'
complete -c snmpdelta -o Cp -d 'Specifies the number of seconds between polling periods'
complete -c snmpdelta -o CP -d 'Specifies the reporting period in number of polling periods'
complete -c snmpdelta -o Ck -d 'When the polling period (-Cp) is an increment of 60 seconds and the timestamp…'
complete -c snmpdelta -o CT -d 'Makes   snmpdelta print its output in tabular form'
complete -c snmpdelta -o Cv -d 'Specifies the maximum number of oids allowed to be packaged in a single PDU'

