# snmptranslate
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/snmptranslate.1
complete -c snmptranslate -o 'D[TOKEN' -d 'Turn on debugging output for the given R "TOKEN" "(s)'
complete -c snmptranslate -s h -d 'Display a brief usage message and then exit'
complete -c snmptranslate -s m -d 'Specifies a colon separated list of MIB modules to load for this application'
complete -c snmptranslate -s M -d 'Specifies a colon separated list of directories to search for MIBs'
complete -c snmptranslate -s T -d 'Provides control over the translation of the OID values'
complete -c snmptranslate -o Td -d 'Print full details of the specified OID'
complete -c snmptranslate -o Tp -d 'Print a graphical tree, rooted at the specified OID'
complete -c snmptranslate -o Ta -d 'Dump the loaded MIB in a trivial form'
complete -c snmptranslate -o Tl -d 'Dump a labeled form of all objects'
complete -c snmptranslate -o To -d 'Dump a numeric form of all objects'
complete -c snmptranslate -o Ts -d 'Dump a symbolic form of all objects'
complete -c snmptranslate -o Tt -d 'Dump a tree form of the loaded MIBs (mostly useful for debugging)'
complete -c snmptranslate -o Tz -d 'Dump a numeric and labeled form of all objects (compatible with MIB2SCHEMA fo…'
complete -c snmptranslate -s V -d 'Display version information for the application and then exit'
complete -c snmptranslate -s w -d 'Specifies the width of'

