# sntp
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/sntp.1
complete -c sntp -s d -d 'Enable debug logging'
complete -c sntp -s g -d 'Gap betwen requests in milliseconds'
complete -c sntp -s n -d 'Number of DNS records to use for each host argument'
complete -c sntp -s r -d 'bind 2 the NTP reserved port (123) for source communications'
complete -c sntp -s S -d 'Use clock_settime 2 to set the system clock if the offset is greater than 50 …'
complete -c sntp -s s -d 'Use adjtime 2 to slew the system clock if the offset is less than 50 millisec…'
complete -c sntp -s t -d 'Maximum number of seconds to wait for responses'
complete -c sntp -s z -d 'Path to dump header state to.  This is useful for sntpd 8 to read from'

