# softwareupdate
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/softwareupdate.8
complete -c softwareupdate -s l -d 'List all available updates'
complete -c softwareupdate -s i -d 'Each update specified by args is downloaded and installed'
complete -c softwareupdate -l list-full-installers -d 'List the available macOS Installers'
complete -c softwareupdate -l fetch-full-installer -d 'Install the latest recommended macOS Installer'
complete -c softwareupdate -l install-rosetta -d 'Install Rosetta.  Only applies to Apple silicon Macs'
complete -c softwareupdate -s d -d 'Each update specified by args is downloaded but not installed'
complete -c softwareupdate -l schedule -d 'Returns the per-machine automatic (background) check preference'
complete -c softwareupdate -s h -d 'Print command usage'

