# split
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/split.1
complete -c split -s a -d 'Use suffix_length letters to form the suffix of the file name'
complete -c split -s b -d 'off K | k | M | m | G | g on Oc Create split files byte_count bytes in length'
complete -c split -s d -d 'Use a numeric suffix instead of a alphabetic suffix'
complete -c split -s l -d 'Create split files line_count lines in length'
complete -c split -s n -d 'Split file into chunk_count smaller files'
complete -c split -s p -d 'The file is split whenever an input line matches pattern, which is interprete…'

