# spray
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/spray.8
complete -c spray -s c -d 'Send count packets'
complete -c spray -s d -d 'Pause delay microseconds between sending each packet'
complete -c spray -s l -d 'Set the length of the packet that holds the RPC call message to length bytes'

