# ssh-pkcs11-helper
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/ssh-pkcs11-helper.8
complete -c ssh-pkcs11-helper -s v -d 'Verbose mode'

