# sso_util
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/sso_util.8
complete -c sso_util -s p -d 'Returns the data in XML format'
complete -c sso_util -s g -d 'Returns the default Kerberos realm name'
complete -c sso_util -s l -d 'Returns a list of the services sso_util knows how to Kerberize'
complete -c sso_util -s L -d 'Returns the default Kerberos log file paths'
complete -c sso_util -s r -d 'Returns whether or not the given node has a Kerberos record associated with it'
complete -c sso_util -s a -d 'Account name of an administrator authorized to make changes in the Kerberos d…'
complete -c sso_util -s u -d 'Forces the update, ignoring that the update may already have been installed'
complete -c sso_util -s R -d 'Name of the Computer record containing the secure config record'
complete -c sso_util -s f -d 'Specifies the directory node in which to find the given computer record'

