# stapler
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/stapler.1
complete -c stapler -s q -d 'When validating or attaching tickets, stapler will only return the exit code'
complete -c stapler -s v -d 'Sets the output of stapler to include additional diagnostic output'

