# strings
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/strings.1
complete -c strings -s a -d 'This option causes  strings to look for strings in all sections of the object…'
complete -c strings -s o -d 'Preceded each string by its offset in the file (in decimal)'
complete -c strings -s t -d 'Write each string preceded by its byte offset from the start of the file'
complete -c strings -s n -d 'Specify the minimum string length, where the number argument is a positive de…'
complete -c strings -o arch -d 'Specifies the architecture, arch_type, of the file for strings (1) to operate…'

