# stringdups
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/stringdups.1
complete -c stringdups -o minimumCount -d 'Only print information for object descriptions which appear at least count ti…'
complete -c stringdups -o stringsOnly -d 'Only print information for objects that have string content such as C or Pasc…'
complete -c stringdups -o nostacks -d 'Do not print stack backtraces or call trees even if the target process has th…'
complete -c stringdups -o callTrees -d 'If stack backtraces are available, then by default all the object description…'
complete -c stringdups -o invertCallTrees -d 'Same as callTrees except that the call trees are printed from hottest to cold…'

