# su
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/su.1
complete -c su -s f -d 'If the invoked shell is csh 1, this option prevents it from reading the '
complete -c su -s l -d 'Simulate a full login'
complete -c su -s m -d 'Leave the environment unmodified'

