# suexec
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/suexec.8
complete -c suexec -s V -d 'If you are root, this option displays the compile options of suexec'

