# sysctl
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/sysctl.8
complete -c sysctl -s A -d 'Equivalent to o a (for compatibility)'
complete -c sysctl -s a -d 'List all the currently available non-opaque values'
complete -c sysctl -s b -d 'Force the value of the variable(s) to be output in raw, binary format'
complete -c sysctl -s d -d 'Print the description of the variable instead of its value'
complete -c sysctl -s e -d 'Separate the name and the value of the variable(s) with ='
complete -c sysctl -s h -d 'Format output for human, rather than machine, readability'
complete -c sysctl -s i -d 'Ignore unknown OIDs'
complete -c sysctl -s N -d 'Show only variable names, not their values'
complete -c sysctl -s n -d 'Show only variable values, not their names'
complete -c sysctl -s o -d 'Show opaque variables (which are normally suppressed)'
complete -c sysctl -s q -d 'Suppress some warnings generated by sysctl to standard error'
complete -c sysctl -s X -d 'Equivalent to x a (for compatibility)'
complete -c sysctl -s x -d 'As o, but prints a hex dump of the entire value instead of just the first few…'

