# syslogd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/syslogd.8
complete -c syslogd -s d -d 'Run syslogd in debugging mode'
complete -c syslogd -s D -d 'Start as a daemon'
complete -c syslogd -s m -d 'Set the number of minutes between mark messages'
complete -c syslogd -o db_max -d 'Sets the size limit in bytes for individual files in the data store'
complete -c syslogd -o utmp_ttl -d 'Sets the time-to-live in seconds for messages used by the utmp 5, wtmp 5, and…'
complete -c syslogd -o mps_limit -d 'Sets the kernel quota for messages per second allowed by syslogd'
complete -c syslogd -o dup_delay -d 'Sets the time to delay for coalescing duplicate message in log files'
complete -c syslogd -o asl_in -d 'The asl_in module receives log messages on the UNIX domain socket associated …'
complete -c syslogd -o asl_action -d 'The asl_action module examines the stream of received log messages and acts u…'
complete -c syslogd -o klog_in -d 'The klog_in module receives log messages on the UNIX domain socket associated…'
complete -c syslogd -o bsd_out -d 'The bsd_out module examines the stream of received log messages and acts upon…'
complete -c syslogd -o udp_in -d 'The udp_in module receives log messages on the UDP socket associated with the…'

