# systemkeychain
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/systemkeychain.8
complete -c systemkeychain -s C -d 'Create a keychain and establish it in the system as the primary system keycha…'
complete -c systemkeychain -s s -d 'Extract the master secret from source keychain(s) and install them in a desti…'
complete -c systemkeychain -s t -d 'Test unlocking the system keychain'
complete -c systemkeychain -s k -d 'Use a keychain other than the default as the destination system keychain'
complete -c systemkeychain -s c -d 'Create the target keychain if necessary'
complete -c systemkeychain -s f -d 'Force creation of a system keychain or overwriting of an existing key for key…'
complete -c systemkeychain -s v -d 'Turn on verbose mode'

