# system_profiler
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/system_profiler.8
complete -c system_profiler -o xml -d 'Generates a report in XML format'
complete -c system_profiler -o json -d 'Generates a report in JSON format'
complete -c system_profiler -o listDataTypes -d 'Lists the available datatypes'
complete -c system_profiler -o detailLevel -d 'Specifies the level of detail for the report: -tag -width 12n mini report wit…'
complete -c system_profiler -o timeout -d 'Specifies the maximum time to wait in seconds for results'
complete -c system_profiler -o usage -d 'Prints usage info and examples'

