# tab2space
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/tab2space.1
complete -c tab2space -o help -s h -d 'display this help message'
complete -c tab2space -o dos -o crlf -d 'set line ends to CRLF (PC-DOS/Windows - default)'
complete -c tab2space -o mac -o cr -d 'set line ends to CR (classic Mac OS)'
complete -c tab2space -o unix -o lf -d 'set line ends to LF (Unix / Mac OS X)'
complete -c tab2space -o tabs -d 'preserve tabs, e. g.  for Makefile'
complete -c tab2space -o 't<n>' -d 'set tabs to <n> (default is 4) spaces SEE ALSO'

