# tabs
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/tabs.1
complete -c tabs -s n -d 'Set a tab stop every n columns'
complete -c tabs -s a -d 'Assembler format (columns 1, 10, 16, 36, 72)'
complete -c tabs -o a2 -d 'Assembler format (columns 1, 10, 16, 40, 72)'
complete -c tabs -s c -d 'COBOL normal format (columns 1, 8, 12, 16, 20, 55)'
complete -c tabs -o c2 -d 'COBOL compact format (columns 1, 6, 10, 14, 49)'
complete -c tabs -o c3 -d 'COBOL compact format (columns 1, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 5…'
complete -c tabs -s f -d 'FORTRAN format (columns 1, 7, 11, 15, 19, 23)'
complete -c tabs -s p -d 'PL/1 format (columns 1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57,…'
complete -c tabs -s s -d 'SNOBOL format (columns 1, 10, 55)'
complete -c tabs -s u -d 'Assembler format (columns 1, 12, 20, 44)'
complete -c tabs -s T -d 'Output escape sequence for the terminal type type'

