# tailspin
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/tailspin.1
complete -c tailspin -s r -d 'Include a key in the tailspin file indicating why it was saved'
complete -c tailspin -s l -d 'Limit the data in tailspin file to that of the last num-seconds'
complete -c tailspin -s n -d 'Save tailspin file without symbolicating'
complete -c tailspin -s v -d 'Print layout information of tailspin file'
complete -c tailspin -s s -d 'Sort ktrace statistics by frequency of trace class/subclass'

