# talagent
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/talagent.8
complete -c talagent -o help -d 'Outputs usage information'
complete -c talagent -o dump -d 'Outputs the persistent state of an application whose bundle ID contains the g…'
complete -c talagent -o launch -d 'This launches an app (in this case, TextEdit) in a manner approximating how a…'
complete -c talagent -o memory_pressure -d 'Simulates memory pressure, which may cause apps that support automatic termin…'
complete -c talagent -o refresh_encryption -d 'Rotates the bitmap encryption key, and attempts to cross-encrypt all existing…'

