# tapi-archive
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/tapi-archive.1
complete -c tapi-archive -l info
complete -c tapi-archive -l verify-arch
complete -c tapi-archive -l extract
complete -c tapi-archive -l remove
complete -c tapi-archive -l merge
complete -c tapi-archive -s o
complete -c tapi-archive -l help
complete -c tapi-archive -l version

