# tapi-reexport
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/tapi-reexport.1
complete -c tapi-reexport -o arch
complete -c tapi-reexport -o macosx_version_min
complete -c tapi-reexport -o ios_version_min
complete -c tapi-reexport -o watchos_version_min
complete -c tapi-reexport -o tvos_version_min -d 'This is set to indicate the oldest platform version that that the output is t…'
complete -c tapi-reexport -o ObjC
complete -c tapi-reexport -o ObjC++
complete -c tapi-reexport -s x
complete -c tapi-reexport -o std
complete -c tapi-reexport -s D
complete -c tapi-reexport -s U
complete -c tapi-reexport -o isysroot
complete -c tapi-reexport -s I
complete -c tapi-reexport -s L
complete -c tapi-reexport -s F
complete -c tapi-reexport -s o
complete -c tapi-reexport -o fno-rtti
complete -c tapi-reexport -l help

