# tapi-analyze
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/tapi-analyze.1
complete -c tapi-analyze -l target
complete -c tapi-analyze -s o
complete -c tapi-analyze -l sdkdb
complete -c tapi-analyze -s v
complete -c tapi-analyze -l app-info-output
complete -c tapi-analyze -l pretty-json

