# taskpolicy
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/taskpolicy.8
complete -c taskpolicy -s d -d 'Run the program after calling setiopolicy_np 3 with an iotype of IOPOL_TYPE_D…'
complete -c taskpolicy -s g -d 'Run the program after calling setiopolicy_np 3 with an iotype of IOPOL_TYPE_D…'
complete -c taskpolicy -s c -d 'Run the program using the specified QoS clamp'
complete -c taskpolicy -s p -d 'Change settings for the process specified by pid'
complete -c taskpolicy -s b -d 'Run the program after calling setpriority 2 with a priority of PRIO_DARWIN_BG'
complete -c taskpolicy -s B -d 'Move target process out of PRIO_DARWIN_BG'
complete -c taskpolicy -s t -d 'Set throughput tier of the process to thruput_tier'
complete -c taskpolicy -s l -d 'Set latency tier of the process to latency_tier'
complete -c taskpolicy -s a -d 'Run the program with the resource management policies given to applications'
complete -c taskpolicy -s s -d 'Run the program with an initial suspended state by calling posix_spawnattr_se…'

