# tbl
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/tbl.1
complete -c tbl -s C -d 'Enable compatibility mode to recognize  . TS and  '
complete -c tbl -s t -d 'option of groff.  It is highly compatible with Unix tbl '
complete -c tbl -s v -d 'Print the version number'

