# tee
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/tee.1
complete -c tee -s a -d 'Append the output to the files rather than overwriting them'
complete -c tee -s i -d 'Ignore the SIGINT signal'

