# texi2dvi
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/texi2dvi.1
complete -c texi2dvi -s b -l batch -d 'no interaction'
complete -c texi2dvi -s c -l clean -d 'remove all auxiliary files'
complete -c texi2dvi -s D -l debug -d 'turn on shell debugging (set -x)'
complete -c texi2dvi -s h -l help -d 'display this help and exit successfully'
complete -c texi2dvi -s o -l output -d 'leave output in OFILE (implies --clean); Only one input FILE may be specified…'
complete -c texi2dvi -s q -l quiet -d 'no output unless errors (implies --batch)'
complete -c texi2dvi -s s -l silent -d 'same as --quiet'
complete -c texi2dvi -s v -l version -d 'display version information and exit successfully'
complete -c texi2dvi -s V -l verbose -d 'report on what is done . SS "TeX tuning:"'
complete -c texi2dvi -s @ -d 'use @input instead of input; for preloaded Texinfo'
complete -c texi2dvi -s e -s E -l expand -d 'force macro expansion using makeinfo'
complete -c texi2dvi -s I -d 'search DIR for Texinfo files'
complete -c texi2dvi -s l -l language -d 'specify the LANG of FILE (LaTeX or Texinfo)'
complete -c texi2dvi -s p -l pdf -d 'use pdftex or pdflatex for processing'
complete -c texi2dvi -s r -l recode -d 'call recode before TeX to translate input characters'
complete -c texi2dvi -s t -l command -d 'insert CMD in copy of input file'

