# tfmtodit
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/tfmtodit.1
complete -c tfmtodit -s v -d 'Print the version number'
complete -c tfmtodit -s s -d 'The font is special'
complete -c tfmtodit -s k -d 'The skewchar of this font is at position R n '
complete -c tfmtodit -s g -d 'option.  The'

