# tftpd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/tftpd.8
complete -c tftpd -s d -d 'Enable verbose debugging messages to syslogd 8'
complete -c tftpd -s g -d 'Change gid to that of group on startup'
complete -c tftpd -s i -d 'Enable insecure mode, no realpath 3'
complete -c tftpd -s l -d 'Logs all requests using syslog 3'
complete -c tftpd -s n -d 'Suppresses negative acknowledgement of requests for nonexistent relative file…'
complete -c tftpd -s s -d 'tftpd will chroot 2 to directory on startup'
complete -c tftpd -s u -d 'Change uid to that of user on startup'

