# timerfires
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/timerfires.1
complete -c timerfires -s t -d 'Run only for timeout seconds; then exit'
complete -c timerfires -s p -d 'Analyze only timers from the process with process ID pid'
complete -c timerfires -s n -d 'Analyze only timers from processes with name name'
complete -c timerfires -s s -d 'Show call stacks for "sleep"-type timers'

