# tkcon
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/tkcon.1
complete -c tkcon -o argv -d 'Causes TkCon to stop evaluating arguments and set the remaining args to be ar…'
complete -c tkcon -o 'color-<color>' -d 'Sets the requested color type to the specified color for tkcon'
complete -c tkcon -o eval -o main -s e -d 'A Tcl script to eval in each main interpreter'
complete -c tkcon -o exec -d 'Sets the named slave that tkcon operates in'
complete -c tkcon -o font -d 'Sets the font that tkcon uses for its text windows'
complete -c tkcon -o nontcl -d 'Sets ::tkcon::OPT(nontcl) to TCL_BOOLEAN (see tkconrc(5))'
complete -c tkcon -o package -o load -d 'Packages to automatically load into the slave interpreters (i. e.  "Tk")'
complete -c tkcon -o rcfile -d 'Specify an alternate tkcon resource file name'
complete -c tkcon -o root -d 'Makes the named widget the root name of all consoles (i. e. tkcon)'
complete -c tkcon -o slave -d 'A Tcl script to eval in each slave interpreter'

