# tmdiagnose
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/tmdiagnose.8
complete -c tmdiagnose -s h -d 'Print full usage'
complete -c tmdiagnose -s d -d 'Delay the start of the diagnostic by sec seconds'
complete -c tmdiagnose -s f -d 'Write the diagnostic to the specified path'
complete -c tmdiagnose -s m -d 'Gather memory diagnostics for backupd and Finder'
complete -c tmdiagnose -s r -d 'Do not reveal the diagnostic in Finder when finished'

