# tokenadmin
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/tokenadmin.8
complete -c tokenadmin -s h -d 'With no arguments, shows a list of all commands'
complete -c tokenadmin -s q -d 'Makes tokenadmin less verbose'
complete -c tokenadmin -s v -d 'Makes tokenadmin more verbose'
complete -c tokenadmin -s u -d 'Specify the short (i. e. , login) name to be used for the account'
complete -c tokenadmin -s l -d 'Specify the full name to be used for the account'
complete -c tokenadmin -s p -d 'Password for the user\'s login keychain (optional)'

