# tops
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/tops.1
complete -c tops -o help -d 'Displays the tops syntax line'
complete -c tops -o verbose -d 'Prints out the source code lines that are being changed by the command'
complete -c tops -o nocontext -d 'Instead of printing the whole source code line that is being changed or searc…'
complete -c tops -o nofileinfo -d 'Does not print the file name and line number information in verbose messages'
complete -c tops -o semiverbose -d 'Shows how much of the file has been processed'
complete -c tops -o dont -d 'Shows what changes would be made to the source code without actually performi…'
complete -c tops -o scriptfile -d 'Specifies the script file containing the rules that tops will apply to your c…'
complete -c tops -o classfile -d 'Specifies a file that describes the class hierarchy used by the files being p…'

