# tput
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/tput.1
complete -c tput -o Ttype -d 'indicates the type of terminal'
complete -c tput -s S -d 'allows more than one capability per invocation of tput'
complete -c tput -s V -d 'reports the version of ncurses which was used in this program, and exits'

