# tr
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/tr.1
complete -c tr -s C -d 'Complement the set of characters in string1, that is C Li ab includes every c…'
complete -c tr -s c -d 'Same as C but complement the set of values in string1'
complete -c tr -s d -d 'Delete characters in string1 from the input'
complete -c tr -s s -d 'Squeeze multiple occurrences of the characters listed in the last operand (ei…'
complete -c tr -s u -d 'Guarantee that any output is unbuffered'

