# traceroute6
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/traceroute6.8
complete -c traceroute6 -s d -d 'Debug mode'
complete -c traceroute6 -s f -d 'Specify how many hops to skip in trace'
complete -c traceroute6 -s g -d 'Specify intermediate gateway traceroute6 ( uses routing header)'
complete -c traceroute6 -s I -d 'Use ICMP6 ECHO instead of UDP datagrams'
complete -c traceroute6 -s l -d 'Print both host hostnames and numeric addresses'
complete -c traceroute6 -s m -d 'Specify maximum hoplimit, up to 255.  The default is 30 hops'
complete -c traceroute6 -s n -d 'Do not resolve numeric address to hostname'
complete -c traceroute6 -s N -d 'Use a packet with no upper layer header for the probes, instead of UDP datagr…'
complete -c traceroute6 -s p -d 'Set UDP port number to port'
complete -c traceroute6 -s q -d 'Set the number of probe per hop count to probes'
complete -c traceroute6 -s r -d 'Bypass the normal routing tables and send directly to a host on an attached n…'
complete -c traceroute6 -s s -d 'Src specifies the source IPv6 address to be used'
complete -c traceroute6 -s U -d 'Use UDP datagrams for the probes.  This is the default'
complete -c traceroute6 -s v -d 'Be verbose'
complete -c traceroute6 -s w -d 'Specify the delay time between probes'

