# traptoemail
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/traptoemail.1
complete -c traptoemail -s f -d 'sender address, defaults to "root"'
complete -c traptoemail -s s -d 'SMTP server, defaults to "localhost"'

