# tsig-keygen
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/tsig-keygen.8
complete -c tsig-keygen -s a -d 'Specifies the algorithm to use for the TSIG key'
complete -c tsig-keygen -s h -d 'Prints a short summary of options and arguments'
complete -c tsig-keygen -s k -d 'Specifies the key name of the DDNS authentication key'
complete -c tsig-keygen -s q -d '(ddns-confgen only'
complete -c tsig-keygen -s r -d 'Specifies a source of random data for generating the authorization'
complete -c tsig-keygen -s s -d '(ddns-confgen only'
complete -c tsig-keygen -s z -d '(ddns-confgen only'

