# tsort
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/tsort.1
complete -c tsort -s l -d 'Search for and display the longest cycle.  Can take a very long time'
complete -c tsort -s q -d 'Do not display informational messages about cycles'

