# tty
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/tty.1
complete -c tty -s s -d 'Do not write the terminal name; only the exit status is affected when this op…'

