# ul
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ul.1
complete -c ul -s i -d 'Underlining is indicated by a separate line containing appropriate dashes \\-'
complete -c ul -s t -d 'Overrides the terminal type specified in the environment with terminal'

