# umount
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/umount.8
complete -c umount -s a -d 'All the filesystems described via getfsent 3 are unmounted'
complete -c umount -s A -d 'All the currently mounted filesystems except the root are unmounted'
complete -c umount -s f -d 'The filesystem is forcibly unmounted'
complete -c umount -s h -d 'Only filesystems mounted from the specified host will be unmounted'
complete -c umount -s t -d 'Is used to indicate the actions should only be taken on filesystems of the sp…'
complete -c umount -s v -d 'Verbose, additional information is printed out as each filesystem is unmounted'

