# umtest
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/umtest.1
complete -c umtest -s a -d 'Description of -a flag'
complete -c umtest -s b -d 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

