# uname
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/uname.1
complete -c uname -s a -d 'Behave as though all of the options mnrsv were specified'
complete -c uname -s m -d 'print the machine hardware name'
complete -c uname -s n -d 'print the nodename (the nodename may be a name that the system is known by to…'
complete -c uname -s p -d 'print the machine processor architecture name'
complete -c uname -s r -d 'print the operating system release'
complete -c uname -s s -d 'print the operating system name'
complete -c uname -s v -d 'print the operating system version'

