# unifdef
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/unifdef.1
complete -c unifdef -s D -d 'Specify that a symbol is defined to a given value which is used when evaluati…'
complete -c unifdef -s U -d 'Specify that a symbol is undefined'
complete -c unifdef -s b -d 'Replace removed lines with blank lines instead of deleting them'
complete -c unifdef -s B -d 'Compress blank lines around a deleted section'
complete -c unifdef -s c -d 'If the c flag is specified, then the operation of unifdef is complemented, i'
complete -c unifdef -s d -d 'Turn on printing of debugging messages.  Pp'
complete -c unifdef -s e -d 'Because unifdef processes its input one line at a time, it cannot remove prep…'
complete -c unifdef -s K -d 'Always treat the result of && and || operators as unknown if either operand i…'
complete -c unifdef -s k -d 'Process #if and #elif lines with constant expressions'
complete -c unifdef -s n -d 'Add #line directives to the output following any deleted lines, so that error…'
complete -c unifdef -s o -d 'Write output to the file outfile instead of the standard output'
complete -c unifdef -s s -d 'Instead of processing the input file as usual, this option causes unifdef to …'
complete -c unifdef -s S -d 'Like the s option, but the nesting depth of each symbol is also printed'
complete -c unifdef -s t -d 'Disables parsing for C comments and line continuations, which is useful for p…'
complete -c unifdef -o iD
complete -c unifdef -o iU -d 'Ignore #ifdef Ns s'
complete -c unifdef -s I -d 'Specifies to unifdef unifdefall an additional place to look for #include files'
complete -c unifdef -s V -d 'Print version details'

