# unifdefall
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/unifdefall.1
complete -c unifdefall -s D -d 'Specify that a symbol is defined to a given value which is used when evaluati…'
complete -c unifdefall -s U -d 'Specify that a symbol is undefined'
complete -c unifdefall -s b -d 'Replace removed lines with blank lines instead of deleting them'
complete -c unifdefall -s B -d 'Compress blank lines around a deleted section'
complete -c unifdefall -s c -d 'If the c flag is specified, then the operation of unifdefall is complemented,…'
complete -c unifdefall -s d -d 'Turn on printing of debugging messages.  Pp'
complete -c unifdefall -s e -d 'Because unifdefall processes its input one line at a time, it cannot remove p…'
complete -c unifdefall -s K -d 'Always treat the result of && and || operators as unknown if either operand i…'
complete -c unifdefall -s k -d 'Process #if and #elif lines with constant expressions'
complete -c unifdefall -s n -d 'Add #line directives to the output following any deleted lines, so that error…'
complete -c unifdefall -s o -d 'Write output to the file outfile instead of the standard output'
complete -c unifdefall -s s -d 'Instead of processing the input file as usual, this option causes unifdefall …'
complete -c unifdefall -s S -d 'Like the s option, but the nesting depth of each symbol is also printed'
complete -c unifdefall -s t -d 'Disables parsing for C comments and line continuations, which is useful for p…'
complete -c unifdefall -o iD
complete -c unifdefall -o iU -d 'Ignore #ifdef Ns s'
complete -c unifdefall -s I -d 'Specifies to unifdefall unifdefall an additional place to look for #include f…'
complete -c unifdefall -s V -d 'Print version details'

