# uuchk
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/uuchk.8
complete -c uuchk -s s -l system -d 'Display the configuration for just the specified system, rather than for all …'
complete -c uuchk -s I -l config -d 'Set configuration file to use'
complete -c uuchk -s v -l version -d 'Report version information and exit'
complete -c uuchk -l help -d 'Print a help message and exit'

