# uuconv
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/uuconv.1
complete -c uuconv -s i -l input -d 'Set input type (one of taylor, v2, hdb)'
complete -c uuconv -s o -l output -d 'Set output type (one of taylor, v2, hdb)'
complete -c uuconv -s p -l program -d 'Program to convert (e. g. , uucp or cu)'
complete -c uuconv -s v -l version -d 'Report version information and exit'
complete -c uuconv -l help -d 'Print a help message and exit'

