# uuencode
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/uuencode.1
complete -c uuencode -s m -d 'Use the Base64 method of encoding, rather than the traditional uuencode uuenc…'
complete -c uuencode -s o -d 'Output to output_file instead of standard output'
complete -c uuencode -s c -d 'Decode more than one uuencode\'d file from file if possible'
complete -c uuencode -s i -d 'Do not overwrite files'
complete -c uuencode -s p -d 'Decode file and write output to standard output'
complete -c uuencode -s s -d 'Do not strip output pathname to base filename'

