# uuidgen
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/uuidgen.1
complete -c uuidgen -o hdr -d 'Emit CoreFoundation CFUUID-based source code for using the uuid in a header'

