# uulog
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/uulog.1
complete -c uulog -s '#' -s n -l lines -d 'Here \'#\' is a number; e. g. , `-10\''
complete -c uulog -s s -l system -d 'Display only log entries pertaining to the specified system'
complete -c uulog -s u -l user -d 'Display only log entries pertaining to the specified user'
complete -c uulog -s D -l debuglog -d 'Display the debugging log file'
complete -c uulog -s S -l statslog -d 'Display the statistics log file'
complete -c uulog -s F -l follow -d 'Keep displaying the log file forever, printing new lines as they are appended…'
complete -c uulog -s f -d 'Keep displaying the log file forever, displaying only log entries pertaining …'
complete -c uulog -s X -l debug -d 'Turn on particular debugging types'
complete -c uulog -s I -l config -d 'Set configuration file to use'
complete -c uulog -s v -l version -d 'Report version information and exit'
complete -c uulog -l help -d 'Print a help message and exit'

