# uuname
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/uuname.1
complete -c uuname -s a -l aliases -d 'List all aliases for remote systems, as well as their canonical names'
complete -c uuname -s l -l local -d 'Print the UUCP name of the local system, rather than listing the names of all…'
complete -c uuname -s x -l debug -d 'Turn on particular debugging types'
complete -c uuname -s I -l config -d 'Set configuration file to use'
complete -c uuname -s v -l version -d 'Report version information and exit'
complete -c uuname -l help -d 'Print a help message and exit.  SEE ALSO uucp(1) FILES'

