# uupick
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/uupick.1
complete -c uupick -s s -l system -d 'Used to restrict `uupick\' to only present files transferred from a particular…'
complete -c uupick -s x -l debug -d 'Turn on particular debugging types'
complete -c uupick -s I -l config -d 'Set configuration file to use'
complete -c uupick -s v -l version -d 'Report version information and exit'
complete -c uupick -l help -d 'Print a help message and exit'

