# uux
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/uux.1
complete -c uux -s p -l stdin -d 'Read standard input and use it as the standard input for the command to be ex…'
complete -c uux -s c -l nocopy -d 'Do not copy local files to the spool directory.   This is the default'
complete -c uux -s C -l copy -d 'Copy local files to the spool directory'
complete -c uux -s l -l link -d 'Link local files into the spool directory'
complete -c uux -s g -l grade -d 'Set the grade of the file transfer command'
complete -c uux -s n -l notification -d 'Do not send mail about the status of the job, even if it fails'
complete -c uux -s z -d 'Send mail about the status of the job if an error occurs'
complete -c uux -s r -l nouucico -d 'Do not start the  uucico (8) daemon immediately; merely queue up the executio…'
complete -c uux -s j -l jobid -d 'Print jobids on standard output'
complete -c uux -s a -l requestor -d 'Report job status to the specified e-mail address'
complete -c uux -s x -l debug -d 'Turn on particular debugging types'
complete -c uux -s I -l config -d 'Set configuration file to use'
complete -c uux -s v -l version -d 'Report version information and exit'
complete -c uux -l kill -d 'switch of uustat (1), which will make the execution impossible to complete'
complete -c uux -l help -d 'Print a help message and exit.  EXAMPLES uux -z - sys1!rmail user1'

