# uuxqt
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/uuxqt.8
complete -c uuxqt -s c -l command -d 'Only execute requests for the specified command.   For example: . br . in + '
complete -c uuxqt -s s -l system -d 'Only execute requests originating from the specified system'
complete -c uuxqt -s x -l debug -d 'Turn on particular debugging types'
complete -c uuxqt -s I -l config -d 'Set configuration file to use'
complete -c uuxqt -s v -l version -d 'Report version information and exit'
complete -c uuxqt -s q -d or
complete -c uuxqt -l nouuxqt -d 'option)'
complete -c uuxqt -l help -d 'Print a help message and exit'

