# vis
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/vis.1
complete -c vis -s b -d 'Turns off prepending of backslash before up-arrow control sequences and meta …'
complete -c vis -s c -d 'Request a format which displays a small subset of the non-printable character…'
complete -c vis -s F -d 'Causes vis to fold output lines to foldwidth columns (default 80), like fold …'
complete -c vis -s f -d 'Same as F'
complete -c vis -s l -d 'Mark newlines with the visible sequence \\e$, followed by the newline'
complete -c vis -s n -d 'Turns off any encoding, except for the fact that backslashes are still double…'
complete -c vis -s o -d 'Request a format which displays non-printable characters as an octal number, …'
complete -c vis -s s -d 'Only characters considered unsafe to send to a terminal are encoded'
complete -c vis -s t -d 'Tabs are also encoded'
complete -c vis -s w -d 'White space (space-tab-newline) is also encoded'

