# vpnd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/vpnd.8
complete -c vpnd -s d -d 'Do not move to background and print log strings to the terminal'
complete -c vpnd -s h -d 'Print usage summary and exit'
complete -c vpnd -s i -d 'Server_id in the plist file that defines the configuration to be run'
complete -c vpnd -s n -d 'Do not move to background, print log information to the terminal, and quit af…'
complete -c vpnd -s x -d 'Do not move to background'

