# vsdbutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/vsdbutil.8
complete -c vsdbutil -s a -d 'adopts (activates) on-disk ownership on the specified path'
complete -c vsdbutil -s c -d 'checks the status of the ownership usage on the specified path'
complete -c vsdbutil -s d -d 'disowns (deactivates) the on-disk ownership on the specified path'
complete -c vsdbutil -s i -d 'initializes the ownership database to include all mounted HFS+ and APFS volum…'
complete -c vsdbutil -s h -d 'prints out a simple help message El Pp The vsdbutil command is deprecated; us…'

