# vtool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/vtool.1
complete -c vtool -o arch -d 'Specifies the architecture, arch, for vtool to operate on when the file is a …'
complete -c vtool -s h -d 'Print full usage'
complete -c vtool -s o -d 'Commands that create new files write to the out_file file specified by the ou…'
complete -c vtool -s r -d 'When used with set-build-version or set-version-min the replace option instru…'
complete -c vtool -o remove-build-tool -d 'Removes tool from the platform build version'
complete -c vtool -o remove-build-version -d 'Removes the build version for the specified platform'
complete -c vtool -o remove-source-version -d 'Removes the source version from the Mach-O file.  Must be used with output'
complete -c vtool -o set-build-tool -d 'Updates the build version load command for platform to include the specified …'
complete -c vtool -o set-build-version -d 'Create or update the LC_BUILD_VERSION load command for platform to include th…'
complete -c vtool -o set-source-version -d 'Create or update the source version load command.  version takes the format A'
complete -c vtool -o set-version-min -d 'Create or update an LC_VERSION_MIN_* load command for platform'
complete -c vtool -o show -d 'Display the build and source versions within the specified file'
complete -c vtool -o show-build -d 'Display the build versions within the specified file'
complete -c vtool -o show-source -d 'Display the source version within the specified file'
complete -c vtool -o show-space -d 'Show the space in the file consumed by the mach header and the existing load …'

