# w
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/w.1
complete -c w -s h -d 'Suppress the heading'
complete -c w -s i -d 'Output is sorted by idle time'

