# wall
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/wall.1
complete -c wall -s g -d 'Send messages to users in this group'

