# wc
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/wc.1
complete -c wc -s c -d 'The number of bytes in each input file is written to the standard output'
complete -c wc -s l -d 'The number of lines in each input file is written to the standard output'
complete -c wc -s m -d 'The number of characters in each input file is written to the standard output'
complete -c wc -s w -d 'The number of words in each input file is written to the standard output'

