# weakpass_edit
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/weakpass_edit.8
complete -c weakpass_edit -s p -d 'add or delete a passphrase, provided as a command-line argument, to the weak …'
complete -c weakpass_edit -s f -d 'add or delete all passphrases contained in a file'

