# whereis
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/whereis.1
complete -c whereis -s B -d 'Specify directories to search for binaries.  Requires the f option'
complete -c whereis -s M -d 'Specify directories to search for manual pages.  Requires the f option'
complete -c whereis -s a -d 'Report all matches instead of only the first of each requested type'
complete -c whereis -s b -d 'Search for binaries'
complete -c whereis -s f -d 'Delimits the list of directories after the B, M, or S options, and indicates …'
complete -c whereis -s m -d 'Search for manual pages'
complete -c whereis -s q -d quiet
complete -c whereis -s u -d 'Search for unusual entries'

