# who
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/who.1
complete -c who -s a -d 'Same as bdlprTtu'
complete -c who -s b -d 'Time of last system boot'
complete -c who -s d -d 'Print dead processes'
complete -c who -s H -d 'Write column headings above the regular output'
complete -c who -s l -d 'Print system login processes (unsupported)'
complete -c who -s m -d 'Only print information about the current terminal'
complete -c who -s p -d 'Print active processes spawned by launchd 8 (unsupported)'
complete -c who -s q -d 'Quick mode : List only the names and the number of users currently logged on'
complete -c who -s r -d 'Print the current runlevel.  This is meaningless on Mac OS X'
complete -c who -s s -d 'List only the name, line and time fields.  This is the default'
complete -c who -s T -d 'Print a character after the user name indicating the state of the terminal li…'
complete -c who -s t -d 'Print last system clock change (unsupported)'
complete -c who -s u -d 'Print the idle time for each user, and the associated process ID'

