# wspd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/wspd.8
complete -c wspd -l s -d 'The UNIX socket wspd listens to'
complete -c wspd -l d -d 'The delay between last connection was disconnected and the time wspd will clo…'

