# xattr
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/xattr.1
complete -c xattr -s l -d 'By default, the first two command forms either displays just the attribute na…'
complete -c xattr -s r -d 'If a file argument is a directory, act as if the entire contents of the direc…'
complete -c xattr -s s -d 'If a file argument is a symbolic link, act on the symbolic link itself, rathe…'
complete -c xattr -s v -d 'Force the file name to be displayed, even for a single file'
complete -c xattr -s x -d 'Force the attribute value to be displayed in the hexadecimal representation'

