# xccov
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xccov.1
complete -c xccov -l only-targets -d 'Only view the list of targets'
complete -c xccov -l files-for-target -d 'Only view the source files in the target(s) with the given name'
complete -c xccov -l functions-for-file -d 'Only view the functions/methods for the file(s) with the given name or path'
complete -c xccov -l json -d 'View the data in JSON format (default is human readable text)'
complete -c xccov -l path-equivalence -d 'If specified, map source file paths in before'
complete -c xccov -l file-list -d 'When viewing an archive, list all of the files for which the archive contains…'
complete -c xccov -l file -d 'View the line and subrange execution counts stored in the archive for the fil…'
complete -c xccov -l report -d 'View the coverage report contained within a result bundle'
complete -c xccov -l archive -d 'View the coverage archive contained within a result bundle'
complete -c xccov -l outReport -d 'A path where the merged report will be placed.  Defaults to \'merged'
complete -c xccov -l outArchive -d 'A path where the merged archive will be placed.  Defaults to \'merged'
complete -c xccov -l ---------------------------------------------------------------- -l ------------- -d 'HelloWorld. app                                                     57'

