# xcode-select
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/xcode-select.1
complete -c xcode-select -s h -l help -d 'Prints the usage message'
complete -c xcode-select -s s -l switch -d 'Sets the active developer directory to the given path, for example /Applicati…'
complete -c xcode-select -s p -l print-path -d 'Prints the path to the currently selected developer directory'
complete -c xcode-select -s r -l reset -d 'Unsets any user-specified developer directory, so that the developer director…'
complete -c xcode-select -s v -l version -d 'Prints xcode-select version information'
complete -c xcode-select -l install -d 'Opens a user interface dialog to request automatic installation of the comman…'

