# xcresulttool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xcresulttool.1
complete -c xcresulttool -l path -d 'Path to the result bundle'
complete -c xcresulttool -l output-path -d 'Output path for the exported file or directory'
complete -c xcresulttool -l format -d 'Controls output format'
complete -c xcresulttool -l id -d 'Provides the desired object\'s ID (hash)'
complete -c xcresulttool -l hash -d 'Used by formatDescription get to print only the hash of the format (can be co…'
complete -c xcresulttool -l include-event-stream-types -d 'Used by formatDescription get to also include event stream types in addition …'
complete -c xcresulttool -o resultBundlePath -d ' where PATH is the desired path ending with . xcresult.  COMMANDS'
complete -c xcresulttool -l type -d 'Used by export to identify whether to export the given data as a file or dire…'

