# xcrun
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xcrun.1
complete -c xcrun -s v -l verbose -d 'Add verbose information on how the tool lookup is performed'
complete -c xcrun -s n -l no-cache -d 'Don\\(aqt consult the cache when looking up values'
complete -c xcrun -s k -l kill-cache -d 'Removes the cache.  Causes all values to be re-cached'
complete -c xcrun -l sdk -d 'Specifies which SDK to search for tools'
complete -c xcrun -l toolchain -d 'Specifies which toolchain to use to perform the lookup'
complete -c xcrun -s l -l log -d 'Print the full command line that is invoked'
complete -c xcrun -s f -l find -d 'Enable "find" mode, in which the resolved tool path is printed instead of the…'
complete -c xcrun -s r -l run -d 'Enable "run" mode, in which the resolved tool path is executed with any provi…'
complete -c xcrun -l show-sdk-path -d 'Print the path to the selected SDK'
complete -c xcrun -l show-sdk-version -d 'Print the version number of the selected SDK'
complete -c xcrun -l show-sdk-build-version -d 'Print the build version number of the selected SDK'
complete -c xcrun -l show-sdk-platform-path -d 'Print the path to the platform for the selected SDK'
complete -c xcrun -l show-sdk-platform-version -d 'Print the version number of the platform for the selected SDK'

