# xcscontrol
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xcscontrol.1
complete -c xcscontrol -s h -l help -l usage -d 'Prints basic usage information'
complete -c xcscontrol -l version -d 'Displays version information'
complete -c xcscontrol -l preflight -d 'Preflights the Xcode Server service'
complete -c xcscontrol -l initialize -d 'Initializes Xcode Server, must be called before the service is usable'
complete -c xcscontrol -l reset -d 'Resets Xcode Server, removing all service data and stopping all services'
complete -c xcscontrol -l restart -d 'Restart Xcode Server without removing any service data'
complete -c xcscontrol -l shutdown -d 'Stops Xcode Server'

