# xcsgenerator
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xcsgenerator.1
complete -c xcsgenerator -s a -d 'Description of -a flag'
complete -c xcsgenerator -s b -d 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

