# xscertadmin
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/xscertadmin.8
complete -c xscertadmin -o x/--xml -d 'Returns output to stdout in xml format'
complete -c xscertadmin -o v/--version -d 'Print the version of the tool'
complete -c xscertadmin -o d/--debug -d 'Sets the level of diagnostic message detail, 0 for off and 1 for on'
complete -c xscertadmin -o a/--all -d 'List all CRLs El ADD OPTIONS -tag -width stringtosetspacing12'
complete -c xscertadmin -o f/--file -d 'A file containing names'
complete -c xscertadmin -o i/--issuer -d 'The common name of the issuer of the certificate'
complete -c xscertadmin -o r/--reason -d 'The revocation reason code'
complete -c xscertadmin -o s/--serial -d 'The serial number of the certificate to revoke'
complete -c xscertadmin -o t/--type -d 'The record type: user, device, computer or recordType'

