# xssendevent
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/xssendevent.8
complete -c xssendevent -s e -d 'Tells xssendevent to load a file of events in text plist format, one "event" …'

