# xsubpp5
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/xsubpp5.18.1
complete -c xsubpp5 -o hiertype -d 'Retains \'::\' in type names so that \\*(C+ hierarchical types can be mapped'
complete -c xsubpp5 -o except -d 'Adds exception handling stubs to the C code'
complete -c xsubpp5 -o typemap -d 'Indicates that a user-supplied typemap should take precedence over the defaul…'
complete -c xsubpp5 -o output -d 'Specifies the name of the output file to generate'
complete -c xsubpp5 -s v -d 'Prints the xsubpp version number to standard output, then exits'
complete -c xsubpp5 -o prototypes -d 'By default xsubpp will not automatically generate prototype code for all xsubs'
complete -c xsubpp5 -o noversioncheck -d 'Disables the run time test that determines if the object file (derived from t…'
complete -c xsubpp5 -o nolinenumbers -d 'Prevents the inclusion of \'#line\' directives in the output'
complete -c xsubpp5 -o nooptimize -d 'Disables certain optimizations'
complete -c xsubpp5 -o noinout -d 'Disable recognition of \\f(CW\\*(C`IN\\*(C\', \\f(CW\\*(C`OUT_LIST\\*(C\' and \\f(CW\\*…'
complete -c xsubpp5 -o noargtypes -d 'Disable recognition of ANSI-like descriptions of function signature'

