# yapp
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/yapp.1
complete -c yapp -s v -d 'Creates a file grammar. output describing your parser'
complete -c yapp -s s -d 'Create a standalone module in which the driver is included'
complete -c yapp -s n -d 'Disable source file line numbering embedded in your parser module'
complete -c yapp -s m -d 'Gives your parser module the package name (or name space or module name or cl…'
complete -c yapp -s o -d 'The compiled output file will be named outfile for your parser module'
complete -c yapp -s t -d 'The -t filename option allows you to specify a file which should be  used as …'
complete -c yapp -s b -d 'If you work on systems that understand so called shebangs, and your generated…'
complete -c yapp -s V -d 'Display current version of Parse::Yapp and gracefully exits'

