# zdump
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/zdump.8
complete -c zdump -l version -d 'Output version information and exit'
complete -c zdump -s v -d 'For each zonename on the command line, print the time at the lowest possible …'
complete -c zdump -s c -d 'Cut off the verbose output near the start of the given year'

