# zic
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/zic.8
complete -c zic -l version -d 'Output version information and exit'
complete -c zic -s D -d 'Do not automatically create directories'
complete -c zic -s d -d 'Create time conversion information files in the named directory rather than i…'
complete -c zic -s g -d 'After creating each output file, change its group ownership to the specified …'
complete -c zic -s L -d 'Read leap second information from the file with the given name'
complete -c zic -s l -d 'Use the given time zone as local time'
complete -c zic -s m -d 'After creating each output file, change its access mode to mode'
complete -c zic -s p -d 'Use the given "time zone" Ns \'s rules when handling POSIX-format time zone en…'
complete -c zic -s u -d 'After creating each output file, change its owner to user (which can be eithe…'
complete -c zic -s v -d 'Complain if a year that appears in a data file is outside the range of years …'
complete -c zic -s s -d 'Limit time values stored in output files to values that are the same whether …'
complete -c zic -s y -d 'Use the given command rather than yearistype when checking year types (see be…'

