# zprint
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/zprint.1
complete -c zprint -s c -d '(Default) zprint prints zone info in columns'
complete -c zprint -s d -d 'Display deltas over time, showing any zones that have achieved a new maximum …'
complete -c zprint -s h -d '(Default) Shows headings for the columns printed with the c option'
complete -c zprint -s l -d '(Default) Show all wired memory information after the zone information'
complete -c zprint -s L -d 'Do not show all wired memory information after the zone information'
complete -c zprint -s s -d 'zprint sorts the zones, showing the zone wasting the most memory first'
complete -c zprint -s t -d 'For each zone, zprint calculates the total size of allocations from the zone …'
complete -c zprint -s w -d 'For each zone, zprint calculates how much space is allocated but not currentl…'

