#!/bin/bash

# macdot — glryan@uw.edu	|	https://griffinryan.com/

# dotfile backup script
NC='\33[0m';              # No Color
RED='\33[0;31m';          # Red
LIGHTRED='\33[1;31m';      # Light Red
GREEN='\33[0;32';          # Green
LIGHTGREEN='\33[1;32m';     # Light Green
BLUE='\33[0;34m';          # Blue
LIGHTBLUE='\33[1;34m';     # Light Blue
CYAN='\33[0;36m';          # Cyan
LIGHTCYAN='\33[1;36m';     # Light Cyan
YELLOW='\33[0;33m';        # Yellow
LIGHTYELLOW='\33[1;33m';   # Light Yellow
PURPLE='\33[0;35m';        # Purple
LIGHTPURPLE='\33[1;35m';   # Light Purple

function dotfileBackup() {
    # prompt a path for backup folder.
    printf "    Please \33[1;32menter\33[0m a \33[1;34mtitle\33[0m for your \33[1;34mbackup directory\33[0m:  \33[1;32m" 
    read REPLY
    printf "\33[0m"
    echo
    PTD=$PWD/$REPLY
    rm -rf $PWD/$REPLY 2>/dev/null
    mkdir $PWD/$REPLY

    # individually (and recursively) add parent directories.
    /bin/cp -rf ~/.vim $PTD/.vim 2>/dev/null
    /bin/cp -rf ~/.local $PTD/.vim 2>/dev/null
    /bin/cp -rf ~/.config $PTD/.vim 2>/dev/null
    /bin/cp -rf ~/.iterm $PTD/.iterm 2>/dev/null
    /bin/cp -rf ~/.fonts $PTD/.fonts 2>/dev/null

    # wildcard * to add all parent files.
    /bin/cp -f ~/.* $PTD/ 2>/dev/null
}

# Help page for macdot - a macOS configuration tool.
    toilet -d /opt/homebrew/Cellar/macdot/**/fonts -f larry3d 'macdot' | boxes -d parchment | lolcat -p 5
# Install dotfiles to ~/.* from /usr/local/share/torpdots/dotfiles/.*
if [ "$1" == "--force" -o "$1" == "-f" ]; then
    # force dotfileInstall() with -f argument
    dotfileBackup

    # Status message.
    printf "    '\33[1;35mmacdot\33[0m \33[1;33mbackup\33[0m' \33[1;32msuccessfully restored\33[0m dotfiles from \33[1;34m/~/.macdot/\33[0m.\n"
else
    # Status message.
    printf "    This will \33[1;34mbackup existing\33[0m files in the home directory. \33[1;31mAre you sure\33[0m? (y/n) " 
    read
    echo;
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        dotfileBackup

        # Status message.
        printf "    '\33[1;35mmacdot\33[0m \33[1;33mbackup\33[0m' \33[1;32msuccessfully backed up\33[0m dotfiles to:\n"
        printf "    \33[1;34m$PTD/\33[0m\n\n"
    fi;
fi;
unset dotfileBackup

