#!/bin/bash

# macdot — glryan@uw.edu	|	https://griffinryan.com/

# dotfile management script
NC='\33[0m'               # No Color
LIGHTBLUE='\33[1;34m'     # Light Blue
LIGHTYELLOW='\33[1;33m'   # Light Yellow
LIGHTPURPLE='\33[1;35m'   # Light Purple
LIGHTRED='\33[1;31m'      # Light Red
YELLOW='\33[0;33m';        # Yellow

function dotfileInstall() {

    dotfileSave
    
    # wildcard * to add all parent files.
    /bin/cp /opt/homebrew/Cellar/macdot/*.*.*/dotfiles/.* ~/ 2>/dev/null

    # individually (and recursively) add parent directories.
    /bin/cp -rf /opt/homebrew/Cellar/macdot/*.*.*/dotfiles/.vim ~/.vim
    /bin/cp -rf /opt/homebrew/Cellar/macdot/*.*.*/dotfiles/.local ~/.local
    /bin/cp -rf /opt/homebrew/Cellar/macdot/*.*.*/dotfiles/.config ~/.config
    /bin/cp -rf /opt/homebrew/Cellar/macdot/*.*.*/dotfiles/.iterm ~/.iterm
    /bin/cp -rf /opt/homebrew/Cellar/macdot/*.*.*/dotfiles/.fonts ~/.fonts

    # move iTerm2 .plist file to current shell.
    /bin/cp /opt/homebrew/Cellar/macdot/*.*.*/dotfiles/.iterm/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist
    
    # make sure of Fish as default shell.
    # chsh -s /opt/homebrew/bin/fish
}

function dotfileSave() {
    # make a new /.macdot/ folder.
    cd $HOME
    mkdir .macdot 2>/dev/null
    mkdir .macdot/.vim 2>/dev/null
    mkdir .macdot/.local 2>/dev/null
    mkdir .macdot/.config 2>/dev/null
    mkdir .macdot/.iterm 2>/dev/null
    mkdir .macdot/.fonts 2>/dev/null

    # individually (and recursively) add parent directories.
    /bin/cp -r ~/.vim ~/.macdot/.vim 2>/dev/null
    /bin/cp -r ~/.local ~/.macdot/.local 2>/dev/null
    /bin/cp -r ~/.config ~/.macdot/.config 2>/dev/null
    /bin/cp -r ~/.iterm ~/.macdot/.iterm 2>/dev/null
    /bin/cp -r ~/.fonts ~/.macdot/.fonts 2>/dev/null

    # wildcard * to add all parent files.
    /bin/cp ~/.* ~/.macdot/ 2>/dev/null
}

# Help page for macdot - a macOS configuration tool.
toilet -d /opt/homebrew/Cellar/macdot/**/fonts -f larry3d 'macdot' | boxes -d parchment | lolcat -p 5
# Status message.
printf "    Now installing all \33[1;35mmacdot\33[0m dotfiles to home directory...\n"

# Install dotfiles to ~/.* from /usr/local/share/torpdots/dotfiles/.*
if [ "$1" == "--force" -o "$1" == "-f" ]; then
    # force dotfileInstall() with -f argument
    dotfileInstall
    # Status message.
    printf "       '\33[1;35mmacdot\33[0m \33[1;33msave\33[0m' backed up dotfiles to \33[1;34m/~/.macdot/\33[0m.\n"
    printf "    \33[1;35mmacdot\33[0m \33[1;33mdot\33[0m has \33[1;34msuccessfully installed\33[0m all dotfiles!\n"
else
    # Status message.
    printf "    This will \33[1;31moverwrite existing\33[0m files in the home directory. \33[1;31mAre you sure\33[0m? (y/n) " 
    read
    echo;
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        dotfileInstall
        # Status message.
        printf "    \33[1;35mmacdot\33[0m \33[1;33msave\33[0m backed up dotfiles to \33[1;34m/~/.macdot/\33[0m.\n"
        printf "    \33[1;35mmacdot\33[0m \33[1;33mdot\33[0m has \33[1;32msuccessfully installed\33[0m all dotfiles!\n\n"
    fi;
fi;
unset dotfileInstall
