#!/bin/bash

# macdot — glryan@uw.edu	|	https://griffinryan.com/

# list function to show all supported formulae/casks/dotfiles
toilet -d /opt/homebrew/Cellar/macdot/**/fonts -f larry3d 'macdot' | boxes -d parchment | lolcat -p 5
