#!/bin/bash

# macdot — glryan@uw.edu	|	https://griffinryan.com/

# Help page for macdot - a macOS configuration tool.
toilet -d /opt/homebrew/Cellar/macdot/**/fonts -f larry3d 'macdot' | boxes -d parchment | lolcat -p 5

# printf "       '\33[1;35mmacdot\33[0m' to display this page.\n";
printf "       '\33[1;35mmacdot\33[0m \33[1;33msave\33[0m' to \33[1;32msave\33[0m dotfiles in \33[1;34m/~/...\33[0m to \33[1;34m/~/.macdot/\33[0m.\n";
printf "       '\33[1;35mmacdot\33[0m \33[1;33mbackup\33[0m' to \33[1;32mbackup\33[0m dotfiles to a new \33[1;34mdirectory\33[0m.\n";
printf "       '\33[1;35mmacdot\33[0m \33[1;33mrestore\33[0m' to \33[1;32mrevert\33[0m to saved dotfiles in \33[1;34m/~/.macdot/\33[0m.\n";
printf "       '\33[1;35mmacdot\33[0m \33[1;33mdot\33[0m' to \33[1;32mbackup\33[0m and \33[1;32minstall\33[0m all dotfiles (\33[1;31muse with caution!\33[0m).\n";
printf "       '\33[1;35mmacdot\33[0m \33[1;33mhelp\33[0m' to \33[1;32mdisplay more options\33[0m.\n\n";

printf "       '\33[1;35mmacdot\33[0m \33[1;33mapple\33[0m' to \33[1;32mconfigure macOS\33[0m with Applescript (\33[1;31muse with caution!\33[0m).\n";
printf "       '\33[1;35mmacdot\33[0m \33[1;33miterm\33[0m' to \33[1;32mconfigure iTerm2\33[0m preferences.\n";
printf "       '\33[1;35mmacdot\33[0m \33[1;33mkegs\33[0m' to \33[1;32minstall\33[0m popular homebrew formulae.\n";
# printf "       '\33[1;35mmacdot\33[0m \33[1;33mkegs\33[0m' to \33[1;32minstall\33[0m popular homebrew formulae.\n\n";