#!/bin/bash

# macdot — glryan@uw.edu	|	https://griffinryan.com/

# dotfile backup script

function dotfileRestore() {
  PS3="Select backup to restore from: "
  select backup in $(find ~/.macdot/* -maxdepth 0 -type d -exec basename {} \;); do break; done

  rsync -a --delete ~/.macdot/${backup}/ ~/
}

# Help page for macdot - a macOS configuration tool.
toilet -d /opt/homebrew/Cellar/macdot/**/fonts -f larry3d 'macdot' | boxes -d parchment | lolcat -p 5
# Install dotfiles to ~/.* from /usr/local/share/torpdots/dotfiles/.*
dotfileRestore

# Status message.
printf "    '\33[1;35mmacdot\33[0m \33[1;33mrestore\33[0m' \33[1;32msuccessfully restored\33[0m dotfiles from \33[1;34m/~/.macdot/\33[0m.\n\n"

unset dotfileRestore
