#!/bin/bash

# macdot — glryan@uw.edu	|	https://griffinryan.com/

# dotfile backup script
NC='\33[0m';              # No Color
RED='\33[0;31m';          # Red
LIGHTRED='\33[1;31m';      # Light Red
GREEN='\33[0;32';          # Green
LIGHTGREEN='\33[1;32m';     # Light Green
BLUE='\33[0;34m';          # Blue
LIGHTBLUE='\33[1;34m';     # Light Blue
CYAN='\33[0;36m';          # Cyan
LIGHTCYAN='\33[1;36m';     # Light Cyan
YELLOW='\33[0;33m';        # Yellow
LIGHTYELLOW='\33[1;33m';   # Light Yellow
PURPLE='\33[0;35m';        # Purple
LIGHTPURPLE='\33[1;35m';   # Light Purple

function dotfileSave() {
    timestamp="$(date +%Y%m%d%H%M)"
    if [ -f ~/.macdot/latest ]; then
      link="--link-dest=$(cat ~/.macdot/latest)"
      vimlink="${link}/.vim"
      locallink="${link}/.local"
      configlink="${link}/.config"
      itermlink="${link}/.iterm"
      fontslink="${link}/.fonts"
    fi

    mkdir -p ~/.macdot/macdot-${timestamp}

    # individually (and recursively) add parent directories.
    [ -d ~/.vim ] && rsync -a ${vimlink} ~/.vim ~/.macdot/macdot-${timestamp}/
    [ -d ~/.local ] && rsync -a ${locallink} ~/.local ~/.macdot/macdot-${timestamp}/
    [ -d ~/.config ] && rsync -a ${configlink} ~/.config ~/.macdot/macdot-${timestamp}/
    [ -d ~/.iterm ] && rsync -a ${itermlink} ~/.iterm ~/.macdot/macdot-${timestamp}/
    [ -d ~/.fonts ] && rsync -a ${fontslink} ~/.fonts ~/.macdot/macdot-${timestamp}/

    # wildcard * to add all parent files.
    rsync -a --delete --exclude=".macdot" ${link} ~/.* ~/.macdot/macdot-${timestamp}/

    echo "${HOME}/.macdot/macdot-${timestamp}" > ~/.macdot/latest
}

# Help page for macdot - a macOS configuration tool.
    toilet -d /opt/homebrew/Cellar/macdot/**/fonts -f larry3d 'macdot' | boxes -d parchment | lolcat -p 5
# Install dotfiles to ~/.* from /usr/local/share/torpdots/dotfiles/.*
if [ "$1" == "--force" -o "$1" == "-f" ]; then
    # force dotfileInstall() with -f argument
    dotfileSave
    # Status message.
    printf "    '\33[1;35mmacdot\33[0m \33[1;33msave\33[0m' \33[1;32msuccessfully backed up\33[0m dotfiles to \33[1;34m/~/.macdot/\33[0m.\n"
else
    # Status message.
    printf "    This will \33[1;34mbackup existing\33[0m files in the home directory. \33[1;31mAre you sure\33[0m? (y/n) " 
    read
    echo;
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        dotfileSave
        # Status message.
        printf "    '\33[1;35mmacdot\33[0m \33[1;33msave\33[0m' \33[1;32msuccessfully saved\33[0m dotfiles to \33[1;34m/~/.macdot/\33[0m.\n\n"
    fi;
fi;
unset dotfileSave
